/* ------------------------------------------------------------------------ */
/* Copyright (c) 2016 by Cadence Design Systems, Inc. ALL RIGHTS RESERVED.  */
/* These coded instructions, statements, and computer programs ('Cadence    */
/* Libraries') are the copyrighted works of Cadence Design Systems Inc.     */
/* Cadence IP is licensed for use with Cadence processor cores only and     */
/* must not be used for any other processors and platforms. Your use of the */
/* Cadence Libraries is subject to the terms of the license agreement you   */
/* have entered into with Cadence Design Systems, or a sublicense granted   */
/* to you by a direct Cadence licensee.                                     */
/* ------------------------------------------------------------------------ */
/*  IntegrIT, Ltd.   www.integrIT.com, info@integrIT.com                    */
/*                                                                          */
/* NatureDSP_Baseband Library                                               */
/*                                                                          */
/* This library contains copyrighted materials, trade secrets and other     */
/* proprietary information of IntegrIT, Ltd. This software is licensed for  */
/* use with Cadence processor cores only and must not be used for any other */
/* processors and platforms. The license to use these sources was given to  */
/* Cadence, Inc. under Terms and Condition of a Software License Agreement  */
/* between Cadence, Inc. and IntegrIT, Ltd.                                 */
/* ------------------------------------------------------------------------ */
/*          Copyright (C) 2009-2016 IntegrIT, Limited.                      */
/*                      All Rights Reserved.                                */
/* ------------------------------------------------------------------------ */


/* Portable data types. */
#include "NatureDSP_types.h"
/* NatureDSP_Baseband library API. */
#include "NatureDSP_Baseband_fft.h"
/* Common utility declarations. */
#include "common.h"
/* Twiddles tables for float point FFT */
#include "fft_fp_tw.h"
/* Internal components for the floating point FFT */
#include "fft_fp_common.h"


#if XCHAL_HAVE_BBEN_VECTORFFT && HAVE_VFPU
/*
Table of the twiddles for cifftf8, generated by matlab:

tw_cifftf8 = [exp(1j*2*pi/8*(0:3)'); exp(1j*2*pi/4*fix((0:3)'/2))]
print_twd({tw_cifftf8}, 'cifftf8_twd', 1)
%=================================================================
function print_twd(all_twd, name, fid)
for i=1:length(all_twd)
t = all_twd{i};
L = length(t);
tmp =  reshape( [real(t), imag(t)].', 2*L, 1 ) ;
s = num2hex(single(tmp));
fprintf(2, 'extern const union ufloat32uint32 ');
fprintf(2, '%s%d[%d];\n', name, i, 2*L);

fprintf(fid, '\nALIGN(32) const union ufloat32uint32 ');
fprintf(fid, '%s%d[%d] = \n{\n', name, i, 2*L);
for k=1:2*L
fprintf(fid, '  { 0x%s },', s(k, :));
if(mod(k, 4)==0)
fprintf(fid, '\n');
end
end
fprintf(fid, '};\n');
end
*/
static ALIGN(32) const union ufloat32uint32 cifftf8_twd1[16] =
{
    { 0x3f800000 }, { 0x00000000 }, { 0x3f3504f3 }, { 0x3f3504f3 },
    { 0x248d3132 }, { 0x3f800000 }, { 0xbf3504f3 }, { 0x3f3504f3 },
    { 0x3f800000 }, { 0x00000000 }, { 0x3f800000 }, { 0x00000000 },
    { 0x248d3132 }, { 0x3f800000 }, { 0x248d3132 }, { 0x3f800000 },
};


/* The in-place complex-to-real spectrum conversion N=16 */
inline_ void blkrifft_spec_conv_packed_N16_fp(complex_float *_x,   /* in/out  complex array, size is N/2+1 */
    const complex_float *twiddle_table,
    int N, int L)
{
    int l;
    int n;
    valign vx1;
    valign vy1;
    vboolN_4 m = BBE_NOTBN_4(BBE_MOVN_4_FROMN(BBE_LTRNI(4)));
    const int v_sz = (BBE_SIMD_WIDTH * 2 / sizeof(*_x)); //Vector size (number of complex elements)
    xb_vecN_4xcf32 _a0, _a1, _b0, _b1, tw;
    xb_vecN_4xcf32 *ptw = (xb_vecN_4xcf32 *)(twiddle_table + N / 4 - v_sz);
    xb_vecN_4xcf32 *px0;
    xb_vecN_4xcf32 *py0;
    xb_vecN_4xcf32 *px1;
    xb_vecN_4xcf32 *py1;

    NASSERT(N == 16);
    NASSERT((N&(N - 1)) == 0);


    n = N / (4 * v_sz) - 1; 
    {
        px0 = (xb_vecN_4xcf32 *)(_x - v_sz*(n + 1) + N / 4);
        px1 = (xb_vecN_4xcf32 *)(_x + v_sz*n + N / 4 + 1);
        py0 = (xb_vecN_4xcf32 *)(_x - v_sz*(n + 1) + N / 4);
        py1 = (xb_vecN_4xcf32 *)(_x + v_sz*n + N / 4 + 1);

        BBE_LVN_4XCF32_XP(tw, ptw, -2 * BBE_SIMD_WIDTH);
        /*  Additional scaling by 1/8 */
        _SCALE_N_4XCF32(tw, 1.0f / 8);
        /* 11 cycles per pipeline stage in steady state with unroll=2 */
        for (l = 0; l < L; l++)
        {

            vy1 = BBE_ZALIGN();
            vx1 = BBE_LAN_4XCF32_PP(px1);
           
            BBE_LVN_4XCF32_XP(_a0, px0, N / 2 * sizeof(*_x) );
            BBE_LAN_4XCF32_IP(_a1, vx1, px1);

            _a1 = BBE_SHFLN_4XCF32I(_a1, BBE_SHFLI_REVERSE_4);
            BBE_ADDSUBN_4XCF32(_b1, _b0, _a0, BBE_CONJN_4XCF32(_a1));

            _b1 = BBE_MULJN_4XCF32(_b1, tw);
            _SCALE_N_4XCF32(_b0, 1.0f / 16); //with additional scaling by 1/8

            BBE_ADDSUBN_4XCF32(_a1, _a0, _b0, _b1);
            _a1 = BBE_CONJN_4XCF32(_a1);
            _a1 = BBE_SHFLN_4XCF32I(_a1, BBE_SHFLI_REVERSE_4);

            //  Flush not needed, since no write to x[N/2] 
            BBE_SAN_4XCF32_IP(_a1, vy1, py1);
            BBE_SVN_4XCF32T_XP(_a0, py0, N / 2 * sizeof(*_x), m);

            py1 = (xb_vecN_4xcf32*)(N / 2 * sizeof(*_x) - 2 * BBE_SIMD_WIDTH + (uintptr_t)py1);
            px1 = (xb_vecN_4xcf32*)(N / 2 * sizeof(*_x) - 2 * BBE_SIMD_WIDTH + (uintptr_t)px1);
        } // for (l = 0; l < L; l++) inner loop
    }  /* First and last iteration */

    px0 = (xb_vecN_4xcf32 *)(_x);
    py0 = (xb_vecN_4xcf32 *)(_x);
    xb_vecN_4xcf32 f = BBE_CONSTN_4XCF32(0x3); 
    _SCALE_N_4XCF32(f, 1.0f / 8); //with additional scaling by 1/8

    /* 12 cycles per pipeline stage in steady state with unroll=4 */
    for (l = 0; l<L; l++)
    {
        xb_vecN_4xcf32 a0, aN_4;

        BBE_LVN_4XCF32_XP(a0, px0, N / 4 * sizeof(*_x));
        BBE_LVN_4XCF32_XP(aN_4, px0, N / 4 * sizeof(*_x));
        aN_4 = BBE_CONJN_4XCF32(aN_4);

        a0 = BBE_MULJN_4XCF32(f, a0);
        _SCALE_N_4XCF32(aN_4, 1.0f / 8);        //with additional scaling by 1/8          

        BBE_SVN_4XCF32F_XP(a0, py0, N / 4 * sizeof(*_x), m);
        BBE_SVN_4XCF32F_XP(aN_4, py0, N / 4 * sizeof(*_x), m);
    }

} //blkrifft_spec_conv_packed_N16_fp




/*
    Ordinary IL x IDFT8, without scaling by 1/8.
*/
static void blk_cifftf8_fp(  complex_float *x,
                             complex_float *y, 
                             int L)
{
    int i;
    xb_vecN_4xcf32 *px = (xb_vecN_4xcf32 *)x;
    xb_vecN_4xcf32 *py = (xb_vecN_4xcf32 *)y;
    xb_vecN_4xcf32 _a0, _a1, _t1, _b0, _b1;

    _t1 = BBE_LVN_4XCF32_I((xb_vecN_4xcf32*)cifftf8_twd1, 0);
     vboolN_2 m = BBE_NOTBN_2(BBE_MOVN_2_FROMN(BBE_LTRNI(8)));
     /* 13 cycles per pipeline stage in steady state with unroll=2 */ 
    for (i = 0; i < L; i++)
    {
        /*
        complex_float a0, a1;
        for (i = 0; i < N/2; i++)
        {
        a0.s.re = x[i].s.re + x[i + N / 2].s.re;
        a1.s.re = x[i].s.re - x[i + N / 2].s.re;
        a0.s.im = x[i].s.im + x[i + N / 2].s.im;
        a1.s.im = x[i].s.im - x[i + N / 2].s.im;
        a1 = mul_fl32c(tw1[i], a1);

        y[2*i  ] = a0;
        y[2*i+1] = a1;
        }
       
        */
        BBE_LVN_4XCF32_IP(_a0, px, sizeof(*px) );
        BBE_LVN_4XCF32_IP(_a1, px, sizeof(*px) );
        BBE_ADDSUBN_4XCF32(_a1, _a0, _a0, _a1);
        _a1 = BBE_MULN_4XCF32(_a1, _t1);

        BBE_DSELN_4XCF32I(_b1, _b0, _a1, _a0, BBE_DSELI_INTERLEAVE_4);

        BBE_ADDSUBN_4XCF32(_b1, _b0, _b0, _b1);
#if 0
        _b1 = BBE_MULN_4XCF32(_b1, _t2);
#else
        {    
            xb_vecN_2xf32    z0 = BBE_MOVN_2XF32_FROMNX16(BBE_MOVNX16_FROMN_4XCF32(_b1));
            /*  muliply by {1, 1, j, j} */          
            BBE_MULMN_2XF32T(z0, z0, BBE_CONSTN_2XF32(1), 1, 6, m);
            _b1 = BBE_MOVN_4XCF32_FROMNX16(BBE_MOVNX16_FROMN_2XF32(z0));
        }

#endif
        _a0 = BBE_SELN_4XCF32I(_b1, _b0, BBE_SELI_EXTRACT_LO_HALVES);
        _a1 = BBE_SELN_4XCF32I(_b1, _b0, BBE_SELI_EXTRACT_HI_HALVES);
        /*


        for (i = 0; i < N/4; i++)
        {
        int j;
        for (j = 0; j < 2; j++)
        {
        a0.s.re = y[(2 * i + j)].s.re + y[(2 * i + j) + N / 2].s.re;
        a1.s.re = y[(2 * i + j)].s.re - y[(2 * i + j) + N / 2].s.re;
        a0.s.im = y[(2 * i + j)].s.im + y[(2 * i + j) + N / 2].s.im;
        a1.s.im = y[(2 * i + j)].s.im - y[(2 * i + j) + N / 2].s.im;
        a1 = mul_fl32c(tw2[i*2+j], a1);

        x[4 * i + j] = a0;
        x[4 * i + j + 2] = a1;
        }

        }


        */
        BBE_ADDSUBN_4XCF32(_a1, _a0, _a0, _a1);

        /* 
           scaling by 1/8 moved into blk_spconv_packed_N16_fp 
        */

        /*
        for (i = 0; i < N / 2; i++)
        {
        a0.s.re = (x[i].s.re + x[i + N / 2].s.re);
        a1.s.re = (x[i].s.re - x[i + N / 2].s.re);
        a0.s.im = (x[i].s.im + x[i + N / 2].s.im);
        a1.s.im = (x[i].s.im - x[i + N / 2].s.im);
        y[ i]      = a0;
        y[ i + N/2] = a1;
        }
        */
        BBE_SVN_4XCF32_IP(_a0, py, sizeof(*py));
        BBE_SVN_4XCF32_IP(_a1, py, sizeof(*py));
    }//for(i=0; i<L; i++)
} /* blk_cifftf8_fp */
#endif //#if XCHAL_HAVE_BBEN_VECTORFFT && HAVE_VFPU

/*-------------------------------------------------------------------------
Blockwise inverse floating point FFT forming real data

These functions make inverse FFT forming real data on L blocks.
FFT implementation for real signal exploits the symmetry properties of the 
Fourier Transform: first, a blockwise complex FFT of half the original size
is applied to input data, and then the resulting spectrum undergoes a 
conversion procedure which results in complex spectrum of real input data.
NOTES:
1.  Bit-reversing permutation is done here.
2.  IFFT runs an in-place algorithm, so INPUT DATA WILL APPEAR DAMAGED after
    the call.
3.  Spectrum of real signal is conjugate-symmetric about the midpoint, thus 
    real inverse FFT functions require only the first half of spectrum and 
    Nyquist frequency bin (altogether N/2+1 complex points) to reconstruct 
    the time domain signal. Moreover, the DC component and Nyquist 
    frequency component have zero imaginary part, thus they can be packed 
    in a single 'complex' value in input data. So, the m-th row of the input 
    matrix shall contain the following values:
    - DC component of the signal in x[m][0].re
    - Nyquist frequency component in x[m][0].im
    - first half of the complex spectrum in x[m][1]...x[m][(N/2)-1]
These data are used to reconstruct N values that are stored into the m-th 
row of real output matrix y[m][N]. The reconstruction is accomplished 
through a special conversion of input spectrum, such that subsequent 
invocation of blockwise complex inverse FFT of size N/2 actually produces 
the desired real signal.

Representation: floating point

Parameters:
  Input:            
    x[L][N/2] half of input spectrum, see note above
  Output:          
    y[L][N]   Output real samples
  Returned value:
                None
Restrictions:
  x,y           Must not overlap and must be aligned on 32-byte boundary
-------------------------------------------------------------------------*/
#if !XCHAL_HAVE_BBEN_VECTORFFT || !HAVE_VFPU
DISCARD_FUN(void, brifft16f, (float32_t * restrict y, complex_float * restrict x, int L) )
#else
void brifft16f(float32_t * restrict y, complex_float * restrict x, int L)
{

    complex_float *twiddle_table = (complex_float*)rfftf16_twd1;

    NASSERT_ALIGN(x, 2 * BBE_SIMD_WIDTH);
    NASSERT_ALIGN(y, 2 * BBE_SIMD_WIDTH);
    NASSERT((uintptr_t)x != (uintptr_t)y);
    NASSERT(L>0);
     
    blkrifft_spec_conv_packed_N16_fp(x, twiddle_table, 16, L); 
    blk_cifftf8_fp(x, (complex_float*)y, L);
}/*brifft16f*/
#endif //#if !XCHAL_HAVE_BBEN_VECTORFFT || ! HAVE_VFPU





