/* ------------------------------------------------------------------------ */
/* Copyright (c) 2016 by Cadence Design Systems, Inc. ALL RIGHTS RESERVED.  */
/* These coded instructions, statements, and computer programs ('Cadence    */
/* Libraries') are the copyrighted works of Cadence Design Systems Inc.     */
/* Cadence IP is licensed for use with Cadence processor cores only and     */
/* must not be used for any other processors and platforms. Your use of the */
/* Cadence Libraries is subject to the terms of the license agreement you   */
/* have entered into with Cadence Design Systems, or a sublicense granted   */
/* to you by a direct Cadence licensee.                                     */
/* ------------------------------------------------------------------------ */
/*  IntegrIT, Ltd.   www.integrIT.com, info@integrIT.com                    */
/*                                                                          */
/* NatureDSP_Baseband Library                                               */
/*                                                                          */
/* This library contains copyrighted materials, trade secrets and other     */
/* proprietary information of IntegrIT, Ltd. This software is licensed for  */
/* use with Cadence processor cores only and must not be used for any other */
/* processors and platforms. The license to use these sources was given to  */
/* Cadence, Inc. under Terms and Condition of a Software License Agreement  */
/* between Cadence, Inc. and IntegrIT, Ltd.                                 */
/* ------------------------------------------------------------------------ */
/*          Copyright (C) 2009-2016 IntegrIT, Limited.                      */
/*                      All Rights Reserved.                                */
/* ------------------------------------------------------------------------ */
/*
NatureDSP_Baseband library. FFT
Radix-2 forward FFT on complex_float data
C code optimized for BBE32
IntegrIT, 2006-2016
*/

/* Cross-platform data type definitions. */
#include "NatureDSP_types.h"
/* Common helper macros. */
#include "common.h"
/* NatureDSP_Baseband library API. */
#include "NatureDSP_Baseband_fft.h"
/* Tables of a twiddles */
#include "fft_fp_tw.h"
/* Internal components for the floating point FFT */
#include "fft_fp_common.h"
#if XCHAL_HAVE_BBEN_VECTORFFT && HAVE_VFPU
/* Inverse DFT8 */
inline_ void cifft8f(complex_float *x,
    complex_float *y)
{
    /*
    Table of the twiddles for cifft8f, generated by matlab:

    tw_cifft8f = [exp(1j*2*pi/8*(0:3)'); exp(1j*2*pi/4*fix((0:3)'/2))]
    print_twd({tw_cifft8f}, 'cifft8f_twd', 1)
    %=================================================================
    function print_twd(all_twd, name, fid)
    for i=1:length(all_twd)
    t = all_twd{i};
    L = length(t);
    tmp =  reshape( [real(t), imag(t)].', 2*L, 1 ) ;
    s = num2hex(single(tmp));
    fprintf(2, 'extern const union ufloat32uint32 ');
    fprintf(2, '%s%d[%d];\n', name, i, 2*L);

    fprintf(fid, '\nALIGN(32) const union ufloat32uint32 ');
    fprintf(fid, '%s%d[%d] = \n{\n', name, i, 2*L);
    for k=1:2*L
    fprintf(fid, '  { 0x%s },', s(k, :));
    if(mod(k, 4)==0)
    fprintf(fid, '\n');
    end
    end
    fprintf(fid, '};\n');
    end
    */
    static ALIGN(32) const union ufloat32uint32 cifft8f_twd1[16] =
    {
        { 0x3f800000 }, { 0x00000000 }, { 0x3f3504f3 }, { 0x3f3504f3 },
        { 0x248d3132 }, { 0x3f800000 }, { 0xbf3504f3 }, { 0x3f3504f3 },
        { 0x3f800000 }, { 0x00000000 }, { 0x3f800000 }, { 0x00000000 },
        { 0x248d3132 }, { 0x3f800000 }, { 0x248d3132 }, { 0x3f800000 },
    };

    const xb_vecN_4xcf32 *ptmp = (const xb_vecN_4xcf32 *)cifft8f_twd1;
    const xb_vecN_4xcf32 twd1 = ptmp[0],
        twd2 = ptmp[1];
    xb_vecN_4xcf32 _a0, _a1, _b0, _b1;

    /*
    complex_float a0, a1;
    for (i = 0; i < N/2; i++)
    {
    a0.s.re = x[i].s.re + x[i + N / 2].s.re;
    a1.s.re = x[i].s.re - x[i + N / 2].s.re;
    a0.s.im = x[i].s.im + x[i + N / 2].s.im;
    a1.s.im = x[i].s.im - x[i + N / 2].s.im;
    a1 = mul_fl32c(tw1[i], a1);

    y[2*i  ] = a0;
    y[2*i+1] = a1;
    }
    */
    _a0 = BBE_LVN_4XCF32_I((xb_vecN_4xcf32*)x, 0);
    _a1 = BBE_LVN_4XCF32_I((xb_vecN_4xcf32*)x, 8 / 2 * sizeof(*x));
    BBE_ADDSUBN_4XCF32(_a1, _a0, _a0, _a1);
    _a1 = BBE_MULN_4XCF32(_a1, twd1);

    BBE_DSELN_4XCF32I(_b1, _b0, _a1, _a0, BBE_DSELI_INTERLEAVE_4);

    BBE_ADDSUBN_4XCF32(_b1, _b0, _b0, _b1);
    _b1 = BBE_MULN_4XCF32(_b1, twd2);

    _a0 = BBE_SELN_4XCF32I(_b1, _b0, BBE_SELI_EXTRACT_LO_HALVES);
    _a1 = BBE_SELN_4XCF32I(_b1, _b0, BBE_SELI_EXTRACT_HI_HALVES);
    /*
    for (i = 0; i < N/4; i++)
    {
    int j;
    for (j = 0; j < 2; j++)
    {
    a0.s.re = y[(2 * i + j)].s.re + y[(2 * i + j) + N / 2].s.re;
    a1.s.re = y[(2 * i + j)].s.re - y[(2 * i + j) + N / 2].s.re;
    a0.s.im = y[(2 * i + j)].s.im + y[(2 * i + j) + N / 2].s.im;
    a1.s.im = y[(2 * i + j)].s.im - y[(2 * i + j) + N / 2].s.im;
    a1 = mul_fl32c(tw2[i*2+j], a1);

    x[4 * i + j] = a0;
    x[4 * i + j + 2] = a1;
    }

    }

    */
    BBE_ADDSUBN_4XCF32(_a1, _a0, _a0, _a1);
    _SCALE_N_4XCF32(_a0, 1.0f / 8);
    _SCALE_N_4XCF32(_a1, 1.0f / 8);
    /*
    for (i = 0; i < N / 2; i++)
    {
    a0.s.re = 1.0f / 8 * (x[i].s.re + x[i + N / 2].s.re);
    a1.s.re = 1.0f / 8 * (x[i].s.re - x[i + N / 2].s.re);
    a0.s.im = 1.0f / 8 * (x[i].s.im + x[i + N / 2].s.im);
    a1.s.im = 1.0f / 8 * (x[i].s.im - x[i + N / 2].s.im);
    y[ i]      = a0;
    y[ i + N/2] = a1;
    }
    */
    BBE_SVN_4XCF32_I(_a0, (xb_vecN_4xcf32*)y, 0);
    BBE_SVN_4XCF32_I(_a1, (xb_vecN_4xcf32*)y, 2 * BBE_SIMD_WIDTH);
}
#endif //#if XCHAL_HAVE_BBEN_VECTORFFT &&  HAVE_VFPU
/*-------------------------------------------------------------------------
Radix-2 inverse floating point FFT forming real data

Description: These functions make inverse FFT forming real data of length
N=2^n, n=4..15. Algorithm exploits the symmetry properties of the FFT:
the input spectrum is modified in such a way that a complex-valued inverse FFT
of half the original size that is applied to the transformed spectrum actually
results in real data.

Representation: floating point

NOTES:
  1. Bit-reversing permutation is done here. 
  2. FFT runs an in-place algorithm, so INPUT DATA WILL APPEAR DAMAGED after 
     the call.

Parameters:
  Input:
    x[(N/2+1)]    Input spectrum samples
  Output:
    y[N]          Real output signal
  Returned value:
                  zero
Restrictions:
  x,y             Must not overlap and must be aligned on 32-byte boundary
-------------------------------------------------------------------------*/
#if !XCHAL_HAVE_BBEN_VECTORFFT || !HAVE_VFPU
DISCARD_FUN(int, rifft16f, (float32_t * restrict y, complex_float * restrict x) )
#else
int rifft16f(float32_t * restrict y, complex_float * restrict x)
{
    const complex_float *twiddle_table = (const complex_float*)rfftf16_twd1;
    NASSERT_ALIGN(x, 2 * BBE_SIMD_WIDTH);
    NASSERT_ALIGN(y, 2 * BBE_SIMD_WIDTH);
    NASSERT(x != (complex_float*)y);

    rifft_spec_conv_fp(x, twiddle_table, 16);
    cifft8f(x, (complex_float*)y);

    return 0;
}
#endif //#if !XCHAL_HAVE_BBEN_VECTORFFT || ! HAVE_VFPU
