/* ------------------------------------------------------------------------ */
/* Copyright (c) 2016 by Cadence Design Systems, Inc. ALL RIGHTS RESERVED.  */
/* These coded instructions, statements, and computer programs ('Cadence    */
/* Libraries') are the copyrighted works of Cadence Design Systems Inc.     */
/* Cadence IP is licensed for use with Cadence processor cores only and     */
/* must not be used for any other processors and platforms. Your use of the */
/* Cadence Libraries is subject to the terms of the license agreement you   */
/* have entered into with Cadence Design Systems, or a sublicense granted   */
/* to you by a direct Cadence licensee.                                     */
/* ------------------------------------------------------------------------ */
/*  IntegrIT, Ltd.   www.integrIT.com, info@integrIT.com                    */
/*                                                                          */
/* NatureDSP_Baseband Library                                               */
/*                                                                          */
/* This library contains copyrighted materials, trade secrets and other     */
/* proprietary information of IntegrIT, Ltd. This software is licensed for  */
/* use with Cadence processor cores only and must not be used for any other */
/* processors and platforms. The license to use these sources was given to  */
/* Cadence, Inc. under Terms and Condition of a Software License Agreement  */
/* between Cadence, Inc. and IntegrIT, Ltd.                                 */
/* ------------------------------------------------------------------------ */
/*          Copyright (C) 2009-2017 IntegrIT, Limited.                      */
/*                      All Rights Reserved.                                */
/* ------------------------------------------------------------------------ */

/*
    NatureDSP_Baseband library. IIR part
    Biquad real block IIR, floating point
    C code optimized for BBE32
    Integrit, 2006-2016
*/

/*-------------------------------------------------------------------------
  Biquad Real Block IIR

  Passes real input data through a series of cascaded biquad sections. Filter 
  implementation is based on Direct Form II aka the Canonical Form. Please 
  refer to the NatureDSP Baseband Library Reference for details on the filter 
  structure.

  For each section the user has to provide 2 feedback tap coefficients 
  a1, a2, and 3 feedforward tap coefficients b0, b1, b2. Fixed-point filter
  variant also requires the input gain term g to be specified for each biquad
  section. For the final scaling of filter output data, the total gain 
  coefficient (gain) is applied to output samples produced by the last biquad
  section.

  Representation:
  bqriir         16-bit signed fixed-point format for input/output samples 
                 and tap coefficients
  bqriirf        IEEE-754 Std. single precision floating-point format for
                 input/output data and tap coefficients

  Implementation of biquad series for fixed-point data format has two flavors:
  Low_Noise  Performs 32x16-bit multiplications and utilizes the scratch
             memory to keep intermediate results in order to lower the
             quantization noise and reduce round-off errors
  Fast       Makes use of native 16x16-bit multipliers and thus appears faster
             than the Low Noise variant at the cost of deteriorated accuracy

  Notes:
  1. Biquad coefficients may be derived from standard SOS and G matrices 
     generated by MATLAB. However, scale factors may require some tuning 
     to find a compromise between quantization noise and possible overflows.
  2. For performance reasons, implementation may introduce additional
     algorithmic delay (group delay) to the output data.

  Methods:
    bqriir[f]_alloc()   - calculate memory block size for a filter instance
    bqriir[f]_init()    - initialize the filter instance
    bqriir[f]_process() - pass a block of input samples to the filter and return
                          filter output samples
  Restrictions:
    - scratch memory block, whenever supplied, must be 32 bytes aligned
    - number of biquads M must be less or equal to 32
---------------------------------------------------------------------------*/

#include <string.h>
/* Portable data types. */
#include "NatureDSP_types.h"
/* Signal Processing Library API. */
#include "NatureDSP_Baseband_iir.h"
/* Common utility and macros declarations. */
#include "common.h"

#if !(HAVE_VFPU)
DISCARD_FUN(void, bqriirf_process,( bqriirf_handle_t     _bqriir,
                                    float32_t * restrict r,
                              const float32_t *          x,
                                    int                  N ))

/*---------------------------------------------------------------------------
   Calculate the memory block size for a filter with given attributes.
   Input:
     M     Number of biquad sections
     opt   Fixed-point implementation variant selector, BQRIIR_OPT_LOW_NOISE or
           BQRIIR_OPT_FAST
   Output:
     Returns required memory block size, in bytes, or zero if failed
   Restrictions:
     M<=32
---------------------------------------------------------------------------*/
size_t bqriirf_alloc( int M )
{
    return (0);
}
/*---------------------------------------------------------------------------
   Initialize the filter instance. Delay elements are zeroed.
   Input:
     objmem     Memory block of bqriir_alloc(M,opt) or bqriirf_alloc(M) bytes
     M          Number of biquad sections
     opt        Fixed-point implementation variant selector, BQRIIR_OPT_LOW_NOISE
                or BQRIIR_OPT_FAST
     coef[C*M]  Per-section coefficient blocks. Each coefficient block contains
                5 tap coefficients a1,a2,b0,b1,b2 and (only for the fixed-point
                variant) the input gain term g. Coefficients must be ordered
                as shown below:
                  bqriir_init()  C=6: g, b0, b1, b2, a1, a2 (Q14)
                  bqriirf_init() C=5: b0, b1, b2, a1, a2
     gain       Total gain coefficient to be applied to the output of the 
                last biquad (for fixed point API only). Fixed-point data format 
                for bqriir_init() is Q8
   Output:
     Returns the filter handle, or zero if failed.
   Restrictions:
     M<=32
---------------------------------------------------------------------------*/
bqriirf_handle_t bqriirf_init( void      * objmem,
                               int         M,
                         const float32_t * restrict coef,
                               float32_t   gain )
{
    return NULL;
}
#else

/* Instance pointer validation number. */
#define MAGIC     0xBDF23906

/* Reserve memory for alignment. */
#define ALIGNED_SIZE( size, align ) \
        ( (size_t)(size) + (align) - 1 )

/* Align address on a specified boundary. */
#define ALIGNED_ADDR( addr, align ) \
        ( ( (uintptr_t)(addr) + ( (align) - 1 ) ) & ~( (align) - 1 ) )

/* Filter instance structure. */
typedef struct tag_bqriirf_t
{
  uint32_t    magic;   // Instance pointer validation number
  int         M;       // Biquads number
  float32_t   gain;    // Total gain
  float32_t * coef;    // Biquad coefficients
  float32_t * sect;    // Biquad sections state
} bqriirf_t, *bqriirf_ptr_t;

/*---------------------------------------------------------------------------
   Calculate the memory block size for a filter with given attributes.
   Input:
     M     Number of biquad sections
     opt   Fixed-point implementation variant selector, BQRIIR_OPT_LOW_NOISE or
           BQRIIR_OPT_FAST
   Output:
     Returns required memory block size, in bytes, or zero if failed
   Restrictions:
     M<=32
---------------------------------------------------------------------------*/
size_t bqriirf_alloc( int M )
{
  if ( M<=0 )
  {
    return (0);
  }

  // Round up M to the multiple of BBE_SIMD_WIDTH/2
  M=(M+BBE_SIMD_WIDTH/2-1) & ~(BBE_SIMD_WIDTH/2-1);

  return ( ALIGNED_SIZE( sizeof( bqriirf_t ), sizeof(int) )
           + // Biquad coefficients
           ALIGNED_SIZE( 5*M*sizeof(float32_t), BBE_SIMD_WIDTH/2*sizeof(float32_t) )
           + // Sections state
           ALIGNED_SIZE( 4*M*sizeof(float32_t), BBE_SIMD_WIDTH/2*sizeof(float32_t) )
               );
}/* bqriirf_alloc() */

/*---------------------------------------------------------------------------
   Initialize the filter instance. Delay elements are zeroed.
   Input:
     objmem     Memory block of bqriir_alloc(M,opt) or bqriirf_alloc(M) bytes
     M          Number of biquad sections
     opt        Fixed-point implementation variant selector, BQRIIR_OPT_LOW_NOISE
                or BQRIIR_OPT_FAST
     coef[C*M]  Per-section coefficient blocks. Each coefficient block contains
                5 tap coefficients a1,a2,b0,b1,b2 and (only for the fixed-point
                variant) the input gain term g. Coefficients must be ordered
                as shown below:
                  bqriir_init()  C=6: g, b0, b1, b2, a1, a2 (Q14)
                  bqriirf_init() C=5: b0, b1, b2, a1, a2
     gain       Total gain coefficient to be applied to the output of the 
                last biquad. Fixed-point data format for bqriir_init() is Q8
   Output:
     Returns the filter handle, or zero if failed.
   Restrictions:
     M<=32
---------------------------------------------------------------------------*/
bqriirf_handle_t bqriirf_init( void      * objmem,
                               int         M,
                         const float32_t * coef,
                               float32_t   gain )
{
    
#define SIMD (BBE_SIMD_WIDTH/2)
  bqriirf_ptr_t bqriir;
  void        * ptr;
  float32_t   * cf;
  float32_t   * sect;
  int           m, k, M_;

  //
  // Validate the arguments.
  //
  
  ASSERT(objmem && coef);
  if ( M<=0 )
  {
    return NULL;
  }

  M_ = M;
  // Round up M to the multiple of BBE_SIMD_WIDTH/2
  M = (M+BBE_SIMD_WIDTH/2-1) & ~(BBE_SIMD_WIDTH/2-1);

  //
  // Partition the memory block.
  //

  ptr     = objmem;
  bqriir  = (bqriirf_ptr_t)ALIGNED_ADDR( ptr, sizeof(int) );
  ptr     = bqriir + 1;
  cf      = (float32_t*)ALIGNED_ADDR( ptr, BBE_SIMD_WIDTH/2*sizeof(float32_t) );
  ptr     = cf + 5*M;
  sect    = (float32_t*)ALIGNED_ADDR( ptr, BBE_SIMD_WIDTH/2*sizeof(float32_t) );
  ptr     = sect + 4*M;

  ASSERT( (int8_t*)ptr - (int8_t*)objmem <= (int)bqriirf_alloc( M ) );

  //
  // Copy the filter coefficients, zero the sections state.
  // Pad with virtual sections.
  //

  // Deinterleave coefficients to the block-stremaing order by SIMD streams.
  for (m = 0; m < M-SIMD; m+=SIMD)
  {
      for (k = 0; k < SIMD; k++)
      {
          cf[m*5+1*SIMD-1-k] = coef[m*5+k*5+0];/* b0 */
          cf[m*5+2*SIMD-1-k] = coef[m*5+k*5+1];/* b1 */
          cf[m*5+3*SIMD-1-k] = coef[m*5+k*5+2];/* b2 */
          cf[m*5+4*SIMD-1-k] = coef[m*5+k*5+3];/* a1 */
          cf[m*5+5*SIMD-1-k] = coef[m*5+k*5+4];/* a2 */
      }
  }
  {
      m = M - SIMD;
      for (k = 0; k < SIMD-(M-M_); k++)
      {
          cf[m*5+1*SIMD-1-k] = coef[m*5+k*5+0];/* b0 */
          cf[m*5+2*SIMD-1-k] = coef[m*5+k*5+1];/* b1 */
          cf[m*5+3*SIMD-1-k] = coef[m*5+k*5+2];/* b2 */
          cf[m*5+4*SIMD-1-k] = coef[m*5+k*5+3];/* a1 */
          cf[m*5+5*SIMD-1-k] = coef[m*5+k*5+4];/* a2 */
      }
      // Pad remaining M%SIMD sections with dummy coefficients.
      for (k = SIMD-(M-M_); k < SIMD; k++)
      {
          cf[m*5+1*SIMD-1-k] = 1.0f;
          cf[m*5+2*SIMD-1-k] = 0.0f;
          cf[m*5+3*SIMD-1-k] = 0.0f;
          cf[m*5+4*SIMD-1-k] = 0.0f;
          cf[m*5+5*SIMD-1-k] = 0.0f;
      }
  }

  memset( sect, 0, 4*M*sizeof(float32_t) );

  //
  // Initialize the filter instance.
  //

  memset( bqriir, 0, sizeof( bqriirf_t ) );

  bqriir->magic   = MAGIC;
  bqriir->M       = M;
  bqriir->gain    = gain;
  bqriir->coef    = cf;
  bqriir->sect    = sect;

  return (bqriir);
#undef SIMD

}/* bqriirf_init() */

/*---------------------------------------------------------------------------
   Pass a block of input samples to the filter and return filter output
   samples
   Input:
     _bqriir,
     _bqriirf     Filter handle
     N            Input/output signal chunk size, in samples
     x[N]         Input samples
   Output:
     r[N]         Output samples
   Temporary:
     scr[4*N+32]  Scratch memory block, size in bytes; required by the Low 
                  Noise fixed-pointimplementation variant (BQRIIR_OPT_LOW_NOISE), 
                  otherwise may be null
   Restrictions:
     scr          Aligned on 32-byte boundary, whenever supplied
---------------------------------------------------------------------------*/
void bqriirf_process( bqriirf_handle_t     _bqriir,
                      float32_t * restrict r,
                const float32_t *          x,
                      int                  N )
{
#define SIMD (BBE_SIMD_WIDTH/2)
  bqriirf_ptr_t bqriir = (bqriirf_ptr_t)_bqriir;
  const xb_vecN_2xf32 * restrict coef;
        xb_vecN_2xf32 * restrict sect;
  const float32_t * restrict pin;
        float32_t * restrict pout;
  xb_vecN_2xf32 gain, xin, rout;
  xb_vecN_2xf32 b0,b1,b2,a1,a2;
  xb_vecN_2xf32 d2,d1,d0,dx,dy;
  xb_vecN_2xf32 acc_fb,acc_ff;
  int M;
  int n, m;

  //
  // Validate the arguments.
  //

  NASSERT( bqriir && bqriir->magic == MAGIC );
  NASSERT( r && x );
  if (N<=0) return;

  coef = (const xb_vecN_2xf32*)bqriir->coef;
  sect = (      xb_vecN_2xf32*)bqriir->sect;
  M = bqriir->M;
  gain = bqriir->gain;
  
  pin = x;
  pout = r;

  //
  // Process SIMD sections simultaneously.
  //

  for ( m=0; m<M-SIMD; m+=SIMD )
  {
    // load sections' coefficients
    BBE_LVN_2XF32_IP(b0, coef, SIMD*sizeof(float32_t));
    BBE_LVN_2XF32_IP(b1, coef, SIMD*sizeof(float32_t));
    BBE_LVN_2XF32_IP(b2, coef, SIMD*sizeof(float32_t));
    BBE_LVN_2XF32_IP(a1, coef, SIMD*sizeof(float32_t));
    BBE_LVN_2XF32_IP(a2, coef, SIMD*sizeof(float32_t));
    // load delay elements
    dx = BBE_LVN_2XF32_I(sect, 0*SIMD*sizeof(float32_t));
    dy = BBE_LVN_2XF32_I(sect, 1*SIMD*sizeof(float32_t));
    d2 = BBE_LVN_2XF32_I(sect, 2*SIMD*sizeof(float32_t));
    d1 = BBE_LVN_2XF32_I(sect, 3*SIMD*sizeof(float32_t));
    
    //
    // Pass the block of input samples through the section. n-th sample at the
    // output of a biquad section r[n] and section state elements (d1,d2) update
    // are given by the following formulae:
    //   d0 = x[n] - a1*d1 - a2*d2
    //   r[n] = b0*d0 + b1*d1 + b2*d2;
    //   d2 = d1; d1 = d0;
    //

    __Pragma("loop_count min=1");
    for ( n=0; n<N; n++ )
    {
      BBE_LSN_2XF32_IP(xin, pin, sizeof(float32_t));
      // Put the input sample to the intersection delay line.
      dx = BBE_SELN_2XF32I(xin, dx, BBE_SELI_ROTATE_RIGHT_2);
      // compute feedback part of the filter
      acc_fb = dx;
      BBE_MULSN_2XF32(acc_fb, a2, d2);
      BBE_MULSN_2XF32(acc_fb, a1, d1);
      d0 = acc_fb;
      // compute feedforward part of the filter
      acc_ff = BBE_MULN_2XF32(b2, d2);
      BBE_MULAN_2XF32(acc_ff, b1, d1);
      BBE_MULAN_2XF32(acc_ff, b0, d0);
      // Shift delay lines
      d2 = d1;
      d1 = d0;
      dx = dy;
      dy = acc_ff;
      // Store computed sample
      rout = acc_ff;
      BBE_SSN_2XF32_IP(rout, pout, sizeof(float32_t));
    }
    // Store updated delay lines
    BBE_SVN_2XF32_IP(dx, sect, SIMD*sizeof(float32_t));
    BBE_SVN_2XF32_IP(dy, sect, SIMD*sizeof(float32_t));
    BBE_SVN_2XF32_IP(d2, sect, SIMD*sizeof(float32_t));
    BBE_SVN_2XF32_IP(d1, sect, SIMD*sizeof(float32_t));

    pin = r;// Use output of the last stage further
    pout = r;
  }
  
  // Process last SIMD sections and apply total gain to the output
  {
    b0 = BBE_LVN_2XF32_I(coef, 0*SIMD*sizeof(float32_t));
    b1 = BBE_LVN_2XF32_I(coef, 1*SIMD*sizeof(float32_t));
    b2 = BBE_LVN_2XF32_I(coef, 2*SIMD*sizeof(float32_t));
    a1 = BBE_LVN_2XF32_I(coef, 3*SIMD*sizeof(float32_t));
    a2 = BBE_LVN_2XF32_I(coef, 4*SIMD*sizeof(float32_t));
    
    dx = BBE_LVN_2XF32_I(sect, 0*SIMD*sizeof(float32_t));
    dy = BBE_LVN_2XF32_I(sect, 1*SIMD*sizeof(float32_t));
    d2 = BBE_LVN_2XF32_I(sect, 2*SIMD*sizeof(float32_t));
    d1 = BBE_LVN_2XF32_I(sect, 3*SIMD*sizeof(float32_t));
    
    __Pragma("loop_count min=1");
    for ( n=0; n<N; n++ )
    {
      BBE_LSN_2XF32_IP(xin, pin, sizeof(float32_t));
      dx = BBE_SELN_2XF32I(xin, dx, BBE_SELI_ROTATE_RIGHT_2);

      acc_fb = dx;
      BBE_MULSN_2XF32(acc_fb, a2, d2);
      BBE_MULSN_2XF32(acc_fb, a1, d1);
      d0 = acc_fb;

      acc_ff = BBE_MULN_2XF32(b2, d2);
      BBE_MULAN_2XF32(acc_ff, b1, d1);
      BBE_MULAN_2XF32(acc_ff, b0, d0);

      d2 = d1;
      d1 = d0;
      dx = dy;
      dy = acc_ff;

      rout = BBE_MULN_2XF32(acc_ff, gain);
      BBE_SSN_2XF32_IP(rout, pout, sizeof(float32_t));
    }
    
    BBE_SVN_2XF32_I(dx, sect, 0*SIMD*sizeof(float32_t));
    BBE_SVN_2XF32_I(dy, sect, 1*SIMD*sizeof(float32_t));
    BBE_SVN_2XF32_I(d2, sect, 2*SIMD*sizeof(float32_t));
    BBE_SVN_2XF32_I(d1, sect, 3*SIMD*sizeof(float32_t));
  }
  
#undef SIMD
}/* bqriirf_process() */

#endif /* if !(HAVE_VFPU) */
