/* ------------------------------------------------------------------------ */
/* Copyright (c) 2016 by Cadence Design Systems, Inc. ALL RIGHTS RESERVED.  */
/* These coded instructions, statements, and computer programs ('Cadence    */
/* Libraries') are the copyrighted works of Cadence Design Systems Inc.     */
/* Cadence IP is licensed for use with Cadence processor cores only and     */
/* must not be used for any other processors and platforms. Your use of the */
/* Cadence Libraries is subject to the terms of the license agreement you   */
/* have entered into with Cadence Design Systems, or a sublicense granted   */
/* to you by a direct Cadence licensee.                                     */
/* ------------------------------------------------------------------------ */
/*  IntegrIT, Ltd.   www.integrIT.com, info@integrIT.com                    */
/*                                                                          */
/* NatureDSP_Baseband Library                                               */
/*                                                                          */
/* This library contains copyrighted materials, trade secrets and other     */
/* proprietary information of IntegrIT, Ltd. This software is licensed for  */
/* use with Cadence processor cores only and must not be used for any other */
/* processors and platforms. The license to use these sources was given to  */
/* Cadence, Inc. under Terms and Condition of a Software License Agreement  */
/* between Cadence, Inc. and IntegrIT, Ltd.                                 */
/* ------------------------------------------------------------------------ */
/*          Copyright (C) 2009-2017 IntegrIT, Limited.                      */
/*                      All Rights Reserved.                                */
/* ------------------------------------------------------------------------ */

/*
    NatureDSP_Baseband library. IIR part
    Biquad real block IIR, floating point, streaming version
    C code optimized for BBE32
    Integrit, 2006-2016
*/

/*-------------------------------------------------------------------------
  Streaming Biquad Real Block IIR 

  Passes a few streams of real data through a series of cascaded biquad 
  sections. Filter implementation is based on Direct Form II aka the
  Canonical Form. Please refer to the NatureDSP Baseband Library Reference
  for details on the filter structure.

  For each section the user has to provide 2 feedback tap coefficients 
  a1, a2, and 3 feedforward tap coefficients b0, b1, b2. Fixed-point filter
  variant also requires the input gain term g to be specified for each biquad
  section. For the final scaling of filter output data, the total gain 
  coefficient (gain) is applied to output samples produced by the last biquad
  section.

  Representation:
  bqriirs    16-bit signed fixed-point format for input/output samples
             and tap coefficients
  bqriirsf   IEEE-754 Std. single precision floating-point format for
             input/output data and tap coefficients

  Implementation of biquad series for fixed-point data format has two flavors:
  Low_Noise  Performs 32x16-bit multiplications and utilizes the scratch
             memory to keep intermediate results in order to lower the
             quantization noise and reduce round-off errors
  Fast       Makes use of native 16x16-bit multipliers and thus appears faster
             than the Low Noise variant at the cost of deteriorated accuracy

  Notes:
  1. Biquad coefficients may be derived from standard SOS and G matrices 
     generated by MATLAB. However, scale factors may require some tuning 
     to find a compromise between quantization noise and possible overflows.
  2. Streaming biquad real block IIR filter may by applied to complex
     data stored in streaming format, which is equivalent to passing a
     complex signal through a complex IIR with real coefficients. The number
     of real data streams L as it is seen by the filter implementation must
     be two times the number of actual complex streams.

  Methods:
      bqriirs[f]_alloc()   - calculate memory block size for a filter instance
      bqriirs[f]_init()    - initialize the filter instance
      bqriirs[f]_process() - pass a block of input samples to the filter and
                             return filter output samples. This operation is
                             simultaneously accomplished for a few independent
                             data streams.
  Restrictions:
      - input/output data arrays must be aligned on 32-byte boundary
      - scratch memory block, whenever supplied, must be 32 bytes aligned
      - number of streams must be a multiple of 16 (bqriirs) or 8 (bqriirsf)
---------------------------------------------------------------------------*/

#include <string.h>
/* Portable data types. */
#include "NatureDSP_types.h"
/* Signal Processing Library API. */
#include "NatureDSP_Baseband_iir.h"
/* Common utility and macros declarations. */
#include "common.h"

#if !(HAVE_VFPU)
DISCARD_FUN(void, bqriirsf_process,( bqriirsf_handle_t    _bqriirs,
                                     float32_t * restrict r,
                               const float32_t *          x,
                                     int                  N ))
/*---------------------------------------------------------------------------
   Calculate the memory block size for a filter with given attributes.
   Input:
     L     Number of streams
     M     Number of biquad sections
     opt   Fixed-point implementation variant selector, BQRIIRS_OPT_LOW_NOISE
           or BQRIIRS_OPT_FAST
   Output:
     Returns required memory block size, in bytes, or zero if failed
   Restrictions:
     L     Must be a multiple of 16 (bqriirs) or 8 (bqriirsf)
---------------------------------------------------------------------------*/
size_t bqriirsf_alloc( int L, int M )
{
    return (0);
}
/*--------------------------------------------------------------------------- 
   Initialize the filter instance. Delay elements are zeroed.
   Input:
     objmem     Memory block of bqriirs_alloc(L,M,opt) or bqriirsf_alloc(L,M) bytes
     M          Number of biquad sections
     L          Number of streams
     opt        Fixed-point implementation variant selector, BQRIIRS_OPT_LOW_NOISE
                or BQRIIRS_OPT_FAST
     coef[C*M]  Per-section coefficient blocks. Each coefficient block contains
                5 tap coefficients a1,a2,b0,b1,b2 and (only for the fixed-point
                variant) the input gain term g. Coefficients must be ordered
                as shown below:
                  bqriirs_init()  C=6: g, b0, b1, b2, a1, a2 (Q14)
                  bqriirsf_init() C=5: b0, b1, b2, a1, a2
     gain       Total gain coefficient to be applied to the output of the 
                last biquad. Fixed-point data format for bqriirs_init() is Q8
   Output:
     Returns the filter handle, or zero if failed.
   Restrictions:
     L          Must be a multiple of 16 (bqriirs) or 8 (bqriirsf)
---------------------------------------------------------------------------*/
bqriirsf_handle_t bqriirsf_init( void      * objmem,
                                 int         L,
                                 int         M,
                           const float32_t * coef,
                                 float32_t   gain )
{
    return NULL;
}
#else

/* Instance pointer validation number. */
#define MAGIC     0xBDF23904

/* Reserve memory for alignment. */
#define ALIGNED_SIZE( size, align ) \
        ( (size_t)(size) + (align) - 1 )

/* Align address on a specified boundary. */
#define ALIGNED_ADDR( addr, align ) \
        ( ( (uintptr_t)(addr) + ( (align) - 1 ) ) & ~( (align) - 1 ) )

/* Filter instance structure. */
typedef struct tag_bqriirsf_t
{
  uint32_t    magic;   // Instance pointer validation number
  int         M;       // Biquads number
  int         L;       // Number of streams
  float32_t   gain;    // Total gain
  float32_t * coef;    // Biquad coefficients
  float32_t * sect;    // Biquad sections state
} bqriirsf_t, *bqriirsf_ptr_t;

/*---------------------------------------------------------------------------
   Calculate the memory block size for a filter with given attributes.
   Input:
     L     Number of streams
     M     Number of biquad sections
     opt   Fixed-point implementation variant selector, BQRIIRS_OPT_LOW_NOISE
           or BQRIIRS_OPT_FAST
   Output:
     Returns required memory block size, in bytes, or zero if failed
   Restrictions:
     L     Must be a multiple of 16 (bqriirs) or 8 (bqriirsf)
---------------------------------------------------------------------------*/
size_t bqriirsf_alloc( int L, int M )
{
  ASSERT((L%(BBE_SIMD_WIDTH/2))==0);

  if ( M<=0 )
  {
    return (0);
  }

  return ( ALIGNED_SIZE( sizeof( bqriirsf_t ), sizeof(int) )
           + // Biquad coefficients
           ALIGNED_SIZE( 5*M*sizeof(float32_t), BBE_SIMD_WIDTH/2*sizeof(float32_t) )
           + // Sections state
           ALIGNED_SIZE( 2*M*L*sizeof(float32_t), BBE_SIMD_WIDTH/2*sizeof(float32_t) )
         );
}/* bqriirsf_alloc() */

/*--------------------------------------------------------------------------- 
   Initialize the filter instance. Delay elements are zeroed.
   Input:
     objmem     Memory block of bqriirs_alloc(L,M,opt) or bqriirsf_alloc(L,M) bytes
     M          Number of biquad sections
     L          Number of streams
     opt        Fixed-point implementation variant selector, BQRIIRS_OPT_LOW_NOISE
                or BQRIIRS_OPT_FAST
     coef[C*M]  Per-section coefficient blocks. Each coefficient block contains
                5 tap coefficients a1,a2,b0,b1,b2 and (only for the fixed-point
                variant) the input gain term g. Coefficients must be ordered
                as shown below:
                  bqriirs_init()  C=6: g, b0, b1, b2, a1, a2 (Q14)
                  bqriirsf_init() C=5: b0, b1, b2, a1, a2
     gain       Total gain coefficient to be applied to the output of the 
                last biquad. Fixed-point data format for bqriirs_init() is Q8
   Output:
     Returns the filter handle, or zero if failed.
   Restrictions:
     L          Must be a multiple of 16 (bqriirs) or 8 (bqriirsf)
---------------------------------------------------------------------------*/
bqriirsf_handle_t bqriirsf_init( void      * objmem,
                                 int         L,
                                 int         M,
                           const float32_t * coef,
                                 float32_t   gain )
{
  bqriirsf_ptr_t bqriirs;
  void         * ptr;
  float32_t    * cf;
  float32_t    * sect;

  //
  // Validate the arguments.
  //
  
  ASSERT((L%(BBE_SIMD_WIDTH/2))==0);
  ASSERT( objmem && coef );
  if ( M <= 0 )
  {
    return NULL;
  }

  //
  // Partition the memory block.
  //

  ptr     = objmem;
  bqriirs = (bqriirsf_ptr_t)ALIGNED_ADDR( ptr, sizeof(int) );
  ptr     = bqriirs + 1;
  cf      = (float32_t*)ALIGNED_ADDR( ptr, BBE_SIMD_WIDTH/2*sizeof(float32_t) );
  ptr     = cf + 5*M;
  sect    = (float32_t*)ALIGNED_ADDR( ptr, BBE_SIMD_WIDTH/2*sizeof(float32_t) );
  ptr     = sect + 2*M*L;

  ASSERT( (int8_t*)ptr - (int8_t*)objmem <= (int)bqriirsf_alloc( L, M ) );

  //
  // Copy the filter coefficients, zero the sections state.
  //

  memcpy( cf, coef, 5*M*sizeof(float32_t) );

  memset( sect, 0, 2*M*L*sizeof(float32_t) );

  //
  // Initialize the filter instance.
  //

  memset( bqriirs, 0, sizeof( bqriirsf_t ) );

  bqriirs->magic   = MAGIC;
  bqriirs->M       = M;
  bqriirs->L       = L;
  bqriirs->gain    = gain;
  bqriirs->coef    = cf;
  bqriirs->sect    = sect;

  return (bqriirs);
}/* bqriirsf_init() */

/*---------------------------------------------------------------------------
   Pass a block of input samples to the filter and return filter output
   samples
   Input:
     _bqriirs,
     _bqriirsf    Filter handle
     N            Input/output signal chunk size, in samples (per stream)
     x[N*L]       Input samples
   Temporary:
     scr[4*N*L]   Scratch memory block, in bytes; required by the Low Noise 
                  fixed-point implementation variant (BQRIIRS_OPT_LOW_NOISE), 
                  otherwise may be null
   Output:
     r[N*L]       Output samples
   Restrictions:
     x,r          Must be aligned on 32-byte boundary
     scr          Must be aligned on 32-byte boundary, whenever supplied
     L            Must be a multiple of 16 (bqriirs) or 8 (bqriirsf)
---------------------------------------------------------------------------*/
void bqriirsf_process( bqriirsf_handle_t    _bqriirs,
                       float32_t * restrict r,
                 const float32_t *          x,
                       int                  N )
{
#define SIMD (BBE_SIMD_WIDTH/2)
  bqriirsf_ptr_t bqriirs = (bqriirsf_ptr_t)_bqriirs;
  const xb_vecN_2xf32 * restrict coef;
        xb_vecN_2xf32 * restrict sect;
  const xb_vecN_2xf32 * restrict pin;
        xb_vecN_2xf32 * restrict pout;
  xb_vecN_2xf32 gain, xin, rout;
  xb_vecN_2xf32 b0,b1,b2,a1,a2,coefvec;
  xb_vecN_2xf32 d2,d1,d0;
  xb_vecN_2xf32 acc_fb,acc_ff;
  valign al_coef;
  int M, L;
  int n, m, l;

  //
  // Validate the arguments.
  //

  NASSERT( bqriirs && bqriirs->magic == MAGIC );
  NASSERT( r && x );
  if (N<=0) return;

  coef = (const xb_vecN_2xf32 *)bqriirs->coef;
  sect = (      xb_vecN_2xf32 *)bqriirs->sect;
  M = bqriirs->M;
  L = bqriirs->L;
  gain = bqriirs->gain;
  al_coef = BBE_LAN_2XF32_PP(coef);
  
  pin  = (const xb_vecN_2xf32 *)x;
  pout = (      xb_vecN_2xf32 *)r;

  for ( m=0; m<M-1; m++ )
  {
    // load sections' coefficients
    BBE_LAVN_2XF32_XP(coefvec, al_coef, coef, 5*sizeof(float32_t));
    b0 = BBE_REPN_2XF32(coefvec, 0);
    b1 = BBE_REPN_2XF32(coefvec, 1);
    b2 = BBE_REPN_2XF32(coefvec, 2);
    a1 = BBE_REPN_2XF32(coefvec, 3);
    a2 = BBE_REPN_2XF32(coefvec, 4);

    //
    // Process SIMD streams simultaneously.
    //
    
    __Pragma("loop_count min=1");
    for ( l=0; l<(L>>(LOG2_BBE_SIMD_WIDTH-1)); l++)
    {

      // load delay elements
      d2 = BBE_LVN_2XF32_I(sect, 0*SIMD*sizeof(float32_t));
      d1 = BBE_LVN_2XF32_I(sect, 1*SIMD*sizeof(float32_t));

      //
      // Pass the block of input samples through the section. n-th sample at the
      // output of a biquad section r[n] and section state elements (d1,d2) update
      // are given by the following formulae:
      //   d0 = x[n] - a1*d1 - a2*d2
      //   r[n] = b0*d0 + b1*d1 + b2*d2;
      //   d2 = d1; d1 = d0;
      //

      __Pragma("loop_count min=1");
      for ( n=0; n<N; n++ )
      {
        BBE_LVN_2XF32_XP(xin, pin, L*sizeof(float32_t));
        // compute feedback part of the filter
        acc_fb = xin;
        BBE_MULSN_2XF32(acc_fb, a2, d2);
        BBE_MULSN_2XF32(acc_fb, a1, d1);
        d0 = acc_fb;
        // compute feedforward part of the filter
        acc_ff = BBE_MULN_2XF32(b2, d2);
        BBE_MULAN_2XF32(acc_ff, b1, d1);
        BBE_MULAN_2XF32(acc_ff, b0, d0);

        d2 = d1;
        d1 = d0;
        // Store computed sample
        rout = acc_ff;
        BBE_SVN_2XF32_XP(rout, pout, L*sizeof(float32_t));
      }

      pin  = (const xb_vecN_2xf32 *)((float32_t*)pin  + (SIMD-L*N));
      pout = (      xb_vecN_2xf32 *)((float32_t*)pout + (SIMD-L*N));
      
      // Store updated delay lines
      BBE_SVN_2XF32_IP(d2, sect, SIMD*sizeof(float32_t));
      BBE_SVN_2XF32_IP(d1, sect, SIMD*sizeof(float32_t));

    }

    pin  = (const xb_vecN_2xf32 *)r;// Use output of the last stage further
    pout = (      xb_vecN_2xf32 *)r;
  }
  
  // Process last section and apply total gain to the output
  {
    BBE_LAVN_2XF32_XP(coefvec, al_coef, coef, 5*sizeof(float32_t));
    b0 = BBE_REPN_2XF32(coefvec, 0);
    b1 = BBE_REPN_2XF32(coefvec, 1);
    b2 = BBE_REPN_2XF32(coefvec, 2);
    a1 = BBE_REPN_2XF32(coefvec, 3);
    a2 = BBE_REPN_2XF32(coefvec, 4);
    
    __Pragma("loop_count min=1");
    for ( l=0; l<(L>>(LOG2_BBE_SIMD_WIDTH-1)); l++)
    {

      d2 = BBE_LVN_2XF32_I(sect, 0*SIMD*sizeof(float32_t));
      d1 = BBE_LVN_2XF32_I(sect, 1*SIMD*sizeof(float32_t));

      __Pragma("loop_count min=1");
      for ( n=0; n<N; n++ )
      {
        BBE_LVN_2XF32_XP(xin, pin, L*sizeof(float32_t));

        acc_fb = xin;
        BBE_MULSN_2XF32(acc_fb, a2, d2);
        BBE_MULSN_2XF32(acc_fb, a1, d1);
        d0 = acc_fb;

        acc_ff = BBE_MULN_2XF32(b2, d2);
        BBE_MULAN_2XF32(acc_ff, b1, d1);
        BBE_MULAN_2XF32(acc_ff, b0, d0);

        d2 = d1;
        d1 = d0;

        rout = BBE_MULN_2XF32(acc_ff, gain);
        BBE_SVN_2XF32_XP(rout, pout, L*sizeof(float32_t));
      }

      pin  = (const xb_vecN_2xf32 *)((float32_t*)pin  + (SIMD-L*N));
      pout = (      xb_vecN_2xf32 *)((float32_t*)pout + (SIMD-L*N));

      BBE_SVN_2XF32_IP(d2, sect, SIMD*sizeof(float32_t));
      BBE_SVN_2XF32_IP(d1, sect, SIMD*sizeof(float32_t));

    }
  }
  
#undef SIMD
}/* bqriirsf_process() */

#endif /* if !(HAVE_VFPU) */
