/* ------------------------------------------------------------------------ */
/* Copyright (c) 2016 by Cadence Design Systems, Inc. ALL RIGHTS RESERVED.  */
/* These coded instructions, statements, and computer programs ('Cadence    */
/* Libraries') are the copyrighted works of Cadence Design Systems Inc.     */
/* Cadence IP is licensed for use with Cadence processor cores only and     */
/* must not be used for any other processors and platforms. Your use of the */
/* Cadence Libraries is subject to the terms of the license agreement you   */
/* have entered into with Cadence Design Systems, or a sublicense granted   */
/* to you by a direct Cadence licensee.                                     */
/* ------------------------------------------------------------------------ */
/*  IntegrIT, Ltd.   www.integrIT.com, info@integrIT.com                    */
/*                                                                          */
/* NatureDSP_Baseband Library                                               */
/*                                                                          */
/* This library contains copyrighted materials, trade secrets and other     */
/* proprietary information of IntegrIT, Ltd. This software is licensed for  */
/* use with Cadence processor cores only and must not be used for any other */
/* processors and platforms. The license to use these sources was given to  */
/* Cadence, Inc. under Terms and Condition of a Software License Agreement  */
/* between Cadence, Inc. and IntegrIT, Ltd.                                 */
/* ------------------------------------------------------------------------ */
/*          Copyright (C) 2009-2016 IntegrIT, Limited.                      */
/*                      All Rights Reserved.                                */
/* ------------------------------------------------------------------------ */

#include "NatureDSP_types.h"
#include "common.h"

#include "fft_fp_tw.h"

/*  Twiddles factors for float point FFT/IFFT cfftfN, cifftfN.
    Generated by matlab script make_cfft_twd(): 
    
function make_cfft_twd(N, fname)
v = 4;
if( nargin()==0 )
    fid = fopen('cfft_tw_header.txt', 'rt');
    
    if fid==0
        hdr_txt=''; 
    else
        hdr_txt = fread(fid, inf, 'uint8=>char');
        fclose(fid); 
        
    end
    for log2N = 4:15
        N = 2^log2N; 
        name = sprintf('cfftf%d_twd', N); 
        fname = strcat(name, '_bbe32.c'); 
        fid = fopen(fname, 'wt'); 
        if ~isempty(hdr_txt)
            fprintf(fid, '%s', hdr_txt);             
        end
        all_twd = cfft_twd(N, v); 
        print_twd(all_twd, name, fid);
        fclose(fid);
    end
else
    all_twd = cfft_twd(N, v); 
    print_twd(all_twd, fname, 1);
end
function all_twd = cfft_twd(N, v)
    all_twd = {}; 
    tw = zeros( N*3/4, 1); 
    if v~=4
        error('v~=4');
    end
    
    for j=0: N/(4*v)-1
        for i=0:v-1
            k = j*v + i; 
            tw(1 + i + j * 3 * v + 0 * v) = exp( -2*1j* pi*1 / N*k);
            tw(1 + i + j * 3 * v + 1 * v) = exp( -2*1j* pi*2 / N*k);
            tw(1 + i + j * 3 * v + 2 * v) = exp( -2*1j* pi*3 / N*k);
        end
    end    
    all_twd{end+1} = tw; 
    N = N/4;

    nstage = 2; 
    while( N > 8 )
        
        if(v>1)
            v = v/4;
        end
        if nstage==3       
            % special aligned format for stage 3
            tw = zeros( N, 1);             
            for j=0: N/(4*v)-1
                for i=0:v-1
                    k = j*v + i; 
                    tw(1 + i + j * 4 * v + 0 * v) = exp( -2*1j* pi*1 / N*k);
                    tw(1 + i + j * 4 * v + 1 * v) = exp( -2*1j* pi*2 / N*k);
                    tw(1 + i + j * 4 * v + 2 * v) = exp( -2*1j* pi*3 / N*k);
                end
            end 
        else %if nstage==3
            tw = zeros( N*3/4, 1);             
            for j=0: N/(4*v)-1
                for i=0:v-1
                    k = j*v + i; 
                    tw(1 + i + j * 3 * v + 0 * v) = exp( -2*1j* pi*1 / N*k);
                    tw(1 + i + j * 3 * v + 1 * v) = exp( -2*1j* pi*2 / N*k);
                    tw(1 + i + j * 3 * v + 2 * v) = exp( -2*1j* pi*3 / N*k);
                end
            end 
        end  % if nstage==3  else
        
        all_twd{end+1} = tw; 
        N = N/4;
        nstage = nstage + 1;
    end	
	
function print_twd(all_twd, name, fid)

for i=1:length(all_twd)
    t = all_twd{i}; 
    L = length(t); 
    tmp =  reshape( [real(t), imag(t)].', 2*L, 1 ) ; 
    s = num2hex(single(tmp)); 
    fprintf(2, 'extern const union ufloat32uint32 '); 
    fprintf(2, '%s%d[%d];\n', name, i, 2*L); 
   
    fprintf(fid, '\nALIGN(32) const union ufloat32uint32 '); 
    fprintf(fid, '%s%d[%d] = \n{\n', name, i, 2*L); 
    for k=1:2*L
        fprintf(fid, '  { 0x%s },', s(k, :)); 
        if(mod(k, 4)==0)
            fprintf(fid, '\n');     
        end            
    end
    fprintf(fid, '};\n'); 

end
*/


ALIGN(32) const union ufloat32uint32 cfftf64_twd1[96] = 
{
  { 0x3f800000 },  { 0x00000000 },  { 0x3f7ec46d },  { 0xbdc8bd36 },
  { 0x3f7b14be },  { 0xbe47c5c2 },  { 0x3f74fa0b },  { 0xbe94a031 },
  { 0x3f800000 },  { 0x00000000 },  { 0x3f7b14be },  { 0xbe47c5c2 },
  { 0x3f6c835e },  { 0xbec3ef15 },  { 0x3f54db31 },  { 0xbf0e39da },
  { 0x3f800000 },  { 0x00000000 },  { 0x3f74fa0b },  { 0xbe94a031 },
  { 0x3f54db31 },  { 0xbf0e39da },  { 0x3f226799 },  { 0xbf45e403 },
  { 0x3f6c835e },  { 0xbec3ef15 },  { 0x3f61c598 },  { 0xbef15aea },
  { 0x3f54db31 },  { 0xbf0e39da },  { 0x3f45e403 },  { 0xbf226799 },
  { 0x3f3504f3 },  { 0xbf3504f3 },  { 0x3f0e39da },  { 0xbf54db31 },
  { 0x3ec3ef15 },  { 0xbf6c835e },  { 0x3e47c5c2 },  { 0xbf7b14be },
  { 0x3ec3ef15 },  { 0xbf6c835e },  { 0x3dc8bd36 },  { 0xbf7ec46d },
  { 0xbe47c5c2 },  { 0xbf7b14be },  { 0xbef15aea },  { 0xbf61c598 },
  { 0x3f3504f3 },  { 0xbf3504f3 },  { 0x3f226799 },  { 0xbf45e403 },
  { 0x3f0e39da },  { 0xbf54db31 },  { 0x3ef15aea },  { 0xbf61c598 },
  { 0x248d3132 },  { 0xbf800000 },  { 0xbe47c5c2 },  { 0xbf7b14be },
  { 0xbec3ef15 },  { 0xbf6c835e },  { 0xbf0e39da },  { 0xbf54db31 },
  { 0xbf3504f3 },  { 0xbf3504f3 },  { 0xbf61c598 },  { 0xbef15aea },
  { 0xbf7b14be },  { 0xbe47c5c2 },  { 0xbf7ec46d },  { 0x3dc8bd36 },
  { 0x3ec3ef15 },  { 0xbf6c835e },  { 0x3e94a031 },  { 0xbf74fa0b },
  { 0x3e47c5c2 },  { 0xbf7b14be },  { 0x3dc8bd36 },  { 0xbf7ec46d },
  { 0xbf3504f3 },  { 0xbf3504f3 },  { 0xbf54db31 },  { 0xbf0e39da },
  { 0xbf6c835e },  { 0xbec3ef15 },  { 0xbf7b14be },  { 0xbe47c5c2 },
  { 0xbf6c835e },  { 0x3ec3ef15 },  { 0xbf45e403 },  { 0x3f226799 },
  { 0xbf0e39da },  { 0x3f54db31 },  { 0xbe94a031 },  { 0x3f74fa0b },
};

ALIGN(32) const union ufloat32uint32 cfftf64_twd2[24] = 
{
  { 0x3f800000 },  { 0x00000000 },  { 0x3f800000 },  { 0x00000000 },
  { 0x3f800000 },  { 0x00000000 },  { 0x3f6c835e },  { 0xbec3ef15 },
  { 0x3f3504f3 },  { 0xbf3504f3 },  { 0x3ec3ef15 },  { 0xbf6c835e },
  { 0x3f3504f3 },  { 0xbf3504f3 },  { 0x248d3132 },  { 0xbf800000 },
  { 0xbf3504f3 },  { 0xbf3504f3 },  { 0x3ec3ef15 },  { 0xbf6c835e },
  { 0xbf3504f3 },  { 0xbf3504f3 },  { 0xbf6c835e },  { 0x3ec3ef15 },
};
