/* ------------------------------------------------------------------------ */
/* Copyright (c) 2016 by Cadence Design Systems, Inc. ALL RIGHTS RESERVED.  */
/* These coded instructions, statements, and computer programs ('Cadence    */
/* Libraries') are the copyrighted works of Cadence Design Systems Inc.     */
/* Cadence IP is licensed for use with Cadence processor cores only and     */
/* must not be used for any other processors and platforms. Your use of the */
/* Cadence Libraries is subject to the terms of the license agreement you   */
/* have entered into with Cadence Design Systems, or a sublicense granted   */
/* to you by a direct Cadence licensee.                                     */
/* ------------------------------------------------------------------------ */
/*  IntegrIT, Ltd.   www.integrIT.com, info@integrIT.com                    */
/*                                                                          */
/* NatureDSP_Baseband Library                                               */
/*                                                                          */
/* This library contains copyrighted materials, trade secrets and other     */
/* proprietary information of IntegrIT, Ltd. This software is licensed for  */
/* use with Cadence processor cores only and must not be used for any other */
/* processors and platforms. The license to use these sources was given to  */
/* Cadence, Inc. under Terms and Condition of a Software License Agreement  */
/* between Cadence, Inc. and IntegrIT, Ltd.                                 */
/* ------------------------------------------------------------------------ */
/*          Copyright (C) 2009-2016 IntegrIT, Limited.                      */
/*                      All Rights Reserved.                                */
/* ------------------------------------------------------------------------ */

#include "NatureDSP_types.h"
#include "common.h"

#include "fft_fp_tw.h"

/*  Twiddles factors for float point FFT/IFFT cfftfN, cifftfN.
    Generated by matlab script make_cfft_twd(): 
    
function make_cfft_twd(N, fname)
v = 4;
if( nargin()==0 )
    fid = fopen('cfft_tw_header.txt', 'rt');
    
    if fid==0
        hdr_txt=''; 
    else
        hdr_txt = fread(fid, inf, 'uint8=>char');
        fclose(fid); 
        
    end
    for log2N = 4:15
        N = 2^log2N; 
        name = sprintf('cfftf%d_twd', N); 
        fname = strcat(name, '_bbe32.c'); 
        fid = fopen(fname, 'wt'); 
        if ~isempty(hdr_txt)
            fprintf(fid, '%s', hdr_txt);             
        end
        all_twd = cfft_twd(N, v); 
        print_twd(all_twd, name, fid);
        fclose(fid);
    end
else
    all_twd = cfft_twd(N, v); 
    print_twd(all_twd, fname, 1);
end
function all_twd = cfft_twd(N, v)
    all_twd = {}; 
    tw = zeros( N*3/4, 1); 
    if v~=4
        error('v~=4');
    end
    
    for j=0: N/(4*v)-1
        for i=0:v-1
            k = j*v + i; 
            tw(1 + i + j * 3 * v + 0 * v) = exp( -2*1j* pi*1 / N*k);
            tw(1 + i + j * 3 * v + 1 * v) = exp( -2*1j* pi*2 / N*k);
            tw(1 + i + j * 3 * v + 2 * v) = exp( -2*1j* pi*3 / N*k);
        end
    end    
    all_twd{end+1} = tw; 
    N = N/4;

    nstage = 2; 
    while( N > 8 )
        
        if(v>1)
            v = v/4;
        end
        if nstage==3       
            % special aligned format for stage 3
            tw = zeros( N, 1);             
            for j=0: N/(4*v)-1
                for i=0:v-1
                    k = j*v + i; 
                    tw(1 + i + j * 4 * v + 0 * v) = exp( -2*1j* pi*1 / N*k);
                    tw(1 + i + j * 4 * v + 1 * v) = exp( -2*1j* pi*2 / N*k);
                    tw(1 + i + j * 4 * v + 2 * v) = exp( -2*1j* pi*3 / N*k);
                end
            end 
        else %if nstage==3
            tw = zeros( N*3/4, 1);             
            for j=0: N/(4*v)-1
                for i=0:v-1
                    k = j*v + i; 
                    tw(1 + i + j * 3 * v + 0 * v) = exp( -2*1j* pi*1 / N*k);
                    tw(1 + i + j * 3 * v + 1 * v) = exp( -2*1j* pi*2 / N*k);
                    tw(1 + i + j * 3 * v + 2 * v) = exp( -2*1j* pi*3 / N*k);
                end
            end 
        end  % if nstage==3  else
        
        all_twd{end+1} = tw; 
        N = N/4;
        nstage = nstage + 1;
    end	
	
function print_twd(all_twd, name, fid)

for i=1:length(all_twd)
    t = all_twd{i}; 
    L = length(t); 
    tmp =  reshape( [real(t), imag(t)].', 2*L, 1 ) ; 
    s = num2hex(single(tmp)); 
    fprintf(2, 'extern const union ufloat32uint32 '); 
    fprintf(2, '%s%d[%d];\n', name, i, 2*L); 
   
    fprintf(fid, '\nALIGN(32) const union ufloat32uint32 '); 
    fprintf(fid, '%s%d[%d] = \n{\n', name, i, 2*L); 
    for k=1:2*L
        fprintf(fid, '  { 0x%s },', s(k, :)); 
        if(mod(k, 4)==0)
            fprintf(fid, '\n');     
        end            
    end
    fprintf(fid, '};\n'); 

end
*/


ALIGN(32) const union ufloat32uint32 cfftf512_twd1[768] = 
{
  { 0x3f800000 },  { 0x00000000 },  { 0x3f7ffb11 },  { 0xbc490e90 },
  { 0x3f7fec43 },  { 0xbcc90ab0 },  { 0x3f7fd397 },  { 0xbd16c32c },
  { 0x3f800000 },  { 0x00000000 },  { 0x3f7fec43 },  { 0xbcc90ab0 },
  { 0x3f7fb10f },  { 0xbd48fb30 },  { 0x3f7f4e6d },  { 0xbd96a905 },
  { 0x3f800000 },  { 0x00000000 },  { 0x3f7fd397 },  { 0xbd16c32c },
  { 0x3f7f4e6d },  { 0xbd96a905 },  { 0x3f7e70b0 },  { 0xbde1bc2e },
  { 0x3f7fb10f },  { 0xbd48fb30 },  { 0x3f7f84ab },  { 0xbd7b2b74 },
  { 0x3f7f4e6d },  { 0xbd96a905 },  { 0x3f7f0e58 },  { 0xbdafb680 },
  { 0x3f7ec46d },  { 0xbdc8bd36 },  { 0x3f7e1324 },  { 0xbdfab273 },
  { 0x3f7d3aac },  { 0xbe164083 },  { 0x3f7c3b28 },  { 0xbe2f10a2 },
  { 0x3f7d3aac },  { 0xbe164083 },  { 0x3f7baccd },  { 0xbe3b6ecf },
  { 0x3f79c79d },  { 0xbe605c13 },  { 0x3f778bc5 },  { 0xbe827dc0 },
  { 0x3f7ec46d },  { 0xbdc8bd36 },  { 0x3f7e70b0 },  { 0xbde1bc2e },
  { 0x3f7e1324 },  { 0xbdfab273 },  { 0x3f7dabcc },  { 0xbe09cf86 },
  { 0x3f7b14be },  { 0xbe47c5c2 },  { 0x3f79c79d },  { 0xbe605c13 },
  { 0x3f7853f8 },  { 0xbe78cfcc },  { 0x3f76ba07 },  { 0xbe888e93 },
  { 0x3f74fa0b },  { 0xbe94a031 },  { 0x3f721352 },  { 0xbea68f12 },
  { 0x3f6ed89e },  { 0xbeb8442a },  { 0x3f6b4b0c },  { 0xbec9b953 },
  { 0x3f7d3aac },  { 0xbe164083 },  { 0x3f7cbfc9 },  { 0xbe22abb6 },
  { 0x3f7c3b28 },  { 0xbe2f10a2 },  { 0x3f7baccd },  { 0xbe3b6ecf },
  { 0x3f74fa0b },  { 0xbe94a031 },  { 0x3f731447 },  { 0xbea09ae5 },
  { 0x3f710908 },  { 0xbeac7cd4 },  { 0x3f6ed89e },  { 0xbeb8442a },
  { 0x3f676bd8 },  { 0xbedae880 },  { 0x3f633c5a },  { 0xbeebcbbb },
  { 0x3f5ebe05 },  { 0xbefc5d27 },  { 0x3f59f26a },  { 0xbf064b82 },
  { 0x3f7b14be },  { 0xbe47c5c2 },  { 0x3f7a7302 },  { 0xbe541501 },
  { 0x3f79c79d },  { 0xbe605c13 },  { 0x3f791298 },  { 0xbe6c9a7f },
  { 0x3f6c835e },  { 0xbec3ef15 },  { 0x3f6a09a7 },  { 0xbecf7bca },
  { 0x3f676bd8 },  { 0xbedae880 },  { 0x3f64aa59 },  { 0xbee63375 },
  { 0x3f54db31 },  { 0xbf0e39da },  { 0x3f4f7a1f },  { 0xbf15f6d9 },
  { 0x3f49d112 },  { 0xbf1d7fd1 },  { 0x3f43e200 },  { 0xbf24d225 },
  { 0x3f7853f8 },  { 0xbe78cfcc },  { 0x3f778bc5 },  { 0xbe827dc0 },
  { 0x3f76ba07 },  { 0xbe888e93 },  { 0x3f75dec6 },  { 0xbe8e9a22 },
  { 0x3f61c598 },  { 0xbef15aea },  { 0x3f5ebe05 },  { 0xbefc5d27 },
  { 0x3f5b941a },  { 0xbf039c3d },  { 0x3f584853 },  { 0xbf08f59b },
  { 0x3f3daef9 },  { 0xbf2beb4a },  { 0x3f373a23 },  { 0xbf32c8c9 },
  { 0x3f3085bb },  { 0xbf396842 },  { 0x3f299415 },  { 0xbf3fc767 },
  { 0x3f74fa0b },  { 0xbe94a031 },  { 0x3f740bdd },  { 0xbe9aa086 },
  { 0x3f731447 },  { 0xbea09ae5 },  { 0x3f721352 },  { 0xbea68f12 },
  { 0x3f54db31 },  { 0xbf0e39da },  { 0x3f514d3d },  { 0xbf13682a },
  { 0x3f4d9f02 },  { 0xbf187fc0 },  { 0x3f49d112 },  { 0xbf1d7fd1 },
  { 0x3f226799 },  { 0xbf45e403 },  { 0x3f1b02c6 },  { 0xbf4bbbf8 },
  { 0x3f13682a },  { 0xbf514d3d },  { 0x3f0b9a6b },  { 0xbf5695e5 },
  { 0x3f710908 },  { 0xbeac7cd4 },  { 0x3f6ff573 },  { 0xbeb263ef },
  { 0x3f6ed89e },  { 0xbeb8442a },  { 0x3f6db293 },  { 0xbebe1d4a },
  { 0x3f45e403 },  { 0xbf226799 },  { 0x3f41d870 },  { 0xbf273656 },
  { 0x3f3daef9 },  { 0xbf2beb4a },  { 0x3f396842 },  { 0xbf3085bb },
  { 0x3f039c3d },  { 0xbf5b941a },  { 0x3ef6e0cb },  { 0xbf604621 },
  { 0x3ee63375 },  { 0xbf64aa59 },  { 0x3ed53641 },  { 0xbf68bf3c },
  { 0x3f6c835e },  { 0xbec3ef15 },  { 0x3f6b4b0c },  { 0xbec9b953 },
  { 0x3f6a09a7 },  { 0xbecf7bca },  { 0x3f68bf3c },  { 0xbed53641 },
  { 0x3f3504f3 },  { 0xbf3504f3 },  { 0x3f3085bb },  { 0xbf396842 },
  { 0x3f2beb4a },  { 0xbf3daef9 },  { 0x3f273656 },  { 0xbf41d870 },
  { 0x3ec3ef15 },  { 0xbf6c835e },  { 0x3eb263ef },  { 0xbf6ff573 },
  { 0x3ea09ae5 },  { 0xbf731447 },  { 0x3e8e9a22 },  { 0xbf75dec6 },
  { 0x3f676bd8 },  { 0xbedae880 },  { 0x3f660f88 },  { 0xbee0924f },
  { 0x3f64aa59 },  { 0xbee63375 },  { 0x3f633c5a },  { 0xbeebcbbb },
  { 0x3f226799 },  { 0xbf45e403 },  { 0x3f1d7fd1 },  { 0xbf49d112 },
  { 0x3f187fc0 },  { 0xbf4d9f02 },  { 0x3f13682a },  { 0xbf514d3d },
  { 0x3e78cfcc },  { 0xbf7853f8 },  { 0x3e541501 },  { 0xbf7a7302 },
  { 0x3e2f10a2 },  { 0xbf7c3b28 },  { 0x3e09cf86 },  { 0xbf7dabcc },
  { 0x3f61c598 },  { 0xbef15aea },  { 0x3f604621 },  { 0xbef6e0cb },
  { 0x3f5ebe05 },  { 0xbefc5d27 },  { 0x3f5d2d53 },  { 0xbf00e7e4 },
  { 0x3f0e39da },  { 0xbf54db31 },  { 0x3f08f59b },  { 0xbf584853 },
  { 0x3f039c3d },  { 0xbf5b941a },  { 0x3efc5d27 },  { 0xbf5ebe05 },
  { 0x3dc8bd36 },  { 0xbf7ec46d },  { 0x3d7b2b74 },  { 0xbf7f84ab },
  { 0x3cc90ab0 },  { 0xbf7fec43 },  { 0xbc490e90 },  { 0xbf7ffb11 },
  { 0x3f5b941a },  { 0xbf039c3d },  { 0x3f59f26a },  { 0xbf064b82 },
  { 0x3f584853 },  { 0xbf08f59b },  { 0x3f5695e5 },  { 0xbf0b9a6b },
  { 0x3ef15aea },  { 0xbf61c598 },  { 0x3ee63375 },  { 0xbf64aa59 },
  { 0x3edae880 },  { 0xbf676bd8 },  { 0x3ecf7bca },  { 0xbf6a09a7 },
  { 0xbd48fb30 },  { 0xbf7fb10f },  { 0xbdafb680 },  { 0xbf7f0e58 },
  { 0xbdfab273 },  { 0xbf7e1324 },  { 0xbe22abb6 },  { 0xbf7cbfc9 },
  { 0x3f54db31 },  { 0xbf0e39da },  { 0x3f531849 },  { 0xbf10d3cd },
  { 0x3f514d3d },  { 0xbf13682a },  { 0x3f4f7a1f },  { 0xbf15f6d9 },
  { 0x3ec3ef15 },  { 0xbf6c835e },  { 0x3eb8442a },  { 0xbf6ed89e },
  { 0x3eac7cd4 },  { 0xbf710908 },  { 0x3ea09ae5 },  { 0xbf731447 },
  { 0xbe47c5c2 },  { 0xbf7b14be },  { 0xbe6c9a7f },  { 0xbf791298 },
  { 0xbe888e93 },  { 0xbf76ba07 },  { 0xbe9aa086 },  { 0xbf740bdd },
  { 0x3f4d9f02 },  { 0xbf187fc0 },  { 0x3f4bbbf8 },  { 0xbf1b02c6 },
  { 0x3f49d112 },  { 0xbf1d7fd1 },  { 0x3f47de65 },  { 0xbf1ff6cb },
  { 0x3e94a031 },  { 0xbf74fa0b },  { 0x3e888e93 },  { 0xbf76ba07 },
  { 0x3e78cfcc },  { 0xbf7853f8 },  { 0x3e605c13 },  { 0xbf79c79d },
  { 0xbeac7cd4 },  { 0xbf710908 },  { 0xbebe1d4a },  { 0xbf6db293 },
  { 0xbecf7bca },  { 0xbf6a09a7 },  { 0xbee0924f },  { 0xbf660f88 },
  { 0x3f45e403 },  { 0xbf226799 },  { 0x3f43e200 },  { 0xbf24d225 },
  { 0x3f41d870 },  { 0xbf273656 },  { 0x3f3fc767 },  { 0xbf299415 },
  { 0x3e47c5c2 },  { 0xbf7b14be },  { 0x3e2f10a2 },  { 0xbf7c3b28 },
  { 0x3e164083 },  { 0xbf7d3aac },  { 0x3dfab273 },  { 0xbf7e1324 },
  { 0xbef15aea },  { 0xbf61c598 },  { 0xbf00e7e4 },  { 0xbf5d2d53 },
  { 0xbf08f59b },  { 0xbf584853 },  { 0xbf10d3cd },  { 0xbf531849 },
  { 0x3f3daef9 },  { 0xbf2beb4a },  { 0x3f3b8f3b },  { 0xbf2e3bde },
  { 0x3f396842 },  { 0xbf3085bb },  { 0x3f373a23 },  { 0xbf32c8c9 },
  { 0x3dc8bd36 },  { 0xbf7ec46d },  { 0x3d96a905 },  { 0xbf7f4e6d },
  { 0x3d48fb30 },  { 0xbf7fb10f },  { 0x3cc90ab0 },  { 0xbf7fec43 },
  { 0xbf187fc0 },  { 0xbf4d9f02 },  { 0xbf1ff6cb },  { 0xbf47de65 },
  { 0xbf273656 },  { 0xbf41d870 },  { 0xbf2e3bde },  { 0xbf3b8f3b },
  { 0x3f3504f3 },  { 0xbf3504f3 },  { 0x3f32c8c9 },  { 0xbf373a23 },
  { 0x3f3085bb },  { 0xbf396842 },  { 0x3f2e3bde },  { 0xbf3b8f3b },
  { 0x248d3132 },  { 0xbf800000 },  { 0xbcc90ab0 },  { 0xbf7fec43 },
  { 0xbd48fb30 },  { 0xbf7fb10f },  { 0xbd96a905 },  { 0xbf7f4e6d },
  { 0xbf3504f3 },  { 0xbf3504f3 },  { 0xbf3b8f3b },  { 0xbf2e3bde },
  { 0xbf41d870 },  { 0xbf273656 },  { 0xbf47de65 },  { 0xbf1ff6cb },
  { 0x3f2beb4a },  { 0xbf3daef9 },  { 0x3f299415 },  { 0xbf3fc767 },
  { 0x3f273656 },  { 0xbf41d870 },  { 0x3f24d225 },  { 0xbf43e200 },
  { 0xbdc8bd36 },  { 0xbf7ec46d },  { 0xbdfab273 },  { 0xbf7e1324 },
  { 0xbe164083 },  { 0xbf7d3aac },  { 0xbe2f10a2 },  { 0xbf7c3b28 },
  { 0xbf4d9f02 },  { 0xbf187fc0 },  { 0xbf531849 },  { 0xbf10d3cd },
  { 0xbf584853 },  { 0xbf08f59b },  { 0xbf5d2d53 },  { 0xbf00e7e4 },
  { 0x3f226799 },  { 0xbf45e403 },  { 0x3f1ff6cb },  { 0xbf47de65 },
  { 0x3f1d7fd1 },  { 0xbf49d112 },  { 0x3f1b02c6 },  { 0xbf4bbbf8 },
  { 0xbe47c5c2 },  { 0xbf7b14be },  { 0xbe605c13 },  { 0xbf79c79d },
  { 0xbe78cfcc },  { 0xbf7853f8 },  { 0xbe888e93 },  { 0xbf76ba07 },
  { 0xbf61c598 },  { 0xbef15aea },  { 0xbf660f88 },  { 0xbee0924f },
  { 0xbf6a09a7 },  { 0xbecf7bca },  { 0xbf6db293 },  { 0xbebe1d4a },
  { 0x3f187fc0 },  { 0xbf4d9f02 },  { 0x3f15f6d9 },  { 0xbf4f7a1f },
  { 0x3f13682a },  { 0xbf514d3d },  { 0x3f10d3cd },  { 0xbf531849 },
  { 0xbe94a031 },  { 0xbf74fa0b },  { 0xbea09ae5 },  { 0xbf731447 },
  { 0xbeac7cd4 },  { 0xbf710908 },  { 0xbeb8442a },  { 0xbf6ed89e },
  { 0xbf710908 },  { 0xbeac7cd4 },  { 0xbf740bdd },  { 0xbe9aa086 },
  { 0xbf76ba07 },  { 0xbe888e93 },  { 0xbf791298 },  { 0xbe6c9a7f },
  { 0x3f0e39da },  { 0xbf54db31 },  { 0x3f0b9a6b },  { 0xbf5695e5 },
  { 0x3f08f59b },  { 0xbf584853 },  { 0x3f064b82 },  { 0xbf59f26a },
  { 0xbec3ef15 },  { 0xbf6c835e },  { 0xbecf7bca },  { 0xbf6a09a7 },
  { 0xbedae880 },  { 0xbf676bd8 },  { 0xbee63375 },  { 0xbf64aa59 },
  { 0xbf7b14be },  { 0xbe47c5c2 },  { 0xbf7cbfc9 },  { 0xbe22abb6 },
  { 0xbf7e1324 },  { 0xbdfab273 },  { 0xbf7f0e58 },  { 0xbdafb680 },
  { 0x3f039c3d },  { 0xbf5b941a },  { 0x3f00e7e4 },  { 0xbf5d2d53 },
  { 0x3efc5d27 },  { 0xbf5ebe05 },  { 0x3ef6e0cb },  { 0xbf604621 },
  { 0xbef15aea },  { 0xbf61c598 },  { 0xbefc5d27 },  { 0xbf5ebe05 },
  { 0xbf039c3d },  { 0xbf5b941a },  { 0xbf08f59b },  { 0xbf584853 },
  { 0xbf7fb10f },  { 0xbd48fb30 },  { 0xbf7ffb11 },  { 0xbc490e90 },
  { 0xbf7fec43 },  { 0x3cc90ab0 },  { 0xbf7f84ab },  { 0x3d7b2b74 },
  { 0x3ef15aea },  { 0xbf61c598 },  { 0x3eebcbbb },  { 0xbf633c5a },
  { 0x3ee63375 },  { 0xbf64aa59 },  { 0x3ee0924f },  { 0xbf660f88 },
  { 0xbf0e39da },  { 0xbf54db31 },  { 0xbf13682a },  { 0xbf514d3d },
  { 0xbf187fc0 },  { 0xbf4d9f02 },  { 0xbf1d7fd1 },  { 0xbf49d112 },
  { 0xbf7ec46d },  { 0x3dc8bd36 },  { 0xbf7dabcc },  { 0x3e09cf86 },
  { 0xbf7c3b28 },  { 0x3e2f10a2 },  { 0xbf7a7302 },  { 0x3e541501 },
  { 0x3edae880 },  { 0xbf676bd8 },  { 0x3ed53641 },  { 0xbf68bf3c },
  { 0x3ecf7bca },  { 0xbf6a09a7 },  { 0x3ec9b953 },  { 0xbf6b4b0c },
  { 0xbf226799 },  { 0xbf45e403 },  { 0xbf273656 },  { 0xbf41d870 },
  { 0xbf2beb4a },  { 0xbf3daef9 },  { 0xbf3085bb },  { 0xbf396842 },
  { 0xbf7853f8 },  { 0x3e78cfcc },  { 0xbf75dec6 },  { 0x3e8e9a22 },
  { 0xbf731447 },  { 0x3ea09ae5 },  { 0xbf6ff573 },  { 0x3eb263ef },
  { 0x3ec3ef15 },  { 0xbf6c835e },  { 0x3ebe1d4a },  { 0xbf6db293 },
  { 0x3eb8442a },  { 0xbf6ed89e },  { 0x3eb263ef },  { 0xbf6ff573 },
  { 0xbf3504f3 },  { 0xbf3504f3 },  { 0xbf396842 },  { 0xbf3085bb },
  { 0xbf3daef9 },  { 0xbf2beb4a },  { 0xbf41d870 },  { 0xbf273656 },
  { 0xbf6c835e },  { 0x3ec3ef15 },  { 0xbf68bf3c },  { 0x3ed53641 },
  { 0xbf64aa59 },  { 0x3ee63375 },  { 0xbf604621 },  { 0x3ef6e0cb },
  { 0x3eac7cd4 },  { 0xbf710908 },  { 0x3ea68f12 },  { 0xbf721352 },
  { 0x3ea09ae5 },  { 0xbf731447 },  { 0x3e9aa086 },  { 0xbf740bdd },
  { 0xbf45e403 },  { 0xbf226799 },  { 0xbf49d112 },  { 0xbf1d7fd1 },
  { 0xbf4d9f02 },  { 0xbf187fc0 },  { 0xbf514d3d },  { 0xbf13682a },
  { 0xbf5b941a },  { 0x3f039c3d },  { 0xbf5695e5 },  { 0x3f0b9a6b },
  { 0xbf514d3d },  { 0x3f13682a },  { 0xbf4bbbf8 },  { 0x3f1b02c6 },
  { 0x3e94a031 },  { 0xbf74fa0b },  { 0x3e8e9a22 },  { 0xbf75dec6 },
  { 0x3e888e93 },  { 0xbf76ba07 },  { 0x3e827dc0 },  { 0xbf778bc5 },
  { 0xbf54db31 },  { 0xbf0e39da },  { 0xbf584853 },  { 0xbf08f59b },
  { 0xbf5b941a },  { 0xbf039c3d },  { 0xbf5ebe05 },  { 0xbefc5d27 },
  { 0xbf45e403 },  { 0x3f226799 },  { 0xbf3fc767 },  { 0x3f299415 },
  { 0xbf396842 },  { 0x3f3085bb },  { 0xbf32c8c9 },  { 0x3f373a23 },
  { 0x3e78cfcc },  { 0xbf7853f8 },  { 0x3e6c9a7f },  { 0xbf791298 },
  { 0x3e605c13 },  { 0xbf79c79d },  { 0x3e541501 },  { 0xbf7a7302 },
  { 0xbf61c598 },  { 0xbef15aea },  { 0xbf64aa59 },  { 0xbee63375 },
  { 0xbf676bd8 },  { 0xbedae880 },  { 0xbf6a09a7 },  { 0xbecf7bca },
  { 0xbf2beb4a },  { 0x3f3daef9 },  { 0xbf24d225 },  { 0x3f43e200 },
  { 0xbf1d7fd1 },  { 0x3f49d112 },  { 0xbf15f6d9 },  { 0x3f4f7a1f },
  { 0x3e47c5c2 },  { 0xbf7b14be },  { 0x3e3b6ecf },  { 0xbf7baccd },
  { 0x3e2f10a2 },  { 0xbf7c3b28 },  { 0x3e22abb6 },  { 0xbf7cbfc9 },
  { 0xbf6c835e },  { 0xbec3ef15 },  { 0xbf6ed89e },  { 0xbeb8442a },
  { 0xbf710908 },  { 0xbeac7cd4 },  { 0xbf731447 },  { 0xbea09ae5 },
  { 0xbf0e39da },  { 0x3f54db31 },  { 0xbf064b82 },  { 0x3f59f26a },
  { 0xbefc5d27 },  { 0x3f5ebe05 },  { 0xbeebcbbb },  { 0x3f633c5a },
  { 0x3e164083 },  { 0xbf7d3aac },  { 0x3e09cf86 },  { 0xbf7dabcc },
  { 0x3dfab273 },  { 0xbf7e1324 },  { 0x3de1bc2e },  { 0xbf7e70b0 },
  { 0xbf74fa0b },  { 0xbe94a031 },  { 0xbf76ba07 },  { 0xbe888e93 },
  { 0xbf7853f8 },  { 0xbe78cfcc },  { 0xbf79c79d },  { 0xbe605c13 },
  { 0xbedae880 },  { 0x3f676bd8 },  { 0xbec9b953 },  { 0x3f6b4b0c },
  { 0xbeb8442a },  { 0x3f6ed89e },  { 0xbea68f12 },  { 0x3f721352 },
  { 0x3dc8bd36 },  { 0xbf7ec46d },  { 0x3dafb680 },  { 0xbf7f0e58 },
  { 0x3d96a905 },  { 0xbf7f4e6d },  { 0x3d7b2b74 },  { 0xbf7f84ab },
  { 0xbf7b14be },  { 0xbe47c5c2 },  { 0xbf7c3b28 },  { 0xbe2f10a2 },
  { 0xbf7d3aac },  { 0xbe164083 },  { 0xbf7e1324 },  { 0xbdfab273 },
  { 0xbe94a031 },  { 0x3f74fa0b },  { 0xbe827dc0 },  { 0x3f778bc5 },
  { 0xbe605c13 },  { 0x3f79c79d },  { 0xbe3b6ecf },  { 0x3f7baccd },
  { 0x3d48fb30 },  { 0xbf7fb10f },  { 0x3d16c32c },  { 0xbf7fd397 },
  { 0x3cc90ab0 },  { 0xbf7fec43 },  { 0x3c490e90 },  { 0xbf7ffb11 },
  { 0xbf7ec46d },  { 0xbdc8bd36 },  { 0xbf7f4e6d },  { 0xbd96a905 },
  { 0xbf7fb10f },  { 0xbd48fb30 },  { 0xbf7fec43 },  { 0xbcc90ab0 },
  { 0xbe164083 },  { 0x3f7d3aac },  { 0xbde1bc2e },  { 0x3f7e70b0 },
  { 0xbd96a905 },  { 0x3f7f4e6d },  { 0xbd16c32c },  { 0x3f7fd397 },
};

ALIGN(32) const union ufloat32uint32 cfftf512_twd2[192] = 
{
  { 0x3f800000 },  { 0x00000000 },  { 0x3f800000 },  { 0x00000000 },
  { 0x3f800000 },  { 0x00000000 },  { 0x3f7fb10f },  { 0xbd48fb30 },
  { 0x3f7ec46d },  { 0xbdc8bd36 },  { 0x3f7d3aac },  { 0xbe164083 },
  { 0x3f7ec46d },  { 0xbdc8bd36 },  { 0x3f7b14be },  { 0xbe47c5c2 },
  { 0x3f74fa0b },  { 0xbe94a031 },  { 0x3f7d3aac },  { 0xbe164083 },
  { 0x3f74fa0b },  { 0xbe94a031 },  { 0x3f676bd8 },  { 0xbedae880 },
  { 0x3f7b14be },  { 0xbe47c5c2 },  { 0x3f6c835e },  { 0xbec3ef15 },
  { 0x3f54db31 },  { 0xbf0e39da },  { 0x3f7853f8 },  { 0xbe78cfcc },
  { 0x3f61c598 },  { 0xbef15aea },  { 0x3f3daef9 },  { 0xbf2beb4a },
  { 0x3f74fa0b },  { 0xbe94a031 },  { 0x3f54db31 },  { 0xbf0e39da },
  { 0x3f226799 },  { 0xbf45e403 },  { 0x3f710908 },  { 0xbeac7cd4 },
  { 0x3f45e403 },  { 0xbf226799 },  { 0x3f039c3d },  { 0xbf5b941a },
  { 0x3f6c835e },  { 0xbec3ef15 },  { 0x3f3504f3 },  { 0xbf3504f3 },
  { 0x3ec3ef15 },  { 0xbf6c835e },  { 0x3f676bd8 },  { 0xbedae880 },
  { 0x3f226799 },  { 0xbf45e403 },  { 0x3e78cfcc },  { 0xbf7853f8 },
  { 0x3f61c598 },  { 0xbef15aea },  { 0x3f0e39da },  { 0xbf54db31 },
  { 0x3dc8bd36 },  { 0xbf7ec46d },  { 0x3f5b941a },  { 0xbf039c3d },
  { 0x3ef15aea },  { 0xbf61c598 },  { 0xbd48fb30 },  { 0xbf7fb10f },
  { 0x3f54db31 },  { 0xbf0e39da },  { 0x3ec3ef15 },  { 0xbf6c835e },
  { 0xbe47c5c2 },  { 0xbf7b14be },  { 0x3f4d9f02 },  { 0xbf187fc0 },
  { 0x3e94a031 },  { 0xbf74fa0b },  { 0xbeac7cd4 },  { 0xbf710908 },
  { 0x3f45e403 },  { 0xbf226799 },  { 0x3e47c5c2 },  { 0xbf7b14be },
  { 0xbef15aea },  { 0xbf61c598 },  { 0x3f3daef9 },  { 0xbf2beb4a },
  { 0x3dc8bd36 },  { 0xbf7ec46d },  { 0xbf187fc0 },  { 0xbf4d9f02 },
  { 0x3f3504f3 },  { 0xbf3504f3 },  { 0x248d3132 },  { 0xbf800000 },
  { 0xbf3504f3 },  { 0xbf3504f3 },  { 0x3f2beb4a },  { 0xbf3daef9 },
  { 0xbdc8bd36 },  { 0xbf7ec46d },  { 0xbf4d9f02 },  { 0xbf187fc0 },
  { 0x3f226799 },  { 0xbf45e403 },  { 0xbe47c5c2 },  { 0xbf7b14be },
  { 0xbf61c598 },  { 0xbef15aea },  { 0x3f187fc0 },  { 0xbf4d9f02 },
  { 0xbe94a031 },  { 0xbf74fa0b },  { 0xbf710908 },  { 0xbeac7cd4 },
  { 0x3f0e39da },  { 0xbf54db31 },  { 0xbec3ef15 },  { 0xbf6c835e },
  { 0xbf7b14be },  { 0xbe47c5c2 },  { 0x3f039c3d },  { 0xbf5b941a },
  { 0xbef15aea },  { 0xbf61c598 },  { 0xbf7fb10f },  { 0xbd48fb30 },
  { 0x3ef15aea },  { 0xbf61c598 },  { 0xbf0e39da },  { 0xbf54db31 },
  { 0xbf7ec46d },  { 0x3dc8bd36 },  { 0x3edae880 },  { 0xbf676bd8 },
  { 0xbf226799 },  { 0xbf45e403 },  { 0xbf7853f8 },  { 0x3e78cfcc },
  { 0x3ec3ef15 },  { 0xbf6c835e },  { 0xbf3504f3 },  { 0xbf3504f3 },
  { 0xbf6c835e },  { 0x3ec3ef15 },  { 0x3eac7cd4 },  { 0xbf710908 },
  { 0xbf45e403 },  { 0xbf226799 },  { 0xbf5b941a },  { 0x3f039c3d },
  { 0x3e94a031 },  { 0xbf74fa0b },  { 0xbf54db31 },  { 0xbf0e39da },
  { 0xbf45e403 },  { 0x3f226799 },  { 0x3e78cfcc },  { 0xbf7853f8 },
  { 0xbf61c598 },  { 0xbef15aea },  { 0xbf2beb4a },  { 0x3f3daef9 },
  { 0x3e47c5c2 },  { 0xbf7b14be },  { 0xbf6c835e },  { 0xbec3ef15 },
  { 0xbf0e39da },  { 0x3f54db31 },  { 0x3e164083 },  { 0xbf7d3aac },
  { 0xbf74fa0b },  { 0xbe94a031 },  { 0xbedae880 },  { 0x3f676bd8 },
  { 0x3dc8bd36 },  { 0xbf7ec46d },  { 0xbf7b14be },  { 0xbe47c5c2 },
  { 0xbe94a031 },  { 0x3f74fa0b },  { 0x3d48fb30 },  { 0xbf7fb10f },
  { 0xbf7ec46d },  { 0xbdc8bd36 },  { 0xbe164083 },  { 0x3f7d3aac },
};

ALIGN(32) const union ufloat32uint32 cfftf512_twd3[64] = 
{
  { 0x3f800000 },  { 0x00000000 },  { 0x3f800000 },  { 0x00000000 },
  { 0x3f800000 },  { 0x00000000 },  { 0x00000000 },  { 0x00000000 },
  { 0x3f7b14be },  { 0xbe47c5c2 },  { 0x3f6c835e },  { 0xbec3ef15 },
  { 0x3f54db31 },  { 0xbf0e39da },  { 0x00000000 },  { 0x00000000 },
  { 0x3f6c835e },  { 0xbec3ef15 },  { 0x3f3504f3 },  { 0xbf3504f3 },
  { 0x3ec3ef15 },  { 0xbf6c835e },  { 0x00000000 },  { 0x00000000 },
  { 0x3f54db31 },  { 0xbf0e39da },  { 0x3ec3ef15 },  { 0xbf6c835e },
  { 0xbe47c5c2 },  { 0xbf7b14be },  { 0x00000000 },  { 0x00000000 },
  { 0x3f3504f3 },  { 0xbf3504f3 },  { 0x248d3132 },  { 0xbf800000 },
  { 0xbf3504f3 },  { 0xbf3504f3 },  { 0x00000000 },  { 0x00000000 },
  { 0x3f0e39da },  { 0xbf54db31 },  { 0xbec3ef15 },  { 0xbf6c835e },
  { 0xbf7b14be },  { 0xbe47c5c2 },  { 0x00000000 },  { 0x00000000 },
  { 0x3ec3ef15 },  { 0xbf6c835e },  { 0xbf3504f3 },  { 0xbf3504f3 },
  { 0xbf6c835e },  { 0x3ec3ef15 },  { 0x00000000 },  { 0x00000000 },
  { 0x3e47c5c2 },  { 0xbf7b14be },  { 0xbf6c835e },  { 0xbec3ef15 },
  { 0xbf0e39da },  { 0x3f54db31 },  { 0x00000000 },  { 0x00000000 },
};
