/* ------------------------------------------------------------------------ */
/* Copyright (c) 2016 by Cadence Design Systems, Inc. ALL RIGHTS RESERVED.  */
/* These coded instructions, statements, and computer programs ('Cadence    */
/* Libraries') are the copyrighted works of Cadence Design Systems Inc.     */
/* Cadence IP is licensed for use with Cadence processor cores only and     */
/* must not be used for any other processors and platforms. Your use of the */
/* Cadence Libraries is subject to the terms of the license agreement you   */
/* have entered into with Cadence Design Systems, or a sublicense granted   */
/* to you by a direct Cadence licensee.                                     */
/* ------------------------------------------------------------------------ */
/*  IntegrIT, Ltd.   www.integrIT.com, info@integrIT.com                    */
/*                                                                          */
/* NatureDSP_Baseband Library                                               */
/*                                                                          */
/* This library contains copyrighted materials, trade secrets and other     */
/* proprietary information of IntegrIT, Ltd. This software is licensed for  */
/* use with Cadence processor cores only and must not be used for any other */
/* processors and platforms. The license to use these sources was given to  */
/* Cadence, Inc. under Terms and Condition of a Software License Agreement  */
/* between Cadence, Inc. and IntegrIT, Ltd.                                 */
/* ------------------------------------------------------------------------ */
/*          Copyright (C) 2009-2016 IntegrIT, Limited.                      */
/*                      All Rights Reserved.                                */
/* ------------------------------------------------------------------------ */

#include "NatureDSP_types.h"
#include "common.h"

#include "fft_fp_tw.h"

/*  Twiddles factors for float point FFT/IFFT cfftfN, cifftfN.
    Generated by matlab script make_cfft_twd(): 
    
function make_cfft_twd(N, fname)
v = 4;
if( nargin()==0 )
    fid = fopen('cfft_tw_header.txt', 'rt');
    
    if fid==0
        hdr_txt=''; 
    else
        hdr_txt = fread(fid, inf, 'uint8=>char');
        fclose(fid); 
        
    end
    for log2N = 4:15
        N = 2^log2N; 
        name = sprintf('cfftf%d_twd', N); 
        fname = strcat(name, '_bbe32.c'); 
        fid = fopen(fname, 'wt'); 
        if ~isempty(hdr_txt)
            fprintf(fid, '%s', hdr_txt);             
        end
        all_twd = cfft_twd(N, v); 
        print_twd(all_twd, name, fid);
        fclose(fid);
    end
else
    all_twd = cfft_twd(N, v); 
    print_twd(all_twd, fname, 1);
end

function all_twd = cfft_twd(N, v)
    all_twd = {}; 
    tw = zeros( N*3/4, 1); 
    if v~=4
        error('v~=4');
    end
    
    for j=0: N/(4*v)-1
        for i=0:v-1
            k = j*v + i; 
            tw(1 + i + j * 3 * v + 0 * v) = exp( -2*1j* pi*1 / N*k);
            tw(1 + i + j * 3 * v + 1 * v) = exp( -2*1j* pi*2 / N*k);
            tw(1 + i + j * 3 * v + 2 * v) = exp( -2*1j* pi*3 / N*k);
        end
    end    
    all_twd{end+1} = tw; 
    N = N/4;

    while( N > 8 )

        tw = zeros( N*3/4, 1); 
        if(v>1)
            v = v/4;
        end
            
        for j=0: N/(4*v)-1
            for i=0:v-1
                k = j*v + i; 
                tw(1 + i + j * 3 * v + 0 * v) = exp( -2*1j* pi*1 / N*k);
                tw(1 + i + j * 3 * v + 1 * v) = exp( -2*1j* pi*2 / N*k);
                tw(1 + i + j * 3 * v + 2 * v) = exp( -2*1j* pi*3 / N*k);
            end
        end      
        all_twd{end+1} = tw; 
        N = N/4;
    end
	
	
function print_twd(all_twd, name, fid)

for i=1:length(all_twd)
    t = all_twd{i}; 
    L = length(t); 
    tmp =  reshape( [real(t), imag(t)].', 2*L, 1 ) ; 
    s = num2hex(single(tmp)); 
    fprintf(2, 'extern const union ufloat32uint32 '); 
    fprintf(2, '%s%d[%d];\n', name, i, 2*L); 
   
    fprintf(fid, '\nALIGN(32) const union ufloat32uint32 '); 
    fprintf(fid, '%s%d[%d] = \n{\n', name, i, 2*L); 
    for k=1:2*L
        fprintf(fid, '  { 0x%s },', s(k, :)); 
        if(mod(k, 4)==0)
            fprintf(fid, '\n');     
        end            
    end
    fprintf(fid, '};\n'); 

end
*/


ALIGN(32) const union ufloat32uint32 rfftf2048_twd1[1024] = 
{
  { 0x00000000 },  { 0xbf000000 },  { 0xbac90fc6 },  { 0xbeffffb1 },
  { 0xbb490f88 },  { 0xbefffec4 },  { 0xbb96cb58 },  { 0xbefffd39 },
  { 0xbbc90e90 },  { 0xbefffb11 },  { 0xbbfb514b },  { 0xbefff84a },
  { 0xbc16c9b6 },  { 0xbefff4e6 },  { 0xbc2fea69 },  { 0xbefff0e3 },
  { 0xbc490ab0 },  { 0xbeffec43 },  { 0xbc622a7a },  { 0xbeffe705 },
  { 0xbc7b49ba },  { 0xbeffe129 },  { 0xbc8a342f },  { 0xbeffdaaf },
  { 0xbc96c32c },  { 0xbeffd397 },  { 0xbca351cb },  { 0xbeffcbe2 },
  { 0xbcafe007 },  { 0xbeffc38f },  { 0xbcbc6dd5 },  { 0xbeffba9e },
  { 0xbcc8fb30 },  { 0xbeffb10f },  { 0xbcd5880e },  { 0xbeffa6e3 },
  { 0xbce21469 },  { 0xbeff9c18 },  { 0xbceea038 },  { 0xbeff90b1 },
  { 0xbcfb2b74 },  { 0xbeff84ab },  { 0xbd03db0a },  { 0xbeff7808 },
  { 0xbd0a200a },  { 0xbeff6ac7 },  { 0xbd1064b4 },  { 0xbeff5ce9 },
  { 0xbd16a905 },  { 0xbeff4e6d },  { 0xbd1cecf9 },  { 0xbeff3f54 },
  { 0xbd23308c },  { 0xbeff2f9d },  { 0xbd2973ba },  { 0xbeff1f49 },
  { 0xbd2fb680 },  { 0xbeff0e58 },  { 0xbd35f8da },  { 0xbefefcc9 },
  { 0xbd3c3ac3 },  { 0xbefeea9d },  { 0xbd427c39 },  { 0xbefed7d4 },
  { 0xbd48bd36 },  { 0xbefec46d },  { 0xbd4efdb7 },  { 0xbefeb069 },
  { 0xbd553db9 },  { 0xbefe9bc9 },  { 0xbd5b7d37 },  { 0xbefe868b },
  { 0xbd61bc2e },  { 0xbefe70b0 },  { 0xbd67fa9a },  { 0xbefe5a38 },
  { 0xbd6e3876 },  { 0xbefe4323 },  { 0xbd7475c0 },  { 0xbefe2b72 },
  { 0xbd7ab273 },  { 0xbefe1324 },  { 0xbd807745 },  { 0xbefdfa38 },
  { 0xbd839502 },  { 0xbefde0b1 },  { 0xbd86b26e },  { 0xbefdc68c },
  { 0xbd89cf86 },  { 0xbefdabcc },  { 0xbd8cec4a },  { 0xbefd906e },
  { 0xbd9008b7 },  { 0xbefd7474 },  { 0xbd9324ca },  { 0xbefd57de },
  { 0xbd964083 },  { 0xbefd3aac },  { 0xbd995be0 },  { 0xbefd1cdd },
  { 0xbd9c76de },  { 0xbefcfe73 },  { 0xbd9f917b },  { 0xbefcdf6c },
  { 0xbda2abb6 },  { 0xbefcbfc9 },  { 0xbda5c58c },  { 0xbefc9f8a },
  { 0xbda8defc },  { 0xbefc7eb0 },  { 0xbdabf804 },  { 0xbefc5d3a },
  { 0xbdaf10a2 },  { 0xbefc3b28 },  { 0xbdb228d4 },  { 0xbefc187a },
  { 0xbdb54098 },  { 0xbefbf531 },  { 0xbdb857ec },  { 0xbefbd14d },
  { 0xbdbb6ecf },  { 0xbefbaccd },  { 0xbdbe853e },  { 0xbefb87b2 },
  { 0xbdc19b37 },  { 0xbefb61fc },  { 0xbdc4b0b9 },  { 0xbefb3bab },
  { 0xbdc7c5c2 },  { 0xbefb14be },  { 0xbdcada4f },  { 0xbefaed37 },
  { 0xbdcdee60 },  { 0xbefac516 },  { 0xbdd101f1 },  { 0xbefa9c59 },
  { 0xbdd41501 },  { 0xbefa7302 },  { 0xbdd7278f },  { 0xbefa4910 },
  { 0xbdda3997 },  { 0xbefa1e84 },  { 0xbddd4b1a },  { 0xbef9f35e },
  { 0xbde05c13 },  { 0xbef9c79d },  { 0xbde36c83 },  { 0xbef99b43 },
  { 0xbde67c66 },  { 0xbef96e4e },  { 0xbde98bba },  { 0xbef940c0 },
  { 0xbdec9a7f },  { 0xbef91298 },  { 0xbdefa8b2 },  { 0xbef8e3d6 },
  { 0xbdf2b651 },  { 0xbef8b47b },  { 0xbdf5c35a },  { 0xbef88486 },
  { 0xbdf8cfcc },  { 0xbef853f8 },  { 0xbdfbdba4 },  { 0xbef822d1 },
  { 0xbdfee6e1 },  { 0xbef7f110 },  { 0xbe00f8c0 },  { 0xbef7beb7 },
  { 0xbe027dc0 },  { 0xbef78bc5 },  { 0xbe040270 },  { 0xbef7583a },
  { 0xbe0586ce },  { 0xbef72417 },  { 0xbe070ada },  { 0xbef6ef5b },
  { 0xbe088e93 },  { 0xbef6ba07 },  { 0xbe0a11f7 },  { 0xbef6841b },
  { 0xbe0b9507 },  { 0xbef64d97 },  { 0xbe0d17c0 },  { 0xbef6167a },
  { 0xbe0e9a22 },  { 0xbef5dec6 },  { 0xbe101c2c },  { 0xbef5a67b },
  { 0xbe119ddd },  { 0xbef56d97 },  { 0xbe131f35 },  { 0xbef5341d },
  { 0xbe14a031 },  { 0xbef4fa0b },  { 0xbe1620d2 },  { 0xbef4bf62 },
  { 0xbe17a117 },  { 0xbef48422 },  { 0xbe1920fe },  { 0xbef4484b },
  { 0xbe1aa086 },  { 0xbef40bdd },  { 0xbe1c1faf },  { 0xbef3ced9 },
  { 0xbe1d9e78 },  { 0xbef3913f },  { 0xbe1f1cdf },  { 0xbef3530e },
  { 0xbe209ae5 },  { 0xbef31447 },  { 0xbe221887 },  { 0xbef2d4eb },
  { 0xbe2395c5 },  { 0xbef294f8 },  { 0xbe25129f },  { 0xbef25470 },
  { 0xbe268f12 },  { 0xbef21352 },  { 0xbe280b1f },  { 0xbef1d19f },
  { 0xbe2986c4 },  { 0xbef18f57 },  { 0xbe2b0201 },  { 0xbef14c7a },
  { 0xbe2c7cd4 },  { 0xbef10908 },  { 0xbe2df73c },  { 0xbef0c501 },
  { 0xbe2f713a },  { 0xbef08066 },  { 0xbe30eacb },  { 0xbef03b37 },
  { 0xbe3263ef },  { 0xbeeff573 },  { 0xbe33dca5 },  { 0xbeefaf1b },
  { 0xbe3554ec },  { 0xbeef6830 },  { 0xbe36ccc3 },  { 0xbeef20b0 },
  { 0xbe38442a },  { 0xbeeed89e },  { 0xbe39bb1e },  { 0xbeee8ff8 },
  { 0xbe3b31a0 },  { 0xbeee46be },  { 0xbe3ca7af },  { 0xbeedfcf2 },
  { 0xbe3e1d4a },  { 0xbeedb293 },  { 0xbe3f926f },  { 0xbeed67a1 },
  { 0xbe41071e },  { 0xbeed1c1d },  { 0xbe427b55 },  { 0xbeecd007 },
  { 0xbe43ef15 },  { 0xbeec835e },  { 0xbe45625c },  { 0xbeec3624 },
  { 0xbe46d529 },  { 0xbeebe858 },  { 0xbe48477c },  { 0xbeeb99fb },
  { 0xbe49b953 },  { 0xbeeb4b0c },  { 0xbe4b2aae },  { 0xbeeafb8c },
  { 0xbe4c9b8b },  { 0xbeeaab7b },  { 0xbe4e0bea },  { 0xbeea5ad9 },
  { 0xbe4f7bca },  { 0xbeea09a7 },  { 0xbe50eb2a },  { 0xbee9b7e4 },
  { 0xbe525a09 },  { 0xbee96591 },  { 0xbe53c867 },  { 0xbee912ae },
  { 0xbe553641 },  { 0xbee8bf3c },  { 0xbe56a399 },  { 0xbee86b39 },
  { 0xbe58106b },  { 0xbee816a8 },  { 0xbe597cb9 },  { 0xbee7c187 },
  { 0xbe5ae880 },  { 0xbee76bd8 },  { 0xbe5c53c1 },  { 0xbee71599 },
  { 0xbe5dbe79 },  { 0xbee6becc },  { 0xbe5f28a9 },  { 0xbee66771 },
  { 0xbe60924f },  { 0xbee60f88 },  { 0xbe61fb6a },  { 0xbee5b710 },
  { 0xbe6363fa },  { 0xbee55e0b },  { 0xbe64cbfe },  { 0xbee50479 },
  { 0xbe663375 },  { 0xbee4aa59 },  { 0xbe679a5d },  { 0xbee44fac },
  { 0xbe6900b7 },  { 0xbee3f473 },  { 0xbe6a6681 },  { 0xbee398ac },
  { 0xbe6bcbbb },  { 0xbee33c5a },  { 0xbe6d3063 },  { 0xbee2df7b },
  { 0xbe6e9479 },  { 0xbee28210 },  { 0xbe6ff7fb },  { 0xbee2241a },
  { 0xbe715aea },  { 0xbee1c598 },  { 0xbe72bd43 },  { 0xbee1668a },
  { 0xbe741f07 },  { 0xbee106f2 },  { 0xbe758035 },  { 0xbee0a6cf },
  { 0xbe76e0cb },  { 0xbee04621 },  { 0xbe7840c8 },  { 0xbedfe4e9 },
  { 0xbe79a02d },  { 0xbedf8327 },  { 0xbe7afef7 },  { 0xbedf20db },
  { 0xbe7c5d27 },  { 0xbedebe05 },  { 0xbe7dbabb },  { 0xbede5aa6 },
  { 0xbe7f17b2 },  { 0xbeddf6be },  { 0xbe803a06 },  { 0xbedd924d },
  { 0xbe80e7e4 },  { 0xbedd2d53 },  { 0xbe819573 },  { 0xbedcc7d1 },
  { 0xbe8242b1 },  { 0xbedc61c7 },  { 0xbe82ef9f },  { 0xbedbfb34 },
  { 0xbe839c3d },  { 0xbedb941a },  { 0xbe844889 },  { 0xbedb2c79 },
  { 0xbe84f484 },  { 0xbedac450 },  { 0xbe85a02c },  { 0xbeda5ba0 },
  { 0xbe864b82 },  { 0xbed9f26a },  { 0xbe86f686 },  { 0xbed988ad },
  { 0xbe87a136 },  { 0xbed91e6a },  { 0xbe884b92 },  { 0xbed8b3a1 },
  { 0xbe88f59b },  { 0xbed84853 },  { 0xbe899f4e },  { 0xbed7dc7f },
  { 0xbe8a48ad },  { 0xbed77026 },  { 0xbe8af1b7 },  { 0xbed70348 },
  { 0xbe8b9a6b },  { 0xbed695e5 },  { 0xbe8c42c9 },  { 0xbed627fe },
  { 0xbe8cead0 },  { 0xbed5b993 },  { 0xbe8d9281 },  { 0xbed54aa4 },
  { 0xbe8e39da },  { 0xbed4db31 },  { 0xbe8ee0db },  { 0xbed46b3b },
  { 0xbe8f8784 },  { 0xbed3fac3 },  { 0xbe902dd5 },  { 0xbed389c7 },
  { 0xbe90d3cd },  { 0xbed31849 },  { 0xbe91796b },  { 0xbed2a649 },
  { 0xbe921eb0 },  { 0xbed233c6 },  { 0xbe92c39a },  { 0xbed1c0c2 },
  { 0xbe93682a },  { 0xbed14d3d },  { 0xbe940c5f },  { 0xbed0d937 },
  { 0xbe94b039 },  { 0xbed064af },  { 0xbe9553b7 },  { 0xbecfefa8 },
  { 0xbe95f6d9 },  { 0xbecf7a1f },  { 0xbe96999f },  { 0xbecf0417 },
  { 0xbe973c07 },  { 0xbece8d90 },  { 0xbe97de12 },  { 0xbece1689 },
  { 0xbe987fc0 },  { 0xbecd9f02 },  { 0xbe99210f },  { 0xbecd26fd },
  { 0xbe99c200 },  { 0xbeccae79 },  { 0xbe9a6293 },  { 0xbecc3578 },
  { 0xbe9b02c6 },  { 0xbecbbbf8 },  { 0xbe9ba299 },  { 0xbecb41fa },
  { 0xbe9c420c },  { 0xbecac77f },  { 0xbe9ce11f },  { 0xbeca4c87 },
  { 0xbe9d7fd1 },  { 0xbec9d112 },  { 0xbe9e1e22 },  { 0xbec95521 },
  { 0xbe9ebc12 },  { 0xbec8d8b3 },  { 0xbe9f599f },  { 0xbec85bca },
  { 0xbe9ff6cb },  { 0xbec7de65 },  { 0xbea09393 },  { 0xbec76085 },
  { 0xbea12ff9 },  { 0xbec6e22a },  { 0xbea1cbfb },  { 0xbec66354 },
  { 0xbea26799 },  { 0xbec5e403 },  { 0xbea302d3 },  { 0xbec56439 },
  { 0xbea39da9 },  { 0xbec4e3f5 },  { 0xbea4381a },  { 0xbec46337 },
  { 0xbea4d225 },  { 0xbec3e200 },  { 0xbea56bcb },  { 0xbec36051 },
  { 0xbea6050a },  { 0xbec2de29 },  { 0xbea69de3 },  { 0xbec25b89 },
  { 0xbea73656 },  { 0xbec1d870 },  { 0xbea7ce61 },  { 0xbec154e1 },
  { 0xbea86605 },  { 0xbec0d0da },  { 0xbea8fd41 },  { 0xbec04c5c },
  { 0xbea99415 },  { 0xbebfc767 },  { 0xbeaa2a80 },  { 0xbebf41fc },
  { 0xbeaac082 },  { 0xbebebc1b },  { 0xbeab561b },  { 0xbebe35c5 },
  { 0xbeabeb4a },  { 0xbebdaef9 },  { 0xbeac800f },  { 0xbebd27b8 },
  { 0xbead1469 },  { 0xbebca003 },  { 0xbeada859 },  { 0xbebc17d9 },
  { 0xbeae3bde },  { 0xbebb8f3b },  { 0xbeaecef7 },  { 0xbebb0629 },
  { 0xbeaf61a5 },  { 0xbeba7ca4 },  { 0xbeaff3e6 },  { 0xbeb9f2ac },
  { 0xbeb085bb },  { 0xbeb96842 },  { 0xbeb11722 },  { 0xbeb8dd65 },
  { 0xbeb1a81d },  { 0xbeb85216 },  { 0xbeb238aa },  { 0xbeb7c655 },
  { 0xbeb2c8c9 },  { 0xbeb73a23 },  { 0xbeb3587a },  { 0xbeb6ad7f },
  { 0xbeb3e7bc },  { 0xbeb6206c },  { 0xbeb4768f },  { 0xbeb592e7 },
  { 0xbeb504f3 },  { 0xbeb504f3 },  { 0xbeb592e7 },  { 0xbeb4768f },
  { 0xbeb6206c },  { 0xbeb3e7bc },  { 0xbeb6ad7f },  { 0xbeb3587a },
  { 0xbeb73a23 },  { 0xbeb2c8c9 },  { 0xbeb7c655 },  { 0xbeb238aa },
  { 0xbeb85216 },  { 0xbeb1a81d },  { 0xbeb8dd65 },  { 0xbeb11722 },
  { 0xbeb96842 },  { 0xbeb085bb },  { 0xbeb9f2ac },  { 0xbeaff3e6 },
  { 0xbeba7ca4 },  { 0xbeaf61a5 },  { 0xbebb0629 },  { 0xbeaecef7 },
  { 0xbebb8f3b },  { 0xbeae3bde },  { 0xbebc17d9 },  { 0xbeada859 },
  { 0xbebca003 },  { 0xbead1469 },  { 0xbebd27b8 },  { 0xbeac800f },
  { 0xbebdaef9 },  { 0xbeabeb4a },  { 0xbebe35c5 },  { 0xbeab561b },
  { 0xbebebc1b },  { 0xbeaac082 },  { 0xbebf41fc },  { 0xbeaa2a80 },
  { 0xbebfc767 },  { 0xbea99415 },  { 0xbec04c5c },  { 0xbea8fd41 },
  { 0xbec0d0da },  { 0xbea86605 },  { 0xbec154e1 },  { 0xbea7ce61 },
  { 0xbec1d870 },  { 0xbea73656 },  { 0xbec25b89 },  { 0xbea69de3 },
  { 0xbec2de29 },  { 0xbea6050a },  { 0xbec36051 },  { 0xbea56bcb },
  { 0xbec3e200 },  { 0xbea4d225 },  { 0xbec46337 },  { 0xbea4381a },
  { 0xbec4e3f5 },  { 0xbea39da9 },  { 0xbec56439 },  { 0xbea302d3 },
  { 0xbec5e403 },  { 0xbea26799 },  { 0xbec66354 },  { 0xbea1cbfb },
  { 0xbec6e22a },  { 0xbea12ff9 },  { 0xbec76085 },  { 0xbea09393 },
  { 0xbec7de65 },  { 0xbe9ff6cb },  { 0xbec85bca },  { 0xbe9f599f },
  { 0xbec8d8b3 },  { 0xbe9ebc12 },  { 0xbec95521 },  { 0xbe9e1e22 },
  { 0xbec9d112 },  { 0xbe9d7fd1 },  { 0xbeca4c87 },  { 0xbe9ce11f },
  { 0xbecac77f },  { 0xbe9c420c },  { 0xbecb41fa },  { 0xbe9ba299 },
  { 0xbecbbbf8 },  { 0xbe9b02c6 },  { 0xbecc3578 },  { 0xbe9a6293 },
  { 0xbeccae79 },  { 0xbe99c200 },  { 0xbecd26fd },  { 0xbe99210f },
  { 0xbecd9f02 },  { 0xbe987fc0 },  { 0xbece1689 },  { 0xbe97de12 },
  { 0xbece8d90 },  { 0xbe973c07 },  { 0xbecf0417 },  { 0xbe96999f },
  { 0xbecf7a1f },  { 0xbe95f6d9 },  { 0xbecfefa8 },  { 0xbe9553b7 },
  { 0xbed064af },  { 0xbe94b039 },  { 0xbed0d937 },  { 0xbe940c5f },
  { 0xbed14d3d },  { 0xbe93682a },  { 0xbed1c0c2 },  { 0xbe92c39a },
  { 0xbed233c6 },  { 0xbe921eb0 },  { 0xbed2a649 },  { 0xbe91796b },
  { 0xbed31849 },  { 0xbe90d3cd },  { 0xbed389c7 },  { 0xbe902dd5 },
  { 0xbed3fac3 },  { 0xbe8f8784 },  { 0xbed46b3b },  { 0xbe8ee0db },
  { 0xbed4db31 },  { 0xbe8e39da },  { 0xbed54aa4 },  { 0xbe8d9281 },
  { 0xbed5b993 },  { 0xbe8cead0 },  { 0xbed627fe },  { 0xbe8c42c9 },
  { 0xbed695e5 },  { 0xbe8b9a6b },  { 0xbed70348 },  { 0xbe8af1b7 },
  { 0xbed77026 },  { 0xbe8a48ad },  { 0xbed7dc7f },  { 0xbe899f4e },
  { 0xbed84853 },  { 0xbe88f59b },  { 0xbed8b3a1 },  { 0xbe884b92 },
  { 0xbed91e6a },  { 0xbe87a136 },  { 0xbed988ad },  { 0xbe86f686 },
  { 0xbed9f26a },  { 0xbe864b82 },  { 0xbeda5ba0 },  { 0xbe85a02c },
  { 0xbedac450 },  { 0xbe84f484 },  { 0xbedb2c79 },  { 0xbe844889 },
  { 0xbedb941a },  { 0xbe839c3d },  { 0xbedbfb34 },  { 0xbe82ef9f },
  { 0xbedc61c7 },  { 0xbe8242b1 },  { 0xbedcc7d1 },  { 0xbe819573 },
  { 0xbedd2d53 },  { 0xbe80e7e4 },  { 0xbedd924d },  { 0xbe803a06 },
  { 0xbeddf6be },  { 0xbe7f17b2 },  { 0xbede5aa6 },  { 0xbe7dbabb },
  { 0xbedebe05 },  { 0xbe7c5d27 },  { 0xbedf20db },  { 0xbe7afef7 },
  { 0xbedf8327 },  { 0xbe79a02d },  { 0xbedfe4e9 },  { 0xbe7840c8 },
  { 0xbee04621 },  { 0xbe76e0cb },  { 0xbee0a6cf },  { 0xbe758035 },
  { 0xbee106f2 },  { 0xbe741f07 },  { 0xbee1668a },  { 0xbe72bd43 },
  { 0xbee1c598 },  { 0xbe715aea },  { 0xbee2241a },  { 0xbe6ff7fb },
  { 0xbee28210 },  { 0xbe6e9479 },  { 0xbee2df7b },  { 0xbe6d3063 },
  { 0xbee33c5a },  { 0xbe6bcbbb },  { 0xbee398ac },  { 0xbe6a6681 },
  { 0xbee3f473 },  { 0xbe6900b7 },  { 0xbee44fac },  { 0xbe679a5d },
  { 0xbee4aa59 },  { 0xbe663375 },  { 0xbee50479 },  { 0xbe64cbfe },
  { 0xbee55e0b },  { 0xbe6363fa },  { 0xbee5b710 },  { 0xbe61fb6a },
  { 0xbee60f88 },  { 0xbe60924f },  { 0xbee66771 },  { 0xbe5f28a9 },
  { 0xbee6becc },  { 0xbe5dbe79 },  { 0xbee71599 },  { 0xbe5c53c1 },
  { 0xbee76bd8 },  { 0xbe5ae880 },  { 0xbee7c187 },  { 0xbe597cb9 },
  { 0xbee816a8 },  { 0xbe58106b },  { 0xbee86b39 },  { 0xbe56a399 },
  { 0xbee8bf3c },  { 0xbe553641 },  { 0xbee912ae },  { 0xbe53c867 },
  { 0xbee96591 },  { 0xbe525a09 },  { 0xbee9b7e4 },  { 0xbe50eb2a },
  { 0xbeea09a7 },  { 0xbe4f7bca },  { 0xbeea5ad9 },  { 0xbe4e0bea },
  { 0xbeeaab7b },  { 0xbe4c9b8b },  { 0xbeeafb8c },  { 0xbe4b2aae },
  { 0xbeeb4b0c },  { 0xbe49b953 },  { 0xbeeb99fb },  { 0xbe48477c },
  { 0xbeebe858 },  { 0xbe46d529 },  { 0xbeec3624 },  { 0xbe45625c },
  { 0xbeec835e },  { 0xbe43ef15 },  { 0xbeecd007 },  { 0xbe427b55 },
  { 0xbeed1c1d },  { 0xbe41071e },  { 0xbeed67a1 },  { 0xbe3f926f },
  { 0xbeedb293 },  { 0xbe3e1d4a },  { 0xbeedfcf2 },  { 0xbe3ca7af },
  { 0xbeee46be },  { 0xbe3b31a0 },  { 0xbeee8ff8 },  { 0xbe39bb1e },
  { 0xbeeed89e },  { 0xbe38442a },  { 0xbeef20b0 },  { 0xbe36ccc3 },
  { 0xbeef6830 },  { 0xbe3554ec },  { 0xbeefaf1b },  { 0xbe33dca5 },
  { 0xbeeff573 },  { 0xbe3263ef },  { 0xbef03b37 },  { 0xbe30eacb },
  { 0xbef08066 },  { 0xbe2f713a },  { 0xbef0c501 },  { 0xbe2df73c },
  { 0xbef10908 },  { 0xbe2c7cd4 },  { 0xbef14c7a },  { 0xbe2b0201 },
  { 0xbef18f57 },  { 0xbe2986c4 },  { 0xbef1d19f },  { 0xbe280b1f },
  { 0xbef21352 },  { 0xbe268f12 },  { 0xbef25470 },  { 0xbe25129f },
  { 0xbef294f8 },  { 0xbe2395c5 },  { 0xbef2d4eb },  { 0xbe221887 },
  { 0xbef31447 },  { 0xbe209ae5 },  { 0xbef3530e },  { 0xbe1f1cdf },
  { 0xbef3913f },  { 0xbe1d9e78 },  { 0xbef3ced9 },  { 0xbe1c1faf },
  { 0xbef40bdd },  { 0xbe1aa086 },  { 0xbef4484b },  { 0xbe1920fe },
  { 0xbef48422 },  { 0xbe17a117 },  { 0xbef4bf62 },  { 0xbe1620d2 },
  { 0xbef4fa0b },  { 0xbe14a031 },  { 0xbef5341d },  { 0xbe131f35 },
  { 0xbef56d97 },  { 0xbe119ddd },  { 0xbef5a67b },  { 0xbe101c2c },
  { 0xbef5dec6 },  { 0xbe0e9a22 },  { 0xbef6167a },  { 0xbe0d17c0 },
  { 0xbef64d97 },  { 0xbe0b9507 },  { 0xbef6841b },  { 0xbe0a11f7 },
  { 0xbef6ba07 },  { 0xbe088e93 },  { 0xbef6ef5b },  { 0xbe070ada },
  { 0xbef72417 },  { 0xbe0586ce },  { 0xbef7583a },  { 0xbe040270 },
  { 0xbef78bc5 },  { 0xbe027dc0 },  { 0xbef7beb7 },  { 0xbe00f8c0 },
  { 0xbef7f110 },  { 0xbdfee6e1 },  { 0xbef822d1 },  { 0xbdfbdba4 },
  { 0xbef853f8 },  { 0xbdf8cfcc },  { 0xbef88486 },  { 0xbdf5c35a },
  { 0xbef8b47b },  { 0xbdf2b651 },  { 0xbef8e3d6 },  { 0xbdefa8b2 },
  { 0xbef91298 },  { 0xbdec9a7f },  { 0xbef940c0 },  { 0xbde98bba },
  { 0xbef96e4e },  { 0xbde67c66 },  { 0xbef99b43 },  { 0xbde36c83 },
  { 0xbef9c79d },  { 0xbde05c13 },  { 0xbef9f35e },  { 0xbddd4b1a },
  { 0xbefa1e84 },  { 0xbdda3997 },  { 0xbefa4910 },  { 0xbdd7278f },
  { 0xbefa7302 },  { 0xbdd41501 },  { 0xbefa9c59 },  { 0xbdd101f1 },
  { 0xbefac516 },  { 0xbdcdee60 },  { 0xbefaed37 },  { 0xbdcada4f },
  { 0xbefb14be },  { 0xbdc7c5c2 },  { 0xbefb3bab },  { 0xbdc4b0b9 },
  { 0xbefb61fc },  { 0xbdc19b37 },  { 0xbefb87b2 },  { 0xbdbe853e },
  { 0xbefbaccd },  { 0xbdbb6ecf },  { 0xbefbd14d },  { 0xbdb857ec },
  { 0xbefbf531 },  { 0xbdb54098 },  { 0xbefc187a },  { 0xbdb228d4 },
  { 0xbefc3b28 },  { 0xbdaf10a2 },  { 0xbefc5d3a },  { 0xbdabf804 },
  { 0xbefc7eb0 },  { 0xbda8defc },  { 0xbefc9f8a },  { 0xbda5c58c },
  { 0xbefcbfc9 },  { 0xbda2abb6 },  { 0xbefcdf6c },  { 0xbd9f917b },
  { 0xbefcfe73 },  { 0xbd9c76de },  { 0xbefd1cdd },  { 0xbd995be0 },
  { 0xbefd3aac },  { 0xbd964083 },  { 0xbefd57de },  { 0xbd9324ca },
  { 0xbefd7474 },  { 0xbd9008b7 },  { 0xbefd906e },  { 0xbd8cec4a },
  { 0xbefdabcc },  { 0xbd89cf86 },  { 0xbefdc68c },  { 0xbd86b26e },
  { 0xbefde0b1 },  { 0xbd839502 },  { 0xbefdfa38 },  { 0xbd807745 },
  { 0xbefe1324 },  { 0xbd7ab273 },  { 0xbefe2b72 },  { 0xbd7475c0 },
  { 0xbefe4323 },  { 0xbd6e3876 },  { 0xbefe5a38 },  { 0xbd67fa9a },
  { 0xbefe70b0 },  { 0xbd61bc2e },  { 0xbefe868b },  { 0xbd5b7d37 },
  { 0xbefe9bc9 },  { 0xbd553db9 },  { 0xbefeb069 },  { 0xbd4efdb7 },
  { 0xbefec46d },  { 0xbd48bd36 },  { 0xbefed7d4 },  { 0xbd427c39 },
  { 0xbefeea9d },  { 0xbd3c3ac3 },  { 0xbefefcc9 },  { 0xbd35f8da },
  { 0xbeff0e58 },  { 0xbd2fb680 },  { 0xbeff1f49 },  { 0xbd2973ba },
  { 0xbeff2f9d },  { 0xbd23308c },  { 0xbeff3f54 },  { 0xbd1cecf9 },
  { 0xbeff4e6d },  { 0xbd16a905 },  { 0xbeff5ce9 },  { 0xbd1064b4 },
  { 0xbeff6ac7 },  { 0xbd0a200a },  { 0xbeff7808 },  { 0xbd03db0a },
  { 0xbeff84ab },  { 0xbcfb2b74 },  { 0xbeff90b1 },  { 0xbceea038 },
  { 0xbeff9c18 },  { 0xbce21469 },  { 0xbeffa6e3 },  { 0xbcd5880e },
  { 0xbeffb10f },  { 0xbcc8fb30 },  { 0xbeffba9e },  { 0xbcbc6dd5 },
  { 0xbeffc38f },  { 0xbcafe007 },  { 0xbeffcbe2 },  { 0xbca351cb },
  { 0xbeffd397 },  { 0xbc96c32c },  { 0xbeffdaaf },  { 0xbc8a342f },
  { 0xbeffe129 },  { 0xbc7b49ba },  { 0xbeffe705 },  { 0xbc622a7a },
  { 0xbeffec43 },  { 0xbc490ab0 },  { 0xbefff0e3 },  { 0xbc2fea69 },
  { 0xbefff4e6 },  { 0xbc16c9b6 },  { 0xbefff84a },  { 0xbbfb514b },
  { 0xbefffb11 },  { 0xbbc90e90 },  { 0xbefffd39 },  { 0xbb96cb58 },
  { 0xbefffec4 },  { 0xbb490f88 },  { 0xbeffffb1 },  { 0xbac90fc6 },
};
