/* ------------------------------------------------------------------------ */
/* Copyright (c) 2016 by Cadence Design Systems, Inc. ALL RIGHTS RESERVED.  */
/* These coded instructions, statements, and computer programs ('Cadence    */
/* Libraries') are the copyrighted works of Cadence Design Systems Inc.     */
/* Cadence IP is licensed for use with Cadence processor cores only and     */
/* must not be used for any other processors and platforms. Your use of the */
/* Cadence Libraries is subject to the terms of the license agreement you   */
/* have entered into with Cadence Design Systems, or a sublicense granted   */
/* to you by a direct Cadence licensee.                                     */
/* ------------------------------------------------------------------------ */
/*  IntegrIT, Ltd.   www.integrIT.com, info@integrIT.com                    */
/*                                                                          */
/* NatureDSP_Baseband Library                                               */
/*                                                                          */
/* This library contains copyrighted materials, trade secrets and other     */
/* proprietary information of IntegrIT, Ltd. This software is licensed for  */
/* use with Cadence processor cores only and must not be used for any other */
/* processors and platforms. The license to use these sources was given to  */
/* Cadence, Inc. under Terms and Condition of a Software License Agreement  */
/* between Cadence, Inc. and IntegrIT, Ltd.                                 */
/* ------------------------------------------------------------------------ */
/*          Copyright (C) 2009-2016 IntegrIT, Limited.                      */
/*                      All Rights Reserved.                                */
/* ------------------------------------------------------------------------ */

#include "NatureDSP_types.h"
#include "common.h"

#include "fft_fp_tw.h"

/*  Twiddles factors for float point FFT/IFFT cfftfN, cifftfN.
    Generated by matlab script make_cfft_twd(): 
    
function make_cfft_twd(N, fname)
v = 4;
if( nargin()==0 )
    fid = fopen('cfft_tw_header.txt', 'rt');
    
    if fid==0
        hdr_txt=''; 
    else
        hdr_txt = fread(fid, inf, 'uint8=>char');
        fclose(fid); 
        
    end
    for log2N = 4:15
        N = 2^log2N; 
        name = sprintf('cfftf%d_twd', N); 
        fname = strcat(name, '_bbe32.c'); 
        fid = fopen(fname, 'wt'); 
        if ~isempty(hdr_txt)
            fprintf(fid, '%s', hdr_txt);             
        end
        all_twd = cfft_twd(N, v); 
        print_twd(all_twd, name, fid);
        fclose(fid);
    end
else
    all_twd = cfft_twd(N, v); 
    print_twd(all_twd, fname, 1);
end

function all_twd = cfft_twd(N, v)
    all_twd = {}; 
    tw = zeros( N*3/4, 1); 
    if v~=4
        error('v~=4');
    end
    
    for j=0: N/(4*v)-1
        for i=0:v-1
            k = j*v + i; 
            tw(1 + i + j * 3 * v + 0 * v) = exp( -2*1j* pi*1 / N*k);
            tw(1 + i + j * 3 * v + 1 * v) = exp( -2*1j* pi*2 / N*k);
            tw(1 + i + j * 3 * v + 2 * v) = exp( -2*1j* pi*3 / N*k);
        end
    end    
    all_twd{end+1} = tw; 
    N = N/4;

    while( N > 8 )

        tw = zeros( N*3/4, 1); 
        if(v>1)
            v = v/4;
        end
            
        for j=0: N/(4*v)-1
            for i=0:v-1
                k = j*v + i; 
                tw(1 + i + j * 3 * v + 0 * v) = exp( -2*1j* pi*1 / N*k);
                tw(1 + i + j * 3 * v + 1 * v) = exp( -2*1j* pi*2 / N*k);
                tw(1 + i + j * 3 * v + 2 * v) = exp( -2*1j* pi*3 / N*k);
            end
        end      
        all_twd{end+1} = tw; 
        N = N/4;
    end
	
	
function print_twd(all_twd, name, fid)

for i=1:length(all_twd)
    t = all_twd{i}; 
    L = length(t); 
    tmp =  reshape( [real(t), imag(t)].', 2*L, 1 ) ; 
    s = num2hex(single(tmp)); 
    fprintf(2, 'extern const union ufloat32uint32 '); 
    fprintf(2, '%s%d[%d];\n', name, i, 2*L); 
   
    fprintf(fid, '\nALIGN(32) const union ufloat32uint32 '); 
    fprintf(fid, '%s%d[%d] = \n{\n', name, i, 2*L); 
    for k=1:2*L
        fprintf(fid, '  { 0x%s },', s(k, :)); 
        if(mod(k, 4)==0)
            fprintf(fid, '\n');     
        end            
    end
    fprintf(fid, '};\n'); 

end
*/


ALIGN(32) const union ufloat32uint32 rfftf1024_twd1[512] = 
{
  { 0x00000000 },  { 0xbf000000 },  { 0xbb490f88 },  { 0xbefffec4 },
  { 0xbbc90e90 },  { 0xbefffb11 },  { 0xbc16c9b6 },  { 0xbefff4e6 },
  { 0xbc490ab0 },  { 0xbeffec43 },  { 0xbc7b49ba },  { 0xbeffe129 },
  { 0xbc96c32c },  { 0xbeffd397 },  { 0xbcafe007 },  { 0xbeffc38f },
  { 0xbcc8fb30 },  { 0xbeffb10f },  { 0xbce21469 },  { 0xbeff9c18 },
  { 0xbcfb2b74 },  { 0xbeff84ab },  { 0xbd0a200a },  { 0xbeff6ac7 },
  { 0xbd16a905 },  { 0xbeff4e6d },  { 0xbd23308c },  { 0xbeff2f9d },
  { 0xbd2fb680 },  { 0xbeff0e58 },  { 0xbd3c3ac3 },  { 0xbefeea9d },
  { 0xbd48bd36 },  { 0xbefec46d },  { 0xbd553db9 },  { 0xbefe9bc9 },
  { 0xbd61bc2e },  { 0xbefe70b0 },  { 0xbd6e3876 },  { 0xbefe4323 },
  { 0xbd7ab273 },  { 0xbefe1324 },  { 0xbd839502 },  { 0xbefde0b1 },
  { 0xbd89cf86 },  { 0xbefdabcc },  { 0xbd9008b7 },  { 0xbefd7474 },
  { 0xbd964083 },  { 0xbefd3aac },  { 0xbd9c76de },  { 0xbefcfe73 },
  { 0xbda2abb6 },  { 0xbefcbfc9 },  { 0xbda8defc },  { 0xbefc7eb0 },
  { 0xbdaf10a2 },  { 0xbefc3b28 },  { 0xbdb54098 },  { 0xbefbf531 },
  { 0xbdbb6ecf },  { 0xbefbaccd },  { 0xbdc19b37 },  { 0xbefb61fc },
  { 0xbdc7c5c2 },  { 0xbefb14be },  { 0xbdcdee60 },  { 0xbefac516 },
  { 0xbdd41501 },  { 0xbefa7302 },  { 0xbdda3997 },  { 0xbefa1e84 },
  { 0xbde05c13 },  { 0xbef9c79d },  { 0xbde67c66 },  { 0xbef96e4e },
  { 0xbdec9a7f },  { 0xbef91298 },  { 0xbdf2b651 },  { 0xbef8b47b },
  { 0xbdf8cfcc },  { 0xbef853f8 },  { 0xbdfee6e1 },  { 0xbef7f110 },
  { 0xbe027dc0 },  { 0xbef78bc5 },  { 0xbe0586ce },  { 0xbef72417 },
  { 0xbe088e93 },  { 0xbef6ba07 },  { 0xbe0b9507 },  { 0xbef64d97 },
  { 0xbe0e9a22 },  { 0xbef5dec6 },  { 0xbe119ddd },  { 0xbef56d97 },
  { 0xbe14a031 },  { 0xbef4fa0b },  { 0xbe17a117 },  { 0xbef48422 },
  { 0xbe1aa086 },  { 0xbef40bdd },  { 0xbe1d9e78 },  { 0xbef3913f },
  { 0xbe209ae5 },  { 0xbef31447 },  { 0xbe2395c5 },  { 0xbef294f8 },
  { 0xbe268f12 },  { 0xbef21352 },  { 0xbe2986c4 },  { 0xbef18f57 },
  { 0xbe2c7cd4 },  { 0xbef10908 },  { 0xbe2f713a },  { 0xbef08066 },
  { 0xbe3263ef },  { 0xbeeff573 },  { 0xbe3554ec },  { 0xbeef6830 },
  { 0xbe38442a },  { 0xbeeed89e },  { 0xbe3b31a0 },  { 0xbeee46be },
  { 0xbe3e1d4a },  { 0xbeedb293 },  { 0xbe41071e },  { 0xbeed1c1d },
  { 0xbe43ef15 },  { 0xbeec835e },  { 0xbe46d529 },  { 0xbeebe858 },
  { 0xbe49b953 },  { 0xbeeb4b0c },  { 0xbe4c9b8b },  { 0xbeeaab7b },
  { 0xbe4f7bca },  { 0xbeea09a7 },  { 0xbe525a09 },  { 0xbee96591 },
  { 0xbe553641 },  { 0xbee8bf3c },  { 0xbe58106b },  { 0xbee816a8 },
  { 0xbe5ae880 },  { 0xbee76bd8 },  { 0xbe5dbe79 },  { 0xbee6becc },
  { 0xbe60924f },  { 0xbee60f88 },  { 0xbe6363fa },  { 0xbee55e0b },
  { 0xbe663375 },  { 0xbee4aa59 },  { 0xbe6900b7 },  { 0xbee3f473 },
  { 0xbe6bcbbb },  { 0xbee33c5a },  { 0xbe6e9479 },  { 0xbee28210 },
  { 0xbe715aea },  { 0xbee1c598 },  { 0xbe741f07 },  { 0xbee106f2 },
  { 0xbe76e0cb },  { 0xbee04621 },  { 0xbe79a02d },  { 0xbedf8327 },
  { 0xbe7c5d27 },  { 0xbedebe05 },  { 0xbe7f17b2 },  { 0xbeddf6be },
  { 0xbe80e7e4 },  { 0xbedd2d53 },  { 0xbe8242b1 },  { 0xbedc61c7 },
  { 0xbe839c3d },  { 0xbedb941a },  { 0xbe84f484 },  { 0xbedac450 },
  { 0xbe864b82 },  { 0xbed9f26a },  { 0xbe87a136 },  { 0xbed91e6a },
  { 0xbe88f59b },  { 0xbed84853 },  { 0xbe8a48ad },  { 0xbed77026 },
  { 0xbe8b9a6b },  { 0xbed695e5 },  { 0xbe8cead0 },  { 0xbed5b993 },
  { 0xbe8e39da },  { 0xbed4db31 },  { 0xbe8f8784 },  { 0xbed3fac3 },
  { 0xbe90d3cd },  { 0xbed31849 },  { 0xbe921eb0 },  { 0xbed233c6 },
  { 0xbe93682a },  { 0xbed14d3d },  { 0xbe94b039 },  { 0xbed064af },
  { 0xbe95f6d9 },  { 0xbecf7a1f },  { 0xbe973c07 },  { 0xbece8d90 },
  { 0xbe987fc0 },  { 0xbecd9f02 },  { 0xbe99c200 },  { 0xbeccae79 },
  { 0xbe9b02c6 },  { 0xbecbbbf8 },  { 0xbe9c420c },  { 0xbecac77f },
  { 0xbe9d7fd1 },  { 0xbec9d112 },  { 0xbe9ebc12 },  { 0xbec8d8b3 },
  { 0xbe9ff6cb },  { 0xbec7de65 },  { 0xbea12ff9 },  { 0xbec6e22a },
  { 0xbea26799 },  { 0xbec5e403 },  { 0xbea39da9 },  { 0xbec4e3f5 },
  { 0xbea4d225 },  { 0xbec3e200 },  { 0xbea6050a },  { 0xbec2de29 },
  { 0xbea73656 },  { 0xbec1d870 },  { 0xbea86605 },  { 0xbec0d0da },
  { 0xbea99415 },  { 0xbebfc767 },  { 0xbeaac082 },  { 0xbebebc1b },
  { 0xbeabeb4a },  { 0xbebdaef9 },  { 0xbead1469 },  { 0xbebca003 },
  { 0xbeae3bde },  { 0xbebb8f3b },  { 0xbeaf61a5 },  { 0xbeba7ca4 },
  { 0xbeb085bb },  { 0xbeb96842 },  { 0xbeb1a81d },  { 0xbeb85216 },
  { 0xbeb2c8c9 },  { 0xbeb73a23 },  { 0xbeb3e7bc },  { 0xbeb6206c },
  { 0xbeb504f3 },  { 0xbeb504f3 },  { 0xbeb6206c },  { 0xbeb3e7bc },
  { 0xbeb73a23 },  { 0xbeb2c8c9 },  { 0xbeb85216 },  { 0xbeb1a81d },
  { 0xbeb96842 },  { 0xbeb085bb },  { 0xbeba7ca4 },  { 0xbeaf61a5 },
  { 0xbebb8f3b },  { 0xbeae3bde },  { 0xbebca003 },  { 0xbead1469 },
  { 0xbebdaef9 },  { 0xbeabeb4a },  { 0xbebebc1b },  { 0xbeaac082 },
  { 0xbebfc767 },  { 0xbea99415 },  { 0xbec0d0da },  { 0xbea86605 },
  { 0xbec1d870 },  { 0xbea73656 },  { 0xbec2de29 },  { 0xbea6050a },
  { 0xbec3e200 },  { 0xbea4d225 },  { 0xbec4e3f5 },  { 0xbea39da9 },
  { 0xbec5e403 },  { 0xbea26799 },  { 0xbec6e22a },  { 0xbea12ff9 },
  { 0xbec7de65 },  { 0xbe9ff6cb },  { 0xbec8d8b3 },  { 0xbe9ebc12 },
  { 0xbec9d112 },  { 0xbe9d7fd1 },  { 0xbecac77f },  { 0xbe9c420c },
  { 0xbecbbbf8 },  { 0xbe9b02c6 },  { 0xbeccae79 },  { 0xbe99c200 },
  { 0xbecd9f02 },  { 0xbe987fc0 },  { 0xbece8d90 },  { 0xbe973c07 },
  { 0xbecf7a1f },  { 0xbe95f6d9 },  { 0xbed064af },  { 0xbe94b039 },
  { 0xbed14d3d },  { 0xbe93682a },  { 0xbed233c6 },  { 0xbe921eb0 },
  { 0xbed31849 },  { 0xbe90d3cd },  { 0xbed3fac3 },  { 0xbe8f8784 },
  { 0xbed4db31 },  { 0xbe8e39da },  { 0xbed5b993 },  { 0xbe8cead0 },
  { 0xbed695e5 },  { 0xbe8b9a6b },  { 0xbed77026 },  { 0xbe8a48ad },
  { 0xbed84853 },  { 0xbe88f59b },  { 0xbed91e6a },  { 0xbe87a136 },
  { 0xbed9f26a },  { 0xbe864b82 },  { 0xbedac450 },  { 0xbe84f484 },
  { 0xbedb941a },  { 0xbe839c3d },  { 0xbedc61c7 },  { 0xbe8242b1 },
  { 0xbedd2d53 },  { 0xbe80e7e4 },  { 0xbeddf6be },  { 0xbe7f17b2 },
  { 0xbedebe05 },  { 0xbe7c5d27 },  { 0xbedf8327 },  { 0xbe79a02d },
  { 0xbee04621 },  { 0xbe76e0cb },  { 0xbee106f2 },  { 0xbe741f07 },
  { 0xbee1c598 },  { 0xbe715aea },  { 0xbee28210 },  { 0xbe6e9479 },
  { 0xbee33c5a },  { 0xbe6bcbbb },  { 0xbee3f473 },  { 0xbe6900b7 },
  { 0xbee4aa59 },  { 0xbe663375 },  { 0xbee55e0b },  { 0xbe6363fa },
  { 0xbee60f88 },  { 0xbe60924f },  { 0xbee6becc },  { 0xbe5dbe79 },
  { 0xbee76bd8 },  { 0xbe5ae880 },  { 0xbee816a8 },  { 0xbe58106b },
  { 0xbee8bf3c },  { 0xbe553641 },  { 0xbee96591 },  { 0xbe525a09 },
  { 0xbeea09a7 },  { 0xbe4f7bca },  { 0xbeeaab7b },  { 0xbe4c9b8b },
  { 0xbeeb4b0c },  { 0xbe49b953 },  { 0xbeebe858 },  { 0xbe46d529 },
  { 0xbeec835e },  { 0xbe43ef15 },  { 0xbeed1c1d },  { 0xbe41071e },
  { 0xbeedb293 },  { 0xbe3e1d4a },  { 0xbeee46be },  { 0xbe3b31a0 },
  { 0xbeeed89e },  { 0xbe38442a },  { 0xbeef6830 },  { 0xbe3554ec },
  { 0xbeeff573 },  { 0xbe3263ef },  { 0xbef08066 },  { 0xbe2f713a },
  { 0xbef10908 },  { 0xbe2c7cd4 },  { 0xbef18f57 },  { 0xbe2986c4 },
  { 0xbef21352 },  { 0xbe268f12 },  { 0xbef294f8 },  { 0xbe2395c5 },
  { 0xbef31447 },  { 0xbe209ae5 },  { 0xbef3913f },  { 0xbe1d9e78 },
  { 0xbef40bdd },  { 0xbe1aa086 },  { 0xbef48422 },  { 0xbe17a117 },
  { 0xbef4fa0b },  { 0xbe14a031 },  { 0xbef56d97 },  { 0xbe119ddd },
  { 0xbef5dec6 },  { 0xbe0e9a22 },  { 0xbef64d97 },  { 0xbe0b9507 },
  { 0xbef6ba07 },  { 0xbe088e93 },  { 0xbef72417 },  { 0xbe0586ce },
  { 0xbef78bc5 },  { 0xbe027dc0 },  { 0xbef7f110 },  { 0xbdfee6e1 },
  { 0xbef853f8 },  { 0xbdf8cfcc },  { 0xbef8b47b },  { 0xbdf2b651 },
  { 0xbef91298 },  { 0xbdec9a7f },  { 0xbef96e4e },  { 0xbde67c66 },
  { 0xbef9c79d },  { 0xbde05c13 },  { 0xbefa1e84 },  { 0xbdda3997 },
  { 0xbefa7302 },  { 0xbdd41501 },  { 0xbefac516 },  { 0xbdcdee60 },
  { 0xbefb14be },  { 0xbdc7c5c2 },  { 0xbefb61fc },  { 0xbdc19b37 },
  { 0xbefbaccd },  { 0xbdbb6ecf },  { 0xbefbf531 },  { 0xbdb54098 },
  { 0xbefc3b28 },  { 0xbdaf10a2 },  { 0xbefc7eb0 },  { 0xbda8defc },
  { 0xbefcbfc9 },  { 0xbda2abb6 },  { 0xbefcfe73 },  { 0xbd9c76de },
  { 0xbefd3aac },  { 0xbd964083 },  { 0xbefd7474 },  { 0xbd9008b7 },
  { 0xbefdabcc },  { 0xbd89cf86 },  { 0xbefde0b1 },  { 0xbd839502 },
  { 0xbefe1324 },  { 0xbd7ab273 },  { 0xbefe4323 },  { 0xbd6e3876 },
  { 0xbefe70b0 },  { 0xbd61bc2e },  { 0xbefe9bc9 },  { 0xbd553db9 },
  { 0xbefec46d },  { 0xbd48bd36 },  { 0xbefeea9d },  { 0xbd3c3ac3 },
  { 0xbeff0e58 },  { 0xbd2fb680 },  { 0xbeff2f9d },  { 0xbd23308c },
  { 0xbeff4e6d },  { 0xbd16a905 },  { 0xbeff6ac7 },  { 0xbd0a200a },
  { 0xbeff84ab },  { 0xbcfb2b74 },  { 0xbeff9c18 },  { 0xbce21469 },
  { 0xbeffb10f },  { 0xbcc8fb30 },  { 0xbeffc38f },  { 0xbcafe007 },
  { 0xbeffd397 },  { 0xbc96c32c },  { 0xbeffe129 },  { 0xbc7b49ba },
  { 0xbeffec43 },  { 0xbc490ab0 },  { 0xbefff4e6 },  { 0xbc16c9b6 },
  { 0xbefffb11 },  { 0xbbc90e90 },  { 0xbefffec4 },  { 0xbb490f88 },
};
