/* ------------------------------------------------------------------------ */
/* Copyright (c) 2016 by Cadence Design Systems, Inc. ALL RIGHTS RESERVED.  */
/* These coded instructions, statements, and computer programs ('Cadence    */
/* Libraries') are the copyrighted works of Cadence Design Systems Inc.     */
/* Cadence IP is licensed for use with Cadence processor cores only and     */
/* must not be used for any other processors and platforms. Your use of the */
/* Cadence Libraries is subject to the terms of the license agreement you   */
/* have entered into with Cadence Design Systems, or a sublicense granted   */
/* to you by a direct Cadence licensee.                                     */
/* ------------------------------------------------------------------------ */
/*  IntegrIT, Ltd.   www.integrIT.com, info@integrIT.com                    */
/*                                                                          */
/* NatureDSP_Baseband Library                                               */
/*                                                                          */
/* This library contains copyrighted materials, trade secrets and other     */
/* proprietary information of IntegrIT, Ltd. This software is licensed for  */
/* use with Cadence processor cores only and must not be used for any other */
/* processors and platforms. The license to use these sources was given to  */
/* Cadence, Inc. under Terms and Condition of a Software License Agreement  */
/* between Cadence, Inc. and IntegrIT, Ltd.                                 */
/* ------------------------------------------------------------------------ */
/*          Copyright (C) 2009-2016 IntegrIT, Limited.                      */
/*                      All Rights Reserved.                                */
/* ------------------------------------------------------------------------ */

#include "NatureDSP_types.h"
#include "common.h"

#include "fft_fp_tw.h"

/*  Twiddles factors for float point FFT/IFFT cfftfN, cifftfN.
    Generated by matlab script make_cfft_twd(): 
    
function make_cfft_twd(N, fname)
v = 4;
if( nargin()==0 )
    fid = fopen('cfft_tw_header.txt', 'rt');
    
    if fid==0
        hdr_txt=''; 
    else
        hdr_txt = fread(fid, inf, 'uint8=>char');
        fclose(fid); 
        
    end
    for log2N = 4:15
        N = 2^log2N; 
        name = sprintf('cfftf%d_twd', N); 
        fname = strcat(name, '_bbe32.c'); 
        fid = fopen(fname, 'wt'); 
        if ~isempty(hdr_txt)
            fprintf(fid, '%s', hdr_txt);             
        end
        all_twd = cfft_twd(N, v); 
        print_twd(all_twd, name, fid);
        fclose(fid);
    end
else
    all_twd = cfft_twd(N, v); 
    print_twd(all_twd, fname, 1);
end

function all_twd = cfft_twd(N, v)
    all_twd = {}; 
    tw = zeros( N*3/4, 1); 
    if v~=4
        error('v~=4');
    end
    
    for j=0: N/(4*v)-1
        for i=0:v-1
            k = j*v + i; 
            tw(1 + i + j * 3 * v + 0 * v) = exp( -2*1j* pi*1 / N*k);
            tw(1 + i + j * 3 * v + 1 * v) = exp( -2*1j* pi*2 / N*k);
            tw(1 + i + j * 3 * v + 2 * v) = exp( -2*1j* pi*3 / N*k);
        end
    end    
    all_twd{end+1} = tw; 
    N = N/4;

    while( N > 8 )

        tw = zeros( N*3/4, 1); 
        if(v>1)
            v = v/4;
        end
            
        for j=0: N/(4*v)-1
            for i=0:v-1
                k = j*v + i; 
                tw(1 + i + j * 3 * v + 0 * v) = exp( -2*1j* pi*1 / N*k);
                tw(1 + i + j * 3 * v + 1 * v) = exp( -2*1j* pi*2 / N*k);
                tw(1 + i + j * 3 * v + 2 * v) = exp( -2*1j* pi*3 / N*k);
            end
        end      
        all_twd{end+1} = tw; 
        N = N/4;
    end
	
	
function print_twd(all_twd, name, fid)

for i=1:length(all_twd)
    t = all_twd{i}; 
    L = length(t); 
    tmp =  reshape( [real(t), imag(t)].', 2*L, 1 ) ; 
    s = num2hex(single(tmp)); 
    fprintf(2, 'extern const union ufloat32uint32 '); 
    fprintf(2, '%s%d[%d];\n', name, i, 2*L); 
   
    fprintf(fid, '\nALIGN(32) const union ufloat32uint32 '); 
    fprintf(fid, '%s%d[%d] = \n{\n', name, i, 2*L); 
    for k=1:2*L
        fprintf(fid, '  { 0x%s },', s(k, :)); 
        if(mod(k, 4)==0)
            fprintf(fid, '\n');     
        end            
    end
    fprintf(fid, '};\n'); 

end
*/


ALIGN(32) const union ufloat32uint32 rfftf512_twd1[256] = 
{
  { 0x00000000 },  { 0xbf000000 },  { 0xbbc90e90 },  { 0xbefffb11 },
  { 0xbc490ab0 },  { 0xbeffec43 },  { 0xbc96c32c },  { 0xbeffd397 },
  { 0xbcc8fb30 },  { 0xbeffb10f },  { 0xbcfb2b74 },  { 0xbeff84ab },
  { 0xbd16a905 },  { 0xbeff4e6d },  { 0xbd2fb680 },  { 0xbeff0e58 },
  { 0xbd48bd36 },  { 0xbefec46d },  { 0xbd61bc2e },  { 0xbefe70b0 },
  { 0xbd7ab273 },  { 0xbefe1324 },  { 0xbd89cf86 },  { 0xbefdabcc },
  { 0xbd964083 },  { 0xbefd3aac },  { 0xbda2abb6 },  { 0xbefcbfc9 },
  { 0xbdaf10a2 },  { 0xbefc3b28 },  { 0xbdbb6ecf },  { 0xbefbaccd },
  { 0xbdc7c5c2 },  { 0xbefb14be },  { 0xbdd41501 },  { 0xbefa7302 },
  { 0xbde05c13 },  { 0xbef9c79d },  { 0xbdec9a7f },  { 0xbef91298 },
  { 0xbdf8cfcc },  { 0xbef853f8 },  { 0xbe027dc0 },  { 0xbef78bc5 },
  { 0xbe088e93 },  { 0xbef6ba07 },  { 0xbe0e9a22 },  { 0xbef5dec6 },
  { 0xbe14a031 },  { 0xbef4fa0b },  { 0xbe1aa086 },  { 0xbef40bdd },
  { 0xbe209ae5 },  { 0xbef31447 },  { 0xbe268f12 },  { 0xbef21352 },
  { 0xbe2c7cd4 },  { 0xbef10908 },  { 0xbe3263ef },  { 0xbeeff573 },
  { 0xbe38442a },  { 0xbeeed89e },  { 0xbe3e1d4a },  { 0xbeedb293 },
  { 0xbe43ef15 },  { 0xbeec835e },  { 0xbe49b953 },  { 0xbeeb4b0c },
  { 0xbe4f7bca },  { 0xbeea09a7 },  { 0xbe553641 },  { 0xbee8bf3c },
  { 0xbe5ae880 },  { 0xbee76bd8 },  { 0xbe60924f },  { 0xbee60f88 },
  { 0xbe663375 },  { 0xbee4aa59 },  { 0xbe6bcbbb },  { 0xbee33c5a },
  { 0xbe715aea },  { 0xbee1c598 },  { 0xbe76e0cb },  { 0xbee04621 },
  { 0xbe7c5d27 },  { 0xbedebe05 },  { 0xbe80e7e4 },  { 0xbedd2d53 },
  { 0xbe839c3d },  { 0xbedb941a },  { 0xbe864b82 },  { 0xbed9f26a },
  { 0xbe88f59b },  { 0xbed84853 },  { 0xbe8b9a6b },  { 0xbed695e5 },
  { 0xbe8e39da },  { 0xbed4db31 },  { 0xbe90d3cd },  { 0xbed31849 },
  { 0xbe93682a },  { 0xbed14d3d },  { 0xbe95f6d9 },  { 0xbecf7a1f },
  { 0xbe987fc0 },  { 0xbecd9f02 },  { 0xbe9b02c6 },  { 0xbecbbbf8 },
  { 0xbe9d7fd1 },  { 0xbec9d112 },  { 0xbe9ff6cb },  { 0xbec7de65 },
  { 0xbea26799 },  { 0xbec5e403 },  { 0xbea4d225 },  { 0xbec3e200 },
  { 0xbea73656 },  { 0xbec1d870 },  { 0xbea99415 },  { 0xbebfc767 },
  { 0xbeabeb4a },  { 0xbebdaef9 },  { 0xbeae3bde },  { 0xbebb8f3b },
  { 0xbeb085bb },  { 0xbeb96842 },  { 0xbeb2c8c9 },  { 0xbeb73a23 },
  { 0xbeb504f3 },  { 0xbeb504f3 },  { 0xbeb73a23 },  { 0xbeb2c8c9 },
  { 0xbeb96842 },  { 0xbeb085bb },  { 0xbebb8f3b },  { 0xbeae3bde },
  { 0xbebdaef9 },  { 0xbeabeb4a },  { 0xbebfc767 },  { 0xbea99415 },
  { 0xbec1d870 },  { 0xbea73656 },  { 0xbec3e200 },  { 0xbea4d225 },
  { 0xbec5e403 },  { 0xbea26799 },  { 0xbec7de65 },  { 0xbe9ff6cb },
  { 0xbec9d112 },  { 0xbe9d7fd1 },  { 0xbecbbbf8 },  { 0xbe9b02c6 },
  { 0xbecd9f02 },  { 0xbe987fc0 },  { 0xbecf7a1f },  { 0xbe95f6d9 },
  { 0xbed14d3d },  { 0xbe93682a },  { 0xbed31849 },  { 0xbe90d3cd },
  { 0xbed4db31 },  { 0xbe8e39da },  { 0xbed695e5 },  { 0xbe8b9a6b },
  { 0xbed84853 },  { 0xbe88f59b },  { 0xbed9f26a },  { 0xbe864b82 },
  { 0xbedb941a },  { 0xbe839c3d },  { 0xbedd2d53 },  { 0xbe80e7e4 },
  { 0xbedebe05 },  { 0xbe7c5d27 },  { 0xbee04621 },  { 0xbe76e0cb },
  { 0xbee1c598 },  { 0xbe715aea },  { 0xbee33c5a },  { 0xbe6bcbbb },
  { 0xbee4aa59 },  { 0xbe663375 },  { 0xbee60f88 },  { 0xbe60924f },
  { 0xbee76bd8 },  { 0xbe5ae880 },  { 0xbee8bf3c },  { 0xbe553641 },
  { 0xbeea09a7 },  { 0xbe4f7bca },  { 0xbeeb4b0c },  { 0xbe49b953 },
  { 0xbeec835e },  { 0xbe43ef15 },  { 0xbeedb293 },  { 0xbe3e1d4a },
  { 0xbeeed89e },  { 0xbe38442a },  { 0xbeeff573 },  { 0xbe3263ef },
  { 0xbef10908 },  { 0xbe2c7cd4 },  { 0xbef21352 },  { 0xbe268f12 },
  { 0xbef31447 },  { 0xbe209ae5 },  { 0xbef40bdd },  { 0xbe1aa086 },
  { 0xbef4fa0b },  { 0xbe14a031 },  { 0xbef5dec6 },  { 0xbe0e9a22 },
  { 0xbef6ba07 },  { 0xbe088e93 },  { 0xbef78bc5 },  { 0xbe027dc0 },
  { 0xbef853f8 },  { 0xbdf8cfcc },  { 0xbef91298 },  { 0xbdec9a7f },
  { 0xbef9c79d },  { 0xbde05c13 },  { 0xbefa7302 },  { 0xbdd41501 },
  { 0xbefb14be },  { 0xbdc7c5c2 },  { 0xbefbaccd },  { 0xbdbb6ecf },
  { 0xbefc3b28 },  { 0xbdaf10a2 },  { 0xbefcbfc9 },  { 0xbda2abb6 },
  { 0xbefd3aac },  { 0xbd964083 },  { 0xbefdabcc },  { 0xbd89cf86 },
  { 0xbefe1324 },  { 0xbd7ab273 },  { 0xbefe70b0 },  { 0xbd61bc2e },
  { 0xbefec46d },  { 0xbd48bd36 },  { 0xbeff0e58 },  { 0xbd2fb680 },
  { 0xbeff4e6d },  { 0xbd16a905 },  { 0xbeff84ab },  { 0xbcfb2b74 },
  { 0xbeffb10f },  { 0xbcc8fb30 },  { 0xbeffd397 },  { 0xbc96c32c },
  { 0xbeffec43 },  { 0xbc490ab0 },  { 0xbefffb11 },  { 0xbbc90e90 },
};
