/* ------------------------------------------------------------------------ */
/* Copyright (c) 2016 by Cadence Design Systems, Inc. ALL RIGHTS RESERVED.  */
/* These coded instructions, statements, and computer programs ('Cadence    */
/* Libraries') are the copyrighted works of Cadence Design Systems Inc.     */
/* Cadence IP is licensed for use with Cadence processor cores only and     */
/* must not be used for any other processors and platforms. Your use of the */
/* Cadence Libraries is subject to the terms of the license agreement you   */
/* have entered into with Cadence Design Systems, or a sublicense granted   */
/* to you by a direct Cadence licensee.                                     */
/* ------------------------------------------------------------------------ */
/*  IntegrIT, Ltd.   www.integrIT.com, info@integrIT.com                    */
/*                                                                          */
/* NatureDSP_Baseband Library                                               */
/*                                                                          */
/* This library contains copyrighted materials, trade secrets and other     */
/* proprietary information of IntegrIT, Ltd. This software is licensed for  */
/* use with Cadence processor cores only and must not be used for any other */
/* processors and platforms. The license to use these sources was given to  */
/* Cadence, Inc. under Terms and Condition of a Software License Agreement  */
/* between Cadence, Inc. and IntegrIT, Ltd.                                 */
/* ------------------------------------------------------------------------ */
/*          Copyright (C) 2009-2017 IntegrIT, Limited.                      */
/*                      All Rights Reserved.                                */
/* ------------------------------------------------------------------------ */

/*
    NatureDSP_Baseband library. IIR part
    Biquad complex block IIR
    C code optimized for BBE32
    IntegrIT, 2006-2017
*/

/*-------------------------------------------------------------------------
  Biquad Complex Block IIR

  Passes complex input data through a series of cascaded biquad sections
  with real coefficients. Filter implementation is based on Direct Form II
  aka the Canonical Form. Please refer to the NatureDSP Baseband Library
  Reference for details on the filter structure.
  
  For each section the user has to provide 2 feedback tap coefficients 
  a1, a2, and 3 feedforward tap coefficients b0, b1, b2. Fixed-point filter
  variant also requires the input gain term g to be specified for each biquad
  section. For the final scaling of filter output data, the total gain 
  coefficient (gain) is applied to output samples produced by the last biquad
  section.

  Representation:
  bqciir         16-bit signed fixed-point format for input/output samples
                 and tap coefficients
  bqciirf        IEEE-754 Std. single precision floating-point format for
                 input/output data and tap coefficients

  Implementation of biquad series for fixed-point data format has two flavors:
  Low_Noise  Performs 32x16-bit multiplications and utilizes the scratch
             memory to keep intermediate results in order to lower the
             quantization noise and reduce round-off errors
  Fast       Makes use of native 16x16-bit multipliers and thus appears faster
             than the Low Noise variant at the cost of deteriorated accuracy

  Notes:
  1. Biquad coefficients may be derived from standard SOS and G matrices 
     generated by MATLAB. However, scale factors may require some tuning 
     to find a compromise between quantization noise and possible overflows.
  2. For performance reasons, implementation may introduce additional
     algorithmic delay (group delay) to the output data.

  Methods:
    bqciir[f]_alloc()   - calculate memory block size for a filter instance
    bqciir[f]_init()    - initialize the filter instance
    bqciir[f]_process() - pass a block of complex input samples to the filter
                          and return filter output samples
  Restrictions:
    - input/output complex data arrays must be aligned by 4 (bqciir) or
      8 (bqciirf) bytes
    - scratch memory block, whenever supplied, must be 32 bytes aligned
    - number of biquads M must be less or equal to 32
---------------------------------------------------------------------------*/

#include <string.h>
/* Cross-platform data type definitions. */
#include "NatureDSP_types.h"
/* Common helper macros. */
#include "common.h"
/* NatureDSP_Baseband library API. */
#include "NatureDSP_Baseband_iir.h"
/* Filter processing functions. */
#include "bqciir_common.h"

/* Instance pointer validation number. */
#define MAGIC 0x8E2376AA

/* Reserve memory for alignment. */
#define ALIGNED_SIZE( size, align ) \
      ( (size_t)(size) + (align) - 1 )

/* Align address on a specified boundary. */
#define ALIGNED_ADDR( addr, align ) \
      ( ( (uintptr_t)(addr) + ( (align) - 1 ) ) & ~( (align) - 1 ) )

/* Filter instance structure. */
typedef struct tag_bqciir_t
{
  uint32_t  magic;   // Instance pointer validation number
  int       opt;     // BQCIIR_OPT_LOW_NOISE | BQCIIR_OPT_FAST
  int       M;       // Biquads number
  int16_t   gain;    // Total gain, Q8
  int16_t * coef;    // Biquad coefficients
  int16_t * sect;    // Biquad sections state
} bqciir_t, *bqciir_ptr_t;


/*---------------------------------------------------------------------------
   Calculate the memory block size for a filter with given attributes.
   Input:
     M     Number of biquad sections
     opt   Fixed-point implementation variant selector, BQCIIR_OPT_LOW_NOISE or
           BQCIIR_OPT_FAST
   Output:
     Returns required memory block size, in bytes, or zero if failed
   Restrictions:
     M<=32 
---------------------------------------------------------------------------*/

size_t bqciir_alloc ( int M, int opt )
{
  if ( M <= 0 || M>32)
  {
    return (0);
  }

  M = 8*( ( M + 7 ) >> 3 );

  switch ( opt )
  {
  case BQCIIR_OPT_FAST:
    return ( ALIGNED_SIZE( sizeof( bqciir_t ), 4 )
             + // Biquad coefficients
             ALIGNED_SIZE( 6*M*2*2, 32 )
             + // Sections state
             ALIGNED_SIZE( 8*M*2, 32 ));

  case BQCIIR_OPT_LOW_NOISE:
    return ( ALIGNED_SIZE( sizeof( bqciir_t ), 4 )
             + // Biquad coefficients
             ALIGNED_SIZE( 6*M*2*2, 32 )
             + // Sections state
             ALIGNED_SIZE( 16*M*2, 32 ));
  }

  return (0);

} /* bqciir_alloc() */

/*---------------------------------------------------------------------------
   Initialize the filter instance. Delay elements are zeroed.
   Input:
     objmem     Memory block of bqciir_alloc(M,opt) or bqciirf_alloc(M) bytes
     M          Number of biquad sections
     opt        Fixed-point implementation variant selector, BQCIIR_OPT_LOW_NOISE
                or BQCIIR_OPT_FAST
     coef[C*M]  Per-section coefficient blocks. Each coefficient block contains
                5 tap coefficients a1,a2,b0,b1,b2 and (only for the fixed-point
                variant) the input gain term g. Coefficients must be ordered
                as shown below:
                  bqciir_init()  C=6: g, b0, b1, b2, a1, a2 (Q14)
                  bqciirf_init() C=5: b0, b1, b2, a1, a2
     gain       Total gain coefficient to be applied to the output of the 
                last biquad. Fixed-point data format for bqciir_init() is Q8
   Output:
     Returns the filter handle, or zero if failed.
   Restrictions:
     M<=32 
---------------------------------------------------------------------------*/

bqciir_handle_t bqciir_init ( void * objmem, int M, int opt, 
                             const int16_t * coef, int16_t gain )
{
  bqciir_ptr_t bqciir;
  void       * ptr;
  int16_t    * cf, *cf1;
  int16_t    * sect;
  int          sectSize;

  int          M1, m1, n;

  //
  // Validate the arguments.
  //

  if ( !objmem || M <= 0 || M > 32 || !coef )
  {
    return (0);
  }

  //
  // Select the sections state size and filter response delay.
  //

  M1 = M;
  M = 8*( ( M + 7 ) >> 3 );

  switch ( opt )
  {
  case BQCIIR_OPT_FAST:
    sectSize = 8*M;
    break;
  case BQCIIR_OPT_LOW_NOISE:
    sectSize = 16*M;
    break;
  default:
    return (0);
  }

  //
  // Partition the memory block.
  //

  ptr     = objmem;
  bqciir  = (bqciir_ptr_t)ALIGNED_ADDR( ptr, 4 );
  ptr     = bqciir + 1;
  cf      = (int16_t*)ALIGNED_ADDR( ptr, 32 );
  ptr     = cf + 6*M*2;
  sect    = (int16_t*)ALIGNED_ADDR( ptr, 32 );
  ptr     = sect + sectSize;

  NASSERT( (int8_t*)ptr - (int8_t*)objmem <= (int)bqciir_alloc( M, opt ) );

  //
  // Copy the filter coefficients, zero the sections state and delay line.
  //

  cf1 = cf;
  for ( m1 = 0; m1<(M>>3); m1++ )
  {
      for ( n=0; n<8; n++ )
      {
        if (8*m1+n < M1)
        {
            *cf1++ = coef[6*(8*m1+n)+0];
            *cf1++ = coef[6*(8*m1+n)+0];
        }
        else
        {
            *cf1++ = 16384;
            *cf1++ = 16384;
        }
      }
      for ( n=0; n<8; n++ )
      {
        if (8*m1+n < M1)
        {
            *cf1++ = coef[6*(8*m1+n)+1];
            *cf1++ = coef[6*(8*m1+n)+1];
        }
        else
        {
            *cf1++ = 16384;
            *cf1++ = 16384;
        }
      }
      for ( n=0; n<8; n++ )
      {
        if (8*m1+n < M1)
        {
            *cf1++ = coef[6*(8*m1+n)+2];
            *cf1++ = coef[6*(8*m1+n)+2];
        }
        else
        {
            *cf1++ = 0;
            *cf1++ = 0;
        }
      }
      for ( n=0; n<8; n++ )
      {
        if (8*m1+n < M1)
        {
            *cf1++ = coef[6*(8*m1+n)+3];
            *cf1++ = coef[6*(8*m1+n)+3];
        }
        else
        {
            *cf1++ = 0;
            *cf1++ = 0;
        }
      }
      for ( n=0; n<8; n++ )
      {
        if (8*m1+n < M1)
        {
            *cf1++ = - coef[6*(8*m1+n)+4];
            *cf1++ = - coef[6*(8*m1+n)+4];
        }
        else
        {
            *cf1++ = 0;
            *cf1++ = 0;
        }
      }
      for ( n=0; n<8; n++ )
      {
        if (8*m1+n < M1)
        {
            *cf1++ = - coef[6*(8*m1+n)+5];
            *cf1++ = - coef[6*(8*m1+n)+5];
        }
        else
        {
            *cf1++ = 0;
            *cf1++ = 0;
        }
      }
  }

  memset( sect, 0, sectSize*2 );

  //
  // Initialize the filter instance.
  //

  memset( bqciir, 0, sizeof( bqciir_t ) );

  bqciir->magic   = MAGIC;
  bqciir->opt     = opt;
  bqciir->M       = M;
  bqciir->gain    = gain;
  bqciir->coef    = cf;
  bqciir->sect    = sect;

  return (bqciir);

} /* bqciir_init() */

/*---------------------------------------------------------------------------
   Pass a block of complex input samples to the filter and return filter output
   samples
   Input:
     _bqciir,
     _bqriirf     Filter handle
     N            Input/output signal chunk size, in samples
     x[N]         Complex input samples
   Output:
     r[N]         Complex output samples
   Temporary:
     scr[8*N+32]  Scratch memory block, in bytes; required by the Low Noise 
                  fixed-point implementation variant (BQCIIR_OPT_LOW_NOISE), 
                  otherwise may be null
   Restrictions:
     x,r          Aligned on 4-byte (bqciir) or 8-byte (bqciirf) boundary
     scr          Aligned on 32-byte boundary, whenever supplied
---------------------------------------------------------------------------*/

void bqciir_process ( bqciir_handle_t    _bqciir, 
                     complex_fract16 * restrict r,
               const complex_fract16 *          x,
                     void * restrict scr,
                     int                N )
{
  bqciir_ptr_t bqciir = (bqciir_ptr_t)_bqciir;

  int       M;

  //
  // Validate the arguments.
  //

  NASSERT( bqciir && bqciir->magic == MAGIC );
  NASSERT( r && x && ( bqciir->opt != BQCIIR_OPT_LOW_NOISE || scr ) );
  NASSERT_ALIGN4(r);
  NASSERT_ALIGN4(x);
  //
  // Update the input samples delay line.
  //

  M       = bqciir->M;

  //
  // Select and run the processing function.
  //

  if ( bqciir->opt == BQCIIR_OPT_LOW_NOISE )
  {
    bqciir_dp_proc( (int16_t*)r, 
                    bqciir->sect, 
                    (int16_t*)x, 
                    (int16_t*)scr, 
                    bqciir->coef, 
                    bqciir->gain, N, M );
  }
  else
  {
    bqciir_sp_proc( (int16_t*)r, 
                    bqciir->sect, 
                    (int16_t*)x, 
                    bqciir->coef, 
                    bqciir->gain, N, M );
  }
} /* bqciir_process() */
