/* ------------------------------------------------------------------------ */
/* Copyright (c) 2016 by Cadence Design Systems, Inc. ALL RIGHTS RESERVED.  */
/* These coded instructions, statements, and computer programs ('Cadence    */
/* Libraries') are the copyrighted works of Cadence Design Systems Inc.     */
/* Cadence IP is licensed for use with Cadence processor cores only and     */
/* must not be used for any other processors and platforms. Your use of the */
/* Cadence Libraries is subject to the terms of the license agreement you   */
/* have entered into with Cadence Design Systems, or a sublicense granted   */
/* to you by a direct Cadence licensee.                                     */
/* ------------------------------------------------------------------------ */
/*  IntegrIT, Ltd.   www.integrIT.com, info@integrIT.com                    */
/*                                                                          */
/* NatureDSP_Baseband Library                                               */
/*                                                                          */
/* This library contains copyrighted materials, trade secrets and other     */
/* proprietary information of IntegrIT, Ltd. This software is licensed for  */
/* use with Cadence processor cores only and must not be used for any other */
/* processors and platforms. The license to use these sources was given to  */
/* Cadence, Inc. under Terms and Condition of a Software License Agreement  */
/* between Cadence, Inc. and IntegrIT, Ltd.                                 */
/* ------------------------------------------------------------------------ */
/*          Copyright (C) 2009-2017 IntegrIT, Limited.                      */
/*                      All Rights Reserved.                                */
/* ------------------------------------------------------------------------ */

/*
    NatureDSP_Baseband library. IIR part
    Biquad real block IIR, streaming version
    C code optimized for BBE32
    IntegrIT, 2006-2017
*/

/*-------------------------------------------------------------------------
  Streaming Biquad Real Block IIR 

  Passes a few streams of real data through a series of cascaded biquad 
  sections. Filter implementation is based on Direct Form II aka the
  Canonical Form. Please refer to the NatureDSP Baseband Library Reference
  for details on the filter structure.

  For each section the user has to provide 2 feedback tap coefficients 
  a1, a2, and 3 feedforward tap coefficients b0, b1, b2. Fixed-point filter
  variant also requires the input gain term g to be specified for each biquad
  section. For the final scaling of filter output data, the total gain 
  coefficient (gain) is applied to output samples produced by the last biquad
  section.

  Representation:
  bqriirs    16-bit signed fixed-point format for input/output samples
             and tap coefficients
  bqriirsf   IEEE-754 Std. single precision floating-point format for
             input/output data and tap coefficients

  Implementation of biquad series for fixed-point data format has two flavors:
  Low_Noise  Performs 32x16-bit multiplications and utilizes the scratch
             memory to keep intermediate results in order to lower the
             quantization noise and reduce round-off errors
  Fast       Makes use of native 16x16-bit multipliers and thus appears faster
             than the Low Noise variant at the cost of deteriorated accuracy

  Notes:
  1. Biquad coefficients may be derived from standard SOS and G matrices 
     generated by MATLAB. However, scale factors may require some tuning 
     to find a compromise between quantization noise and possible overflows.
  2. Streaming biquad real block IIR filter may by applied to complex
     data stored in streaming format, which is equivalent to passing a
     complex signal through a complex IIR with real coefficients. The number
     of real data streams L as it is seen by the filter implementation must
     be two times the number of actual complex streams.

  Methods:
      bqriirs[f]_alloc()   - calculate memory block size for a filter instance
      bqriirs[f]_init()    - initialize the filter instance
      bqriirs[f]_process() - pass a block of input samples to the filter and
                             return filter output samples. This operation is
                             simultaneously accomplished for a few independent
                             data streams.
  Restrictions:
      - input/output data arrays must be aligned on 32-byte boundary
      - scratch memory block, whenever supplied, must be 32 bytes aligned
      – number of streams must be a multiple of 16 (bqriirs) or 8 (bqriirsf)
---------------------------------------------------------------------------*/

#include <string.h>
/* Cross-platform data type definitions. */
#include "NatureDSP_types.h"
/* Common helper macros. */
#include "common.h"
/* NatureDSP_Baseband library API. */
#include "NatureDSP_Baseband_iir.h"
/* Filter processing functions. */
#include "bqriirs_common.h"

/* Instance pointer validation number. */
#define MAGIC     0x3468CEE5

/* Reserve memory for alignment. */
#define ALIGNED_SIZE( size, align ) \
      ( (size_t)(size) + (align) - 1 )

/* Align address on a specified boundary. */
#define ALIGNED_ADDR( addr, align ) \
      ( ( (uintptr_t)(addr) + ( (align) - 1 ) ) & ~( (align) - 1 ) )

/* Filter instance structure. */
typedef struct tag_bqriir_t
{
  uint32_t  magic;   // Instance pointer validation number
  int       opt;     // BQRIIRS_OPT_LOW_NOISE or BQRIIRS_OPT_FAST
  int       L;       // Number of streams
  int       M;       // Biquads number
  int16_t   gain;    // Total gain, Q8
  int16_t * coef;    // Biquad coefficients
  int16_t * sect;    // Biquad sections state
  
} bqriirs_t, *bqriirs_ptr_t;

/*---------------------------------------------------------------------------
   Calculate the memory block size for a filter with given attributes.
   Input:
     L     Number of streams
     M     Number of biquad sections
     opt   Fixed-point implementation variant selector, BQRIIRS_OPT_LOW_NOISE
           or BQRIIRS_OPT_FAST
   Output:
     Returns required memory block size, in bytes, or zero if failed
   Restrictions:
     L     Must be a multiple of 16 (bqriirs) or 8 (bqriirsf)
---------------------------------------------------------------------------*/

size_t bqriirs_alloc ( int L, int M, int opt )
{
    
  if ( M <= 0 || L<=0 || L % BBE_SIMD_WIDTH > 0 )
  {
    return (0);
  }

  switch ( opt )
  {
  case BQRIIRS_OPT_FAST:

    return ( ALIGNED_SIZE( sizeof( bqriirs_t ), 4 )
             + // Biquad coefficients
             ALIGNED_SIZE( 6*M*2, 2 )
             + // Sections state
             ALIGNED_SIZE( 4*M*L*2, (2*BBE_SIMD_WIDTH) ));

  case BQRIIRS_OPT_LOW_NOISE:

    return ( ALIGNED_SIZE( sizeof( bqriirs_t ), 4 )
             + // Biquad coefficients
             ALIGNED_SIZE( 6*M*2, 2 )
             + // Sections state
             ALIGNED_SIZE( 6*M*L*2, (2*BBE_SIMD_WIDTH)  ));
  }

  return (0);

} /* bqriirs_alloc() */

/*--------------------------------------------------------------------------- 
   Initialize the filter instance. Delay elements are zeroed.
   Input:
     objmem     Memory block of bqriirs_alloc(L,M,opt) or bqriirsf_alloc(L,M) bytes
     M          Number of biquad sections
     L          Number of streams
     opt        Fixed-point implementation variant selector, BQRIIRS_OPT_LOW_NOISE
                or BQRIIRS_OPT_FAST
     coef[C*M]  Per-section coefficient blocks. Each coefficient block contains
                5 tap coefficients a1,a2,b0,b1,b2 and (only for the fixed-point
                variant) the input gain term g. Coefficients must be ordered
                as shown below:
                  bqriirs_init()  C=6: g, b0, b1, b2, a1, a2 (Q14)
                  bqriirsf_init() C=5: b0, b1, b2, a1, a2
     gain       Total gain coefficient to be applied to the output of the 
                last biquad. Fixed-point data format for bqriirs_init() is Q8
   Output:
     Returns the filter handle, or zero if failed.
   Restrictions:
     L          Must be a multiple of 16 (bqriirs) or 8 (bqriirsf)
---------------------------------------------------------------------------*/

bqriirs_handle_t bqriirs_init ( void * objmem, int L, int M, int opt, 
                               const int16_t * coef, int16_t gain )
{
    
  bqriirs_ptr_t bqriirs;
  void       * ptr;
  int16_t    * cf, * cf1;
  int16_t    * sect;
  int          sectSize;

  int          m;

  //
  // Validate the arguments.
  //

  if ( !objmem || M <= 0 || L<=0 || L % BBE_SIMD_WIDTH > 0 || !coef )
  {
    return (0);
  }

  //
  // Select the sections state size and filter response delay.
  //

  switch ( opt )
  {
  case BQRIIRS_OPT_FAST:

    sectSize = 4*M*L;
    break;

  case BQRIIRS_OPT_LOW_NOISE:

    sectSize = 6*M*L;
    break;

  default:
    return (0);
  }

  //
  // Partition the memory block.
  //

  ptr     = objmem;
  bqriirs = (bqriirs_ptr_t)ALIGNED_ADDR( ptr, 4 );
  ptr     = bqriirs + 1;
  cf      = (int16_t*)ALIGNED_ADDR( ptr, 2 );
  ptr     = cf + 6*M;
  sect    = (int16_t*)ALIGNED_ADDR( ptr, (2*BBE_SIMD_WIDTH)  );
  ptr     = sect + sectSize;

  ASSERT( (int8_t*)ptr - (int8_t*)objmem <= (int)bqriirs_alloc( L, M, opt ) );

  //
  // Copy the filter coefficients, zero the sections state and delay line.
  //

  cf1 = cf;
  for ( m=0; m<M; m++ )
  {
      *cf1++ =   coef[6*m+0];
      *cf1++ =   coef[6*m+1];
      *cf1++ =   coef[6*m+2];
      *cf1++ =   coef[6*m+3];
      *cf1++ = - coef[6*m+4];
      *cf1++ = - coef[6*m+5];
  }

  memset( sect, 0, sectSize*2 );

  //
  // Initialize the filter instance.
  //

  memset( bqriirs, 0, sizeof( bqriirs_t ) );

  bqriirs->magic   = MAGIC;
  bqriirs->opt     = opt;
  bqriirs->L       = L;
  bqriirs->M       = M;
  bqriirs->gain    = gain;
  bqriirs->coef    = cf;
  bqriirs->sect    = sect;
 
  return (bqriirs);

} /* bqriirs_init() */

/*---------------------------------------------------------------------------
   Pass a block of input samples to the filter and return filter output
   samples
   Input:
     _bqriirs,
     _bqriirsf    Filter handle
     N            Input/output signal chunk size, in samples (per stream)
     x[N*L]       Input samples
   Temporary:
     scr[4*N*L]   Scratch memory block, in bytes; required by the Low Noise 
                  fixed-point implementation variant (BQRIIRS_OPT_LOW_NOISE), 
                  otherwise may be null
   Output:
     r[N*L]       Output samples
   Restrictions:
     x,r          Must be aligned on 32-byte boundary
     scr          Must be aligned on 32-byte boundary, whenever supplied
     L            Must be a multiple of 16 (bqriirs) or 8 (bqriirsf)
---------------------------------------------------------------------------*/

void bqriirs_process ( bqriirs_handle_t   _bqriirs,
                      int16_t * restrict r,
                const int16_t *          x,
                      void * restrict scr,
                      int                N )
{
    
  bqriirs_ptr_t bqriirs = (bqriirs_ptr_t)_bqriirs;

  int M, L;

  //
  // Validate the arguments.
  //

  ASSERT( bqriirs && bqriirs->magic == MAGIC );

  ASSERT( r && x && ( bqriirs->opt != BQCIIR_OPT_LOW_NOISE || scr ) );

  NASSERT_ALIGN( r,2*BBE_SIMD_WIDTH );
  NASSERT_ALIGN( x,2*BBE_SIMD_WIDTH  );

  //
  // Update the input samples delay line.
  //

  M = bqriirs->M;
  L = bqriirs->L;

  //
  // Select and run the processing function.
  //

  if ( bqriirs->opt == BQCIIR_OPT_LOW_NOISE )
  {
    bqriirs_dp_proc( r,
                    bqriirs->sect,
                    x,
                    (int16_t*)scr,
                    bqriirs->coef,
                    bqriirs->gain, N, L, M );
  }
  else
  {
    bqriirs_sp_proc( r,
                    bqriirs->sect,
                    x,
                    bqriirs->coef,
                    bqriirs->gain, N, L, M );
  }

} /* bqriirs_process() */
