/* ------------------------------------------------------------------------ */
/* Copyright (c) 2017 by Cadence Design Systems, Inc. ALL RIGHTS RESERVED.  */
/* These coded instructions, statements, and computer programs ('Cadence    */
/* Libraries') are the copyrighted works of Cadence Design Systems Inc.     */
/* Cadence IP is licensed for use with Cadence processor cores only and     */
/* must not be used for any other processors and platforms. Your use of the */
/* Cadence Libraries is subject to the terms of the license agreement you   */
/* have entered into with Cadence Design Systems, or a sublicense granted   */
/* to you by a direct Cadence licensee.                                     */
/* ------------------------------------------------------------------------ */
/*  IntegrIT, Ltd.   www.integrIT.com, info@integrIT.com                    */
/*                                                                          */
/* NatureDSP_Baseband Library                                               */
/*                                                                          */
/* This library contains copyrighted materials, trade secrets and other     */
/* proprietary information of IntegrIT, Ltd. This software is licensed for  */
/* use with Cadence processor cores only and must not be used for any other */
/* processors and platforms. The license to use these sources was given to  */
/* Cadence, Inc. under Terms and Condition of a Software License Agreement  */
/* between Cadence, Inc. and IntegrIT, Ltd.                                 */
/* ------------------------------------------------------------------------ */
/*          Copyright (C) 2009-2017 IntegrIT, Limited.                      */
/*                      All Rights Reserved.                                */
/* ------------------------------------------------------------------------ */
/*
 * NatureDSP_Baseband Library API
 * IIR Filters
 */

#ifndef __NATUREDSP_BASEBAND_IIR_H
#define __NATUREDSP_BASEBAND_IIR_H

#include "NatureDSP_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/*===========================================================================
IIR filters:
bqriir  Biquad real block IIR
bqciir  Biquad complex block IIR w/ real coefficients
bqriirs Biquad real block IIR, streaming version
latr    Lattice real block IIR
latc    Lattice complex block IIR w/ real coefficients
latrs   Lattice real block IIR, streaming version
===========================================================================*/

/*-------------------------------------------------------------------------
  Biquad Real Block IIR

  Passes real input data through a series of cascaded biquad sections. Filter 
  implementation is based on Direct Form II aka the Canonical Form. Please 
  refer to the NatureDSP Baseband Library Reference for details on the filter 
  structure.

  For each section the user has to provide 2 feedback tap coefficients 
  a1, a2, and 3 feedforward tap coefficients b0, b1, b2. Fixed-point filter
  variant also requires the input gain term g to be specified for each biquad
  section. For the final scaling of filter output data, the total gain 
  coefficient (gain) is applied to output samples produced by the last biquad
  section.

  Representation:
  bqriir         16-bit signed fixed-point format for input/output samples 
                 and tap coefficients
  bqriirf        IEEE-754 Std. single precision floating-point format for
                 input/output data and tap coefficients

  Implementation of biquad series for fixed-point data format has two flavors:
  Low_Noise  Performs 32x16-bit multiplications and utilizes the scratch
             memory to keep intermediate results in order to lower the
             quantization noise and reduce round-off errors
  Fast       Makes use of native 16x16-bit multipliers and thus appears faster
             than the Low Noise variant at the cost of deteriorated accuracy

  Notes:
  1. Biquad coefficients may be derived from standard SOS and G matrices 
     generated by MATLAB. However, scale factors may require some tuning 
     to find a compromise between quantization noise and possible overflows.
  2. For performance reasons, implementation may introduce additional
     algorithmic delay (group delay) to the output data.

  Methods:
    bqriir[f]_alloc()   - calculate memory block size for a filter instance
    bqriir[f]_init()    - initialize the filter instance
    bqriir[f]_process() - pass a block of input samples to the filter and return
                          filter output samples
  Restrictions:
    - scratch memory block, whenever supplied, must be 32 bytes aligned
    - number of biquads M must be less or equal to 32
---------------------------------------------------------------------------*/

#define BQRIIR_OPT_LOW_NOISE        1
#define BQRIIR_OPT_FAST             0

/* Filter instance structure is defined internally. */
typedef void * bqriir_handle_t;
typedef void * bqriirf_handle_t;

/*---------------------------------------------------------------------------
   Calculate the memory block size for a filter with given attributes.
   Input:
     M     Number of biquad sections
     opt   Fixed-point implementation variant selector, BQRIIR_OPT_LOW_NOISE or
           BQRIIR_OPT_FAST
   Output:
     Returns required memory block size, in bytes, or zero if failed
   Restrictions:
     M<=32
---------------------------------------------------------------------------*/
size_t bqriir_alloc ( int M, int opt );
size_t bqriirf_alloc( int M );

/*---------------------------------------------------------------------------
   Initialize the filter instance. Delay elements are zeroed.
   Input:
     objmem     Memory block of bqriir_alloc(M,opt) or bqriirf_alloc(M) bytes
     M          Number of biquad sections
     opt        Fixed-point implementation variant selector, BQRIIR_OPT_LOW_NOISE
                or BQRIIR_OPT_FAST
     coef[C*M]  Per-section coefficient blocks. Each coefficient block contains
                5 tap coefficients a1,a2,b0,b1,b2 and (only for the fixed-point
                variant) the input gain term g. Coefficients must be ordered
                as shown below:
                  bqriir_init()  C=6: g, b0, b1, b2, a1, a2 (Q14)
                  bqriirf_init() C=5: b0, b1, b2, a1, a2
     gain       Total gain coefficient to be applied to the output of the 
                last biquad (for fixed point API only). Fixed-point data format 
                for bqriir_init() is Q8
   Output:
     Returns the filter handle, or zero if failed.
   Restrictions:
     M<=32
---------------------------------------------------------------------------*/
bqriir_handle_t  bqriir_init ( void * objmem, int M, int opt, 
                               const int16_t * coef, int16_t gain );
bqriirf_handle_t bqriirf_init( void * objmem, int M,
                               const float32_t * coef, float32_t gain );

/*---------------------------------------------------------------------------
   Pass a block of input samples to the filter and return filter output
   samples
   Input:
     _bqriir,
     _bqriirf     Filter handle
     N            Input/output signal chunk size, in samples
     x[N]         Input samples
   Output:
     r[N]         Output samples
   Temporary:
     scr[4*N+32]  Scratch memory block, size in bytes; required by the Low 
                  Noise fixed-pointimplementation variant (BQRIIR_OPT_LOW_NOISE), 
                  otherwise may be null
   Restrictions:
     scr          Aligned on 32-byte boundary, whenever supplied
---------------------------------------------------------------------------*/
void bqriir_process ( bqriir_handle_t      _bqriir,
                      int16_t * restrict   r,
                const int16_t *            x,
                      void * restrict   scr,
                      int                  N );
void bqriirf_process( bqriirf_handle_t     _bqriirf,
                      float32_t * restrict r,
                const float32_t *          x,
                      int                  N );

/*-------------------------------------------------------------------------
  Biquad Complex Block IIR

  Passes complex input data through a series of cascaded biquad sections
  with real coefficients. Filter implementation is based on Direct Form II
  aka the Canonical Form. Please refer to the NatureDSP Baseband Library
  Reference for details on the filter structure.
  
  For each section the user has to provide 2 feedback tap coefficients 
  a1, a2, and 3 feedforward tap coefficients b0, b1, b2. Fixed-point filter
  variant also requires the input gain term g to be specified for each biquad
  section. For the final scaling of filter output data, the total gain 
  coefficient (gain) is applied to output samples produced by the last biquad
  section.

  Representation:
  bqciir         16-bit signed fixed-point format for input/output samples
                 and tap coefficients
  bqciirf        IEEE-754 Std. single precision floating-point format for
                 input/output data and tap coefficients

  Implementation of biquad series for fixed-point data format has two flavors:
  Low_Noise  Performs 32x16-bit multiplications and utilizes the scratch
             memory to keep intermediate results in order to lower the
             quantization noise and reduce round-off errors
  Fast       Makes use of native 16x16-bit multipliers and thus appears faster
             than the Low Noise variant at the cost of deteriorated accuracy

  Notes:
  1. Biquad coefficients may be derived from standard SOS and G matrices 
     generated by MATLAB. However, scale factors may require some tuning 
     to find a compromise between quantization noise and possible overflows.
  2. For performance reasons, implementation may introduce additional
     algorithmic delay (group delay) to the output data.

  Methods:
    bqciir[f]_alloc()   - calculate memory block size for a filter instance
    bqciir[f]_init()    - initialize the filter instance
    bqciir[f]_process() - pass a block of complex input samples to the filter
                          and return filter output samples
  Restrictions:
    - input/output complex data arrays must be aligned by 4 (bqciir) or
      8 (bqciirf) bytes
    - scratch memory block, whenever supplied, must be 32 bytes aligned
    - number of biquads M must be less or equal to 32
---------------------------------------------------------------------------*/

#define BQCIIR_OPT_LOW_NOISE        1
#define BQCIIR_OPT_FAST             0

/* Filter instance structure is defined internally. */
typedef void * bqciir_handle_t;
typedef void * bqciirf_handle_t;

/*---------------------------------------------------------------------------
   Calculate the memory block size for a filter with given attributes.
   Input:
     M     Number of biquad sections
     opt   Fixed-point implementation variant selector, BQCIIR_OPT_LOW_NOISE or
           BQCIIR_OPT_FAST
   Output:
     Returns required memory block size, in bytes, or zero if failed
   Restrictions:
     M<=32 
---------------------------------------------------------------------------*/
size_t bqciir_alloc ( int M, int opt );
size_t bqciirf_alloc( int M );

/*---------------------------------------------------------------------------
   Initialize the filter instance. Delay elements are zeroed.
   Input:
     objmem     Memory block of bqciir_alloc(M,opt) or bqciirf_alloc(M) bytes
     M          Number of biquad sections
     opt        Fixed-point implementation variant selector, BQCIIR_OPT_LOW_NOISE
                or BQCIIR_OPT_FAST
     coef[C*M]  Per-section coefficient blocks. Each coefficient block contains
                5 tap coefficients a1,a2,b0,b1,b2 and (only for the fixed-point
                variant) the input gain term g. Coefficients must be ordered
                as shown below:
                  bqciir_init()  C=6: g, b0, b1, b2, a1, a2 (Q14)
                  bqciirf_init() C=5: b0, b1, b2, a1, a2
     gain       Total gain coefficient to be applied to the output of the 
                last biquad. Fixed-point data format for bqciir_init() is Q8
   Output:
     Returns the filter handle, or zero if failed.
   Restrictions:
     M<=32 
---------------------------------------------------------------------------*/
bqciir_handle_t  bqciir_init ( void * objmem, int M, int opt, 
                               const int16_t * coef, int16_t gain );
bqciirf_handle_t bqciirf_init( void * objmem, int M, 
                               const float32_t * coef, float32_t gain );

/*---------------------------------------------------------------------------
   Pass a block of complex input samples to the filter and return filter output
   samples
   Input:
     _bqciir,
     _bqriirf     Filter handle
     N            Input/output signal chunk size, in samples
     x[N]         Complex input samples
   Output:
     r[N]         Complex output samples
   Temporary:
     scr[8*N+32]  Scratch memory block, in bytes; required by the Low Noise 
                  fixed-point implementation variant (BQCIIR_OPT_LOW_NOISE), 
                  otherwise may be null
   Restrictions:
     x,r          Aligned on 4-byte (bqciir) or 8-byte (bqciirf) boundary
     scr          Aligned on 32-byte boundary, whenever supplied
---------------------------------------------------------------------------*/
void bqciir_process ( bqciir_handle_t      _bqciir, 
                      complex_fract16 * restrict   r,
                const complex_fract16 *            x,
                      void * restrict           scr,
                      int                          N );
void bqciirf_process( bqciirf_handle_t     _bqciirf, 
                      complex_float * restrict r,
                const complex_float *          x,
                      int                      N );

/*-------------------------------------------------------------------------
  Streaming Biquad Real Block IIR 

  Passes a few streams of real data through a series of cascaded biquad 
  sections. Filter implementation is based on Direct Form II aka the
  Canonical Form. Please refer to the NatureDSP Baseband Library Reference
  for details on the filter structure.

  For each section the user has to provide 2 feedback tap coefficients 
  a1, a2, and 3 feedforward tap coefficients b0, b1, b2. Fixed-point filter
  variant also requires the input gain term g to be specified for each biquad
  section. For the final scaling of filter output data, the total gain 
  coefficient (gain) is applied to output samples produced by the last biquad
  section.

  Representation:
  bqriirs    16-bit signed fixed-point format for input/output samples
             and tap coefficients
  bqriirsf   IEEE-754 Std. single precision floating-point format for
             input/output data and tap coefficients

  Implementation of biquad series for fixed-point data format has two flavors:
  Low_Noise  Performs 32x16-bit multiplications and utilizes the scratch
             memory to keep intermediate results in order to lower the
             quantization noise and reduce round-off errors
  Fast       Makes use of native 16x16-bit multipliers and thus appears faster
             than the Low Noise variant at the cost of deteriorated accuracy

  Notes:
  1. Biquad coefficients may be derived from standard SOS and G matrices 
     generated by MATLAB. However, scale factors may require some tuning 
     to find a compromise between quantization noise and possible overflows.
  2. Streaming biquad real block IIR filter may by applied to complex
     data stored in streaming format, which is equivalent to passing a
     complex signal through a complex IIR with real coefficients. The number
     of real data streams L as it is seen by the filter implementation must
     be two times the number of actual complex streams.

  Methods:
      bqriirs[f]_alloc()   - calculate memory block size for a filter instance
      bqriirs[f]_init()    - initialize the filter instance
      bqriirs[f]_process() - pass a block of input samples to the filter and
                             return filter output samples. This operation is
                             simultaneously accomplished for a few independent
                             data streams.
  Restrictions:
      - input/output data arrays must be aligned on 32-byte boundary
      - scratch memory block, whenever supplied, must be 32 bytes aligned
      – number of streams must be a multiple of 16 (bqriirs) or 8 (bqriirsf)
---------------------------------------------------------------------------*/

#define BQRIIRS_OPT_LOW_NOISE        1
#define BQRIIRS_OPT_FAST             0

/* Filter instance structure is defined internally. */
typedef void * bqriirs_handle_t;
typedef void * bqriirsf_handle_t;

/*---------------------------------------------------------------------------
   Calculate the memory block size for a filter with given attributes.
   Input:
     L     Number of streams
     M     Number of biquad sections
     opt   Fixed-point implementation variant selector, BQRIIRS_OPT_LOW_NOISE
           or BQRIIRS_OPT_FAST
   Output:
     Returns required memory block size, in bytes, or zero if failed
   Restrictions:
     L     Must be a multiple of 16 (bqriirs) or 8 (bqriirsf)
---------------------------------------------------------------------------*/
size_t bqriirs_alloc ( int L, int M, int opt );
size_t bqriirsf_alloc( int L, int M );

/*--------------------------------------------------------------------------- 
   Initialize the filter instance. Delay elements are zeroed.
   Input:
     objmem     Memory block of bqriirs_alloc(L,M,opt) or bqriirsf_alloc(L,M) bytes
     M          Number of biquad sections
     L          Number of streams
     opt        Fixed-point implementation variant selector, BQRIIRS_OPT_LOW_NOISE
                or BQRIIRS_OPT_FAST
     coef[C*M]  Per-section coefficient blocks. Each coefficient block contains
                5 tap coefficients a1,a2,b0,b1,b2 and (only for the fixed-point
                variant) the input gain term g. Coefficients must be ordered
                as shown below:
                  bqriirs_init()  C=6: g, b0, b1, b2, a1, a2 (Q14)
                  bqriirsf_init() C=5: b0, b1, b2, a1, a2
     gain       Total gain coefficient to be applied to the output of the 
                last biquad. Fixed-point data format for bqriirs_init() is Q8
   Output:
     Returns the filter handle, or zero if failed.
   Restrictions:
     L          Must be a multiple of 16 (bqriirs) or 8 (bqriirsf)
---------------------------------------------------------------------------*/
bqriirs_handle_t  bqriirs_init ( void * objmem, int L, int M, int opt, 
                                 const int16_t * coef, int16_t gain );
bqriirsf_handle_t bqriirsf_init( void * objmem, int L, int M,
                                 const float32_t * coef, float32_t gain );

/*---------------------------------------------------------------------------
   Pass a block of input samples to the filter and return filter output
   samples
   Input:
     _bqriirs,
     _bqriirsf    Filter handle
     N            Input/output signal chunk size, in samples (per stream)
     x[N*L]       Input samples
   Temporary:
     scr[4*N*L]   Scratch memory block, in bytes; required by the Low Noise 
                  fixed-point implementation variant (BQRIIRS_OPT_LOW_NOISE), 
                  otherwise may be null
   Output:
     r[N*L]       Output samples
   Restrictions:
     x,r          Must be aligned on 32-byte boundary
     scr          Must be aligned on 32-byte boundary, whenever supplied
     L            Must be a multiple of 16 (bqriirs) or 8 (bqriirsf)
---------------------------------------------------------------------------*/
void bqriirs_process ( bqriirs_handle_t     _bqriirs,
                       int16_t * restrict   r,
                 const int16_t *            x,
                       void * restrict   scr,
                       int                  N );
void bqriirsf_process( bqriirsf_handle_t   _bqriirsf,
                       float32_t * restrict r,
                 const float32_t *          x,
                       int                  N );

/*-------------------------------------------------------------------------
  Lattice Real Block IIR

  Passes real input signal through an autoregressive lattice IIR filter with
  real reflection coefficients. Please refer to the NatureDSP Baseband Library
  Reference for details on the filter structure.

  Representation:
  latr       16-bit signed fixed-point format for input/output samples 
             and reflection coefficients
  latrf      IEEE-754 Std. single precision floating-point format for
             input/output data and reflection coefficients

  Implementation of lattice filter for fixed-point data format has two flavors:
  Low_Noise  Performs 32x16-bit multiplications in the feedback branch to attain
             a precise output sample; feedforward products that update the delay
             line are still produced by 16x16-bit multiplications, but the full
             32-bit result is preserved for each delay element to be used on
             future iterations
  Fast       Makes use of native 16x16-bit multipliers and allocates 16 bits for
             a delay element

  Methods:
    latr[f]_alloc()   - calculate memory block size for a filter instance
    latr[f]_init()    - initialize the filter instance
    latr[f]_process() - pass a block of input samples to the filter and return
                        filter output samples
  Restrictions:
    - filter order must not exceed 8: M <= 8
---------------------------------------------------------------------------*/

#define LATR_OPT_LOW_NOISE          1
#define LATR_OPT_FAST               0

/* Filter instance structure is defined internally. */
typedef void * latr_handle_t;
typedef void * latrf_handle_t;

/*-------------------------------------------------------------------------
   Calculate the memory block size for a filter with given attributes.
   Input:
     M     Filter order
     opt   Fixed-point implementation variant selector, LATR_OPT_LOW_NOISE
           or LATR_OPT_FAST
   Output:
     Returns required memory block size, in bytes, or zero if failed
   Restrictions:
     M<=8  Filter order must not exceed 8
-------------------------------------------------------------------------*/
size_t latr_alloc ( int M, int opt );
size_t latrf_alloc( int M );

/*-------------------------------------------------------------------------
   Initialize the filter instance. Delay elements are zeroed.
   Input:
     objmem   Memory block of latr_alloc(M,opt) or latrf_alloc(M) bytes
     M        filter order
     opt      Fixed-point implementation variant selector, LATR_OPT_LOW_NOISE
              or LATR_OPT_FAST
     coef[M]  Filter coefficients; coef[0] matches the newest delayed sample.
              Fixed-point data format for latr_init() is Q15
     gain     Total gain coefficient to be applied to the input. Fixed-point
              data format for latr_init() is Q15
   Output:
     Returns the filter handle, or zero if failed.
   Restrictions:
     M<=8     Filter order must not exceed 8
-------------------------------------------------------------------------*/
latr_handle_t  latr_init ( void * objmem, int M, int opt,
                           const int16_t * coef, int16_t gain );
latrf_handle_t latrf_init( void * objmem, int M,
                           const float32_t * coef, float32_t gain );

/*-------------------------------------------------------------------------
   Pass a block of input samples to the filter and return filter output
   samples
   Input:
     _latr,_latrf  Filter handle
     N             Input/output signal chunk size, in samples
     x[N]          Input samples
   Output:
     r[N]          Output samples
   Restrictions:
     None 
-------------------------------------------------------------------------*/
void latr_process ( latr_handle_t        _latr,
                    int16_t * restrict   r,
              const int16_t *            x,
                    int                  N );
void latrf_process( latrf_handle_t       _latrf,
                    float32_t * restrict r,
              const float32_t *          x,
                    int                  N );

/*-------------------------------------------------------------------------
  Lattice Complex Block IIR w/ Real Coefficients

  Passes complex input signal through an autoregressive lattice IIR filter with
  real reflection coefficients. Please refer to the NatureDSP Baseband Library
  Reference for details on the filter structure.

  Representation:
  latc       16-bit signed fixed-point format for input/output samples 
             and reflection coefficients
  latcf      IEEE-754 Std. single precision floating-point format for
             input/output data and reflection coefficients

  Implementation of lattice filter for fixed-point data format has two flavors:
  Low_Noise  Performs 32x16-bit multiplications in the feedback branch to attain
             a precise output sample; feedforward products that update the delay
             line are still produced by 16x16-bit multiplications, but the full
             32-bit result is preserved for the I/Q component of a delay element
             to be used on future iterations
  Fast       Makes use of native 16x16-bit multipliers and allocates 16 bits for
             the I/Q component of a delay element

  Methods:
    latc[f]_alloc()   - calculate memory block size for a filter instance
    latc[f]_init()    - initialize the filter instance
    latc[f]_process() - pass a block of complex input samples to the filter
                        and return filter output samples
  Restrictions:
    - input/output complex data arrays must be aligned by 4 (latc) or 
      8 (latcf) bytes
    - filter order must not exceed 8: M <= 8
---------------------------------------------------------------------------*/

#define LATC_OPT_LOW_NOISE          1
#define LATC_OPT_FAST               0

/* Filter instance structure is defined internally. */
typedef void * latc_handle_t;
typedef void * latcf_handle_t;

/*-------------------------------------------------------------------------
   Calculate the memory block size for a filter with given attributes.
   Input:
     M     Filter order
     opt   Fixed-point implementation variant selector, LATC_OPT_LOW_NOISE
           or LATC_OPT_FAST
   Output:
     Returns required memory block size, in bytes, or zero if failed
   Restrictions:
     M<=8  Filter order must not exceed 8
-------------------------------------------------------------------------*/
size_t latc_alloc ( int M, int opt );
size_t latcf_alloc( int M );

/*-------------------------------------------------------------------------
   Initialize the filter instance. Delay elements are zeroed.
   Input:
     objmem   Memory block of latc_alloc(M,opt) or latcf_alloc(M) bytes
     M        Filter order
     opt      Fixed-point implementation variant selector, LATC_OPT_LOW_NOISE
              or LATC_OPT_FAST
     coef[M]  Filter coefficients; coef[0] matches the newest delayed sample.
              Fixed-point data format for latc_init() is Q15
     gain     Total gain coefficient to be applied to the input. Fixed-point
              data format for latc_init() is Q15
   Output:
     Returns the filter handle, or zero if failed.
   Restrictions:
     M<=8     Filter order must not exceed 8
-------------------------------------------------------------------------*/
latc_handle_t  latc_init ( void * objmem, int M, int opt,
                           const int16_t * coef, int16_t gain );
latcf_handle_t latcf_init( void * objmem, int M,
                           const float32_t * coef, float32_t gain );

/*-------------------------------------------------------------------------
   Pass a block of complex input samples to the filter and return filter
   output samples
   Input:
     _latc,_latcf  Filter handle
     N             Input/output signal chunk size, in complex samples
     x[N]          Complex input samples
   Output:
     r[N]          Complex output samples
   Restrictions:
     x,r           Aligned by 4 (latc_process) or 8 (latcf_process) bytes
-------------------------------------------------------------------------*/
void latc_process ( latc_handle_t        _latc,
                    complex_fract16 * restrict   r,
              const complex_fract16 *            x,
                    int                          N );
void latcf_process( latcf_handle_t       _latcf,
                    complex_float * restrict r,
              const complex_float *          x,
                    int                      N );

/*-------------------------------------------------------------------------
  Streaming Lattice Block Real IIR

  Passes a few streams of real data through an autoregressive lattice IIR
  filter with real reflection coefficients. Please refer to the NatureDSP
  Baseband Library Reference for details on the filter structure.

  Representation:
  latrs      16-bit signed fixed-point format for input/output samples 
             and reflection coefficients
  latrsf     IEEE-754 Std. single precision floating-point format for
             input/output data and reflection coefficients

  Implementation of lattice filter for fixed-point data format has two flavors:
  Low_Noise  Performs 32x16-bit multiplications in the feedback branch to attain
             a precise output sample; feedforward products that update the delay
             line are still produced by 16x16-bit multiplications, but the full
             32-bit result is preserved for each delay element to be used on
             future iterations
  Fast       Makes use of native 16x16-bit multipliers and allocates 16 bits for
             a delay element

  Note:
    Streaming lattice block real IIR filter may by applied to complex
    data stored in streaming format, which is equivalent to passing a
    complex signal through a complex IIR with real coefficients. The number
    of real data streams L as it is seen by the filter implementation must
    be two times the number of actual complex streams.

  Methods:
    latrs[f]_alloc()   - calculate memory block size for a filter instance
    latrs[f]_init()    - initialize the filter instance
    latrs[f]_process() - pass a block of input samples to the filter and return
                         filter output samples
  Restrictions:
    - input/output data arrays must be aligned on 32-byte boundary
    - filter order cannot exceed 8, M <= 8
    - number of streams must be a multiple of 16 (latrs) or 8 (latrsf)
---------------------------------------------------------------------------*/  

#define LATRS_OPT_LOW_NOISE         1
#define LATRS_OPT_FAST              0

/* Filter instance structure is defined internally. */
typedef void * latrs_handle_t;
typedef void * latrsf_handle_t;

/*---------------------------------------------------------------------------
   Calculate the memory block size for a filter with given attributes.
   Input:
     L     Number of streams
     M     Filter order
     opt   Fixed-point implementation variant selector, LATRS_OPT_LOW_NOISE
           or LATRS_OPT_FAST
   Output:
     Returns required memory block size, in bytes, or zero if failed
   Restrictions:
     M<=8  Filter order cannot exceed 8 
     L     Must be a multiple of 16 (latrs) or 8 (latrsf)
---------------------------------------------------------------------------*/
size_t latrs_alloc ( int L, int M, int opt );
size_t latrsf_alloc( int L, int M );

/*---------------------------------------------------------------------------
   Initialize the filter instance. Delay elements are zeroed.
   Input:
     objmem   Memory block of latrs_alloc(L,M,opt) or latrsf_alloc(L,M) bytes
     L        Number of streams
     M        Filter order
     opt      Fixed-point implementation variant selector, LATRS_OPT_LOW_NOISE
              or LATRS_OPT_FAST
     coef[M]  Filter coefficients; coef[0] matches the newest delayed sample.
              Fixed-point data format for latrs_init() is Q15
     gain     Total gain coefficient to be applied to the input. Fixed-point
              data format for latrs_init() is Q15
   Output:
     Returns the filter handle, or zero if failed.
   Restrictions:
     M<=8     Filter order must not exceed 8
     L        Must be a multiple of 16 (latrs) or 8 (latrsf)
---------------------------------------------------------------------------*/
latrs_handle_t  latrs_init ( void * objmem, int L, int M, int opt,
                             const int16_t * coef, int16_t gain );
latrsf_handle_t latrsf_init( void * objmem, int L, int M,
                             const float32_t * coef, float32_t gain );

/*---------------------------------------------------------------------------
   Pass a block of input samples to the filter and return filter output
   samples
   Input:
     _latrs,_latrsf  Filter handle
     N               Input/output signal chunk size, in samples (per stream)
     x[N*L]          Input samples
   Output:
     r[N*L]          Output samples
   Restrictions:
     x,r             Must be aligned on 32-byte boundary
---------------------------------------------------------------------------*/
void latrs_process ( latrs_handle_t       _latrs,
                     int16_t * restrict   r,
               const int16_t *            x,
                     int                  N );
void latrsf_process( latrsf_handle_t      _latrsf,
                     float32_t * restrict r,
               const float32_t *          x,
                     int                  N );

#ifdef __cplusplus
};
#endif

#endif /* __NATUREDSP_BASEBAND_IIR_H */
